### ISSUE TITLE
GSOC - Real time uploading

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#1]
Closed captions is used by a number of data aggregation companies as once of the sources they add to their data pool. They use the information to correlate appearances on media to things like stock. While doing that for twitter -to mention just one- is easy because there's even an API, it's a lot more difficult to do it for closed captions. We want CCExtractor to be able to upload data as it's produced so it can be used for real time analysis.
The task includes everything from defining the protocol to make the changes in CCExtractor and write reference a implementation of the data receiver.

**Comment by slifty** [comment]
I'm working on a tool currently called Opened Captions which will broadcast several types of text stream over a WebSocket API.  Currently I'm working on the new version and one of the initially supported streams will be captions generated by CCExtractor.

I'll be sure to post here when that is complete in case it is helpful to OP!

**Comment by cfsmp3** [comment]
slifty, your concept of open captions overlaps A LOT with what we are doing. Maybe it makes sense for you to join the team? We're quite active these days since it's the middle of Summer of Code and pretty much everyone is involved.

**Comment by slifty** [comment]
I'd be glad to!  OC was a project from a few years ago back when I was at the Boston Globe (https://github.com/slifty/opened-captions) I'm refreshing it to make it more robust and support new types of text stream.

It would be really great to help out and make sure I'm not completely duplicating certain efforts, is there a mailing list / etc I should join in on?

**Comment by cfsmp3** [comment]
Team communication is happening over slack these days, it's really
convenient. We also have a mailing list but we don't really use it much.

I'll be happy to add you to the group - just need an email address.

**Comment by slifty** [comment]
I use gmail -- handle is the same as github (slifty)!

**Comment by cfsmp3** [comment]
OK, you should have received an invite just now. Welcome!
