### ISSUE TITLE
[BUG] Hulu subtitles no longer being downloaded

### ISSUE THREAD

**Issue by davidsbaldwin** [CCExtractor/ccextractor#1002]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : 0.86

**In raising this issue, I confirm the following (please check boxes, eg [X] - and delete unchecked ones):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [X] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X] - and delete unchecked ones):**

- [ ] I have never used CCExtractor.
- [X] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [ ] NO | [X] YES - *please specify the last known working version*
- What platform did you use? [X] Windows - [ ] Linux - [ ] Mac
- What were the used arguments? `-autoprogram`

**Additional information**

Likely due to the recent Hulu website design change, I can't seem to get subtitles downloaded anymore with CCExtractor. As you can see from screenshots posted at Slack, currently the URLs are using "new.hulu.com" although I assume this will get updated soon to regular hulu.com. 

PS: Make sure you set an alert in GitHub so you get notifications about your ticket. We may need to ask questions and we do everything inside GitHub's system.

**Comment by cfsmp3** [comment]
What tool are you using, what parameters are you passing...? Is there an error message?

**Comment by davidsbaldwin** [comment]
Sure, here are the parameters:

[after running SubtitleExtractor.pyy file]
Paste the link here: https://www.hulu.com/watch/10882b07-2f4b-4f6a-b39b-fe1751e6302b
[it doesn't matter which hulu.com link you input--any of them will output the following]
hulu
Detected Hulu
Processing....

C:\Users\Mulder\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bs4\__init__.py:179: UserWarning: You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.
  warnings.warn("You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.")
Unable to get the subtitles. Please try again and open an issue to request for support for this video.
Subtitles not downloaded.

Hope this helps!

**Comment by MatejMecka** [comment]
This is the Wrong Repository. Suggestion to close it?
