### ISSUE TITLE
[QUESTION] Which license in terms of SPDX is used?

### ISSUE THREAD

**Issue by newbluemoon** [CCExtractor/ccextractor#1013]
Hi!

I’d like to update the ccextractor package for Void Linux. Void strongly encourages the use of [SPDX](https://spdx.org/) license strings. However, I wasn’t able to determine if ccextractor is GPL-2.0-only or GPL-2.0-or-later. I checked the source code files and other documentation, but always found only GPL-2.0 mentioned. I’d be very happy if you could help me out on this. Thanks. :)

**Comment by cfsmp3** [comment]
Assume it's  GPL-2.0-only, that's what we started with and there's too many contributors now to bother changing it to anything else.

**Comment by newbluemoon** [comment]
Ok, thank you! :)
