### ISSUE TITLE
[QUESTION] CCExtractor 0.87 Help on cascading duplicate lines

### ISSUE THREAD

**Issue by sunnyevw** [CCExtractor/ccextractor#1044]
- [x ] I have read and understood the [contributors guide]
- [x ] I have used the latest available version of CCExtractor to verify this issue exists.
- [x ] I absolutely love CCExtractor, but have not contributed previously.
- What platform did you use? [x ] Windows - [ ] Linux - [ ] Mac

https://drive.google.com/drive/folders/1x6cXmWL_P74qCsLolXmuwRq_0GW4nZx8?usp=sharing

The first time I had this issue was with a live showing of a tv show.  However it also occurs every once in a while on shows that aren't live.  This is what happens (the examples are in a shorter version of the 3 minute video and SRT at the above google drive link).  [caption line 1 was just music].  Caption 2 had 3 lines (call them 1, 2, 3); Caption 3 had 3 lines (2, 3, 4); Caption 4 had 3 lines (3, 4, 5).  

I suspect that this can be "fixed" by using the "Teletext line deduplication" section under the Decoder tab.  The instructions are all greek to me and I have no idea where to find "documentation for more information".   Can anyone point me in the right direction?  I could write a stupid program to delete the 2nd and 3rd lines in each caption, but I'm not sure that's the best solution.

**Comment by saurabhshri** [comment]
Hi @sunnyevw ! These type of captions are called roll-up captions. You may use `-noru` parameter to fix duplications.

Without `-noru` :

```
2
00:04:53,359 --> 00:04:58,829
>> So I was like, "You can't    
"Gone Girl" someone if you say  
you're "Gone Girl"-ing him."    

3
00:04:58,831 --> 00:05:00,265
"Gone Girl" someone if you say  
you're "Gone Girl"-ing him."    
>> Yeah, that is too true.      

4
00:05:00,267 --> 00:05:02,233
you're "Gone Girl"-ing him."    
>> Yeah, that is too true.      
Okay, wait, wait, wait.       
```

With `-noru` :

```
2
00:04:53,359 --> 00:04:58,829
>> So I was like, "You can't    
"Gone Girl" someone if you say  
you're "Gone Girl"-ing him."    

3
00:04:58,897 --> 00:05:03,334
>> Yeah, that is too true.      
Okay, wait, wait, wait.         
To girls night.                 

4
00:05:03,402 --> 00:05:07,505
>> Girls night.                 
>> No rush, ladies.             
 Just whenever you get a chanc
```

**Comment by sunnyevw** [comment]
Oh!  Thank you.  This is certainly what I was looking for.
