### ISSUE TITLE
[BUG] segfault with empty file and -out=report option

### ISSUE THREAD

**Issue by rhertzog** [CCExtractor/ccextractor#1046]
This issue is easy to reproduce (at least on Linux):
```
$ ccextractor -out=report /dev/null
File: /dev/null
Stream Mode: Not Found
EIA-608: No
CEA-708: No
MPEG-4 Timed Text: No
Segmentation fault
```

Here is the version information:
```
CCExtractor 0.87, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
CCExtractor detailed version info
	Version: 0.87
	Git commit: Unknown
	Compilation date: 2018-11-22
	File SHA256: Could not open file
Libraries used by CCExtractor
	Tesseract Version: 4.0.0
	Leptonica Version: leptonica-1.76.0
	libGPAC Version: 0.7.2-DEV
	zlib: 1.2.11
	utf8proc Version: 2.2.0
	protobuf-c Version: 1.1.1
	libpng Version: 1.6.34
	FreeType 
	libhash
	nuklear
	libzvbi
```

**In raising this issue, I confirm the following (please check boxes, eg [X] - and delete unchecked ones):**

- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [X] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X] - and delete unchecked ones):**

- [X] I have used CCExtractor just a couple of times but I'm maintaining its Debian package.

**Comment by rhertzog** [comment]
FWIW, this was initially reported in Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=908914

**Comment by cfsmp3** [comment]
Fixed in master.
