### ISSUE TITLE
Bug: Can't open huge .mp4 files

### ISSUE THREAD

**Issue by Pennyliu999** [CCExtractor/ccextractor#1053]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : **X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X] - and delete unchecked ones):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X] - and delete unchecked ones):**

- [ ] I have never used CCExtractor.
- [x I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [ ] NO | [x] YES - *please specify the last known working version* 0.85
- What platform did you use? [x] Windows - [ ] Linux - [ ] Mac

I tried to use 0.87 to extract the subtitles from many MP4 files which are over 4GB, and I failed in all of them, sometimes the file is failed to open, like,

Analyzing data with GPAC (MP4 library)
Opening 'Z:\1965.mp4': Failed to open input file (gf_isom_open() returned error)

Sometimes it just stopped, I copied the warning message from the pop-up window here,

AppName: ccextractorwin.exe	 AppVer: 0.0.0.0	
ModName: ccextractorwin.exe
ModVer: 0.0.0.0	 Offset: 001067e3

I also tried the command line and it doesn't work either.

I confirm in 0.85 I can open the files and extract the subtitles.

**Comment by thealphadollar** [comment]
@Pennyliu999 Can you please attach the mentioned file? Maybe upload it to GDrive and give us a link so that we can analyze the issue better :)

**Comment by Pennyliu999** [comment]
@thealphadollar Thanks for the reply, but the file is literarily too huge to upload (over 4GB), I will try but I'll be appreciated if you may test 0.87 with some huge .mp4 files in your hand.

I've tried some small files which is less than 100 MB and 0.87 works perfectly.

I will keep you updated if I can successfully upload a huge file, thanks.

**Comment by thealphadollar** [comment]
Sure. I've tested it with huge files (around 2GBs) and it works fine for me. It could be issue with the specific file.

**Comment by Pennyliu999** [comment]
@thealphadollar Yes, I think it's not about the size but some kind of coding problem. I tested with a .mp4 which is less than 2 GB and 0.87 still doesn't work (while 0.85 works)

For your information, I downloaded the video files from Apple and removed the drm, 0.87 works with none of them. I will try to upload the file which is smaller than 2 GB for you to test and keep you informed.

**Comment by thealphadollar** [comment]
Thank you, I'll test them out once you've provided them.

*Shivam Kumar Jha*

*Department Of Computer Science And Engineering*
*Indian Institute of Technology Kharagpur*

*Web <https://thealphadollar.github.io> || Github
<https://github.com/thealphadollar/> || LinkedIn
<https://www.linkedin.com/in/thealphadollar/>
<https://thealphadollar.github.io/>*

**Comment by Pennyliu999** [comment]
@thealphadollar Please check this file, thanks for your time.
https://s3-ap-southeast-1.amazonaws.com/tortoise/test2.mp4

**Comment by thealphadollar** [comment]
@Pennyliu999 I'm unable to download the video file from Amazon AWS with the link provided.

**Comment by Pennyliu999** [comment]
@thealphadollar Sorry I forgot to make the file "public", now it should be OK, please try again.

**Comment by thealphadollar** [comment]
@cfsmp3 I can confirm this is one of the issues for which I updated GPAC before GSoC 2018 but wasn't fixed. This is some issue on the end of GPAC in handling these type of MP4 files. I don't think we can do much in this regard. I'm attaching the error log of the file by running on latest version of CCExtractor (0.87).

[Error Log](http://txt.do/diiya)

At the same time, **CCextractor is able to generate subtitle files** for all the languages for which they are available inside the video. I cannot confirm if they are correct but I can say that they match what is being shown by VLC to me.

How did you build? @Pennyliu999 
I built with OCR support using cmake method.

**Comment by Pennyliu999** [comment]
@thealphadollar I didn't build the video, I downloaded it from Apple, so I guess it's encoded by some software based on Mac OS, I've no idea how they did that though.

Glad to know the problem will be fixed, and I think I can only wait for the latest version of CCExtractor?

**Comment by thealphadollar** [comment]
What is the problem? I'm unable to get you; subtitles from the video file
you provided me are extracted perfectly.

**Comment by Pennyliu999** [comment]
@thealphadollar Sorry, I can't extract subtitles from the .mp4 I uploaded to aws, the .exe stopped and I got a pop-up window with error message and that's all. If it works for you, maybe it's some problem with my windows system.

Could you please upload the subtitles and share them with me? That's the main purpose I used CCExtractor, anyway.

**Comment by thealphadollar** [comment]
Here are the files: https://drive.google.com/open?id=14KQozOPN-V1NcTyU5Y-eV-hO_4WEElTB

I used CCExtractor on Linux; the windows version is not that stable (or up to date).

**Comment by Pennyliu999** [comment]
@thealphadollar Thank you very much! Maybe I will try the linux version someday.

**Comment by MakarovGCI2018** [comment]
The error comes from this line of code:
https://github.com/CCExtractor/ccextractor/blob/master/src/gpacmp4/box_code_3gpp.c#L339

We get an exception
![image](https://user-images.githubusercontent.com/44312997/49835351-94a4e380-fda7-11e8-8daa-1fc6b565951d.png)

If we just comment this line ccextractor works well and detects those subtitles but doesn't extract them to file. By the way I'm working on this issue

**Comment by MakarovGCI2018** [comment]
[log_with_error.txt](https://github.com/CCExtractor/ccextractor/files/2669766/log_with_error.txt)
[log_without_error.txt](https://github.com/CCExtractor/ccextractor/files/2669768/log_without_error.txt)

**Comment by cfsmp3** [comment]
Take a look at that file in the current GPAC source code. Maybe it's a bug they fixed already. Or maybe we introduced a bug when we last backported GPAC.

**Comment by Pennyliu999** [comment]
Thanks for all your efforts, and I confirm this bug only happens or exists in windows version, I tried to run 0.87 in Mac OS via homebrew and it works perfectly just like in Linux.

**Comment by NilsIrl** [comment]
Has someone got the file?

**Comment by Pennyliu999** [comment]
> Has someone got the file?

The problem is fixed so I delete the file
