### ISSUE TITLE
[Bug] xFF marker after each line in output and incorrect font detected(CEA-708) 

### ISSUE THREAD

**Issue by MakarovGCI2018** [CCExtractor/ccextractor#1055]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : **X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X] - and delete unchecked ones):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [X] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X] - and delete unchecked ones):**

- [ ] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [X] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [X] NO | [ ] YES - *please specify the last known working version*
- What platform did you use? [X] Windows - [ ] Linux - [ ] Mac
- What were the used arguments? `[input_file] -o [output_file] -svc all`

**Links**
Video file:
https://drive.google.com/open?id=1rfnIMi_aYv_0k7OEkOwUtnS1ZEg4Vf2w
Srt file:
https://drive.google.com/open?id=1xScuwCFZa7Yn0deBHgUQvPilnE9XM2OW

**Additional information**
I downloaded video file(.mpg) which contains cea-708 captions. PotPlayer detects it fine. CCExtractor couldn't extract them until current version but now it wrote subtitles to the output with xFF marker at the end of each line.
What's more it detects font color as "aaaaaa".

**Comment by MakarovGCI2018** [comment]
* Note:
It detects subtitles with changes that were described here https://github.com/CCExtractor/ccextractor/issues/677#issuecomment-446376128
Without those changes it doesn't extract subtitles, so this issue is same to https://github.com/CCExtractor/ccextractor/issues/677 that's why I close it

**Comment by ValZapod** [comment]
> * Without those changes it doesn't extract subtitles, so this issue is same to

@cfsmp3 Looks like not the same.
