### ISSUE TITLE
[BUG] rpm build errors - missing freetype sources in tar.gz and configure mismatches between src and rpm

### ISSUE THREAD

**Issue by tomas-kuchta** [CCExtractor/ccextractor#1064]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : 0.87

**In raising this issue, I confirm the following (please check boxes, eg [X] - and delete unchecked ones):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X] - and delete unchecked ones):**

- [ ] I have never used CCExtractor.
- [x] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [x] NO | [] YES - *please specify the last known working version* - I am not sure actually
- What platform did you use? [ ] Windows - [x] Linux - [ ] Mac
- What were the used arguments? `-autoprogram`

**Video links (replace text below with your links) **

None needed

**Additional information**

Running ./rpm.sh from package_creators directory fails due to following issues:
1. incorrect version 0.85 instead of 0.87 in file: ccextractor.spec
2. changed ./configure command in package_creators/tarbal.sh to:
   ./configure --prefix=/usr --enable-ocr
3. missing freetype source files ft2build.h, ... in generated RPMBUILD/SOURCES/ccextractor-0.87.tar.gz
   Adding directory full src/freetype directory to the tar file at creation resolves the build issue.

Build done on: openSuSE 42.3 with following ccextractor specific dependencies:

Thank you, Tomas

PS: Make sure you set an alert in GitHub so you get notifications about your ticket. We may need to ask questions and we do everything inside GitHub's system.

**Comment by djotaku** [comment]
I also got hit with the spec file issue. 

Also the tarball is missing iso639.h, but that's in the git repo

**Comment by tomas-kuchta** [comment]
Missing iso639.h can also be resolved by changing ./configure command to: ./configure --enable-ocr in package_creators/tarball.sh

This is because both ./configure commands in tatrball.sh and rpm.sh needs to be the same <== tarball.sh creates ccextractor-version.tar.gz which is then used as source for rpm.sh <== thus using rpm.sh to verify the content of ccextractor-version.tar.gz which is used to create source .rpm

I did not have the time to get to the root cause of why the freetype sources are not added to the tar file. Perhaps it is due to missing 'autoreconf -i'  command inside tarball.sh - just speculating at this point.

I guess, both adding the iso639.h to the .tar as well as matching the .configure commands are equally valid hacks. :-)

**Comment by djotaku** [comment]
I know it's been 9 months, but when I change the config argument in the tarball.sh, it still says it doesn't have that file.

**Comment by djotaku** [comment]
I'm making some potential headway changing the linux/Makefile.am. If I can get it to go all the way, will make a PR

**Comment by cfsmp3** [comment]
Closing this this was merged. @tomas-kuchta feel free to reopen if it still doesn't work for you.
