### ISSUE TITLE
[BUG] extracting dvb subs from udp doesnt work while extracting from same file works

### ISSUE THREAD

**Issue by jakubvojacek** [CCExtractor/ccextractor#1069]
CCExtractor version: **0.87**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows :**

- [x] I absolutely love CCExtractor, but have not contributed previously.

**Necessary information**

- Is this a regression (did it work before)? [x] NO | [ ] YES - *please specify the last known working version*
- What platform did you use? [ ] Windows - [x] Linux - [ ] Mac
- What were the used arguments? `-autoprogram`

```
ccextractor  -ocrlang spa -quant 0  -datapid 0x141f -out=webvtt  -trim -lf -nots -nobom -nofc -nogt -udp 229.0.0.150:2000 -o test.vtt
```

**Video links**

https://bit.ly/2sWLbTE

**Additional information**
When I try to extract the dvb subs from the file, there are no issues. But when I play the file in a loop with tsplay `tsplay fox.mp4 229.0.0.150:2000 -loop`, it does not extract anything. 

Since it is possible to extract the subtitles from the file itself and VLC does also display them (dvb_subtitle pid 0x141f maps to program 779), shouldnt it be possible to extract them from multicast too?

Thank you
Jakub

**Comment by cfsmp3** [comment]
if tsplay if converting a TS into a mp4 then most likely captions are just lost in the conversion and there's no captions there at all to begin with.

Also, mp4 probably won't work at all via network because we use GPAC which expects a file if I remember correctly.

**Comment by jakubvojacek** [comment]
@cfsmp3 Hello,

it's not an mp4. it is actually a TS file but I had to change extension since the webserver only allows downloading mp4. The tsplay preserves subtitles, just tried to run ffprobe on it 

```
Input #0, mpegts, from 'udp://229.0.0.150:2000':
  Duration: N/A, start: 20519.244833, bitrate: N/A
  Program 764 
    Stream #0:12[0x3f2]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], 29.97 fps, 59.94 tbr, 90k tbn, 59.94 tbc
    Stream #0:32[0x321](eng): Audio: ac3 ([6][0][0][0] / 0x0006), 48000 Hz, 5.1(side), fltp, 384 kb/s
    Stream #0:33[0x322](spa): Audio: ac3 ([6][0][0][0] / 0x0006), 48000 Hz, stereo, fltp, 384 kb/s
    Stream #0:34[0x19fb](spa): Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006)
  Program 736 
    Stream #0:8[0x2c6]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], 29.97 fps, 59.94 tbr, 90k tbn, 59.94 tbc
    Stream #0:10[0x2bd](eng): Audio: ac3 ([6][0][0][0] / 0x0006), 48000 Hz, 5.1(side), fltp, 384 kb/s
    Stream #0:11[0x2be](spa): Audio: ac3 ([6][0][0][0] / 0x0006), 48000 Hz, stereo, fltp, 384 kb/s
    Stream #0:23[0x993](spa): Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006)
```

The actual problem is not with the TS file but with the multicast that I recorded the file from. Ccextractor fails to read the captions from the multicast and succeeds from the recorded file. Since I could not share the multicast, I shared the recording and tsplay option to make it multicast again - to demonstrate the from file it works and from UDP it does not. 

Thank you
Jakub

**Comment by jakubvojacek** [comment]
Resolved by converting MPTS to SPTS, closing, thank you
