### ISSUE TITLE
[REQUEST] Support EAI-608 closed captions on MP4 video contained in a MKV file

### ISSUE THREAD

**Issue by ReportX** [CCExtractor/ccextractor#1070]
I just get a MKV file which contains a MP4/h264 track with interlaced closed captions. I was not able to extract them using CCExtractor 0.87 (Windows) even trying with multiple settings.

Refer to the magnet link I have given below in order to download a sample (4.29GB) using any compatible BitTorrent client (like Transmission, uTorrent,...):

magnet:?xt=urn:btih:BDE889FBD51470BFD4DB9D01A7802C1809765AFD&dn=T76AGGA2019&tr=http%3a//tracker.trackerfix.com%3a80/announce

**Comment by thelastpolaris** [comment]
I am already working on this request. You can track the progress here https://github.com/CCExtractor/ccextractor/issues/1068

**Comment by cfsmp3** [comment]
@ReportX code for this has been merged - please test and let us know how it works for you.
