### ISSUE TITLE
XDS data parsing

### ISSUE THREAD

**Issue by arianaa30** [CCExtractor/ccextractor#1071]
We have used CCExtractor for parsing Vchip information. It looks like for `vchipflags`, some processing is done. What I see on my end looks processed. For instance for TV-PG `D` I don't simply get `D`!
I get `Sexually Suggestive Dialog`! And similarly, I see `Adult Language` for `L`.

Is CCExctractor adding these descriptive texts? Where can I get those mappings?

**Comment by aadibajpai** [comment]
https://github.com/CCExtractor/ccextractor/blob/7b4bf0b15a01cc5e58fd8bc375359b89430660eb/src/lib_ccx/ccx_decoders_xds.c

**Comment by arianaa30** [comment]
Yes found it. Thanks!
