### ISSUE TITLE
[BUG] Windows Compile Error - Fix for OCR lib

### ISSUE THREAD

**Issue by ggnull35** [CCExtractor/ccextractor#1074]
I am using the latest git version. When I try to build Debug-Full on Windows VS2017 gives out cannot find capi.h error.

I fixed to lines to:

ocr.c Line 4: #include "capi.h"
params.c Line 19: #include "capi.h"

Before they were: #include "tesseract/capi.h"

**Comment by cfsmp3** [comment]
This was solved already. Note that your change made it compile on Windows but broke it on linux.
