### ISSUE TITLE
[BUG] Windows Compile Error for FFmpeg Integration

### ISSUE THREAD

**Issue by ggnull35** [CCExtractor/ccextractor#1075]
I use latest git version.

If I enable FFmpeg integration as mentioned in FFmpeg integration document for Windows compile, Windows 2017 gives error ar:

ffmpeg_intgr.c
Line 5:  #include <libavfilter/avfiltergraph.h>

as file not found.

Afaik, there is no avfiltergraph.h in current FFmpeg git master. I removed the line and compile is completed.

**Comment by Adityak9** [comment]
I read in ffmpeg's github repo that avfiltergraph.h is integrated with avfilter.h, so change avfiltergraph.h with avfilter.h. I don't if it is a correct solution but that is one which i figured out.

**Comment by ggnull35** [comment]
I will give a try.

**Comment by ggnull35** [comment]
It compiles, but in both methods FFmpeg integrated version always fails to probe input.
So, I disabled FFmpeg. There can be need to do more updates.

**Comment by vikramcs** [comment]
Hi,
I was talking about ffmpeg dlls, not the ffmpeginterop project. The dlls created as part the of compilation process described at https://trac.ffmpeg.org/wiki/CompilationGuide/WinRT are required by the ffmpeginterop project. The later will not build without these (it must be why VS says the project is outdated, it was never built).

Check that "make" an "make install" created dlls, check the path were they were copied to. It will be something like Build/Windows...
In Visual Studio, check the ffmpeginterop solution platforms drop down (or go to the Build tab > Configuration manager). Make sure the selected entry (active platform) matches the platform you built ffmpeg for (x64, arm, ...).
Hope this helps.

**Comment by cfsmp3** [comment]
@ggnull35 Is this still happening?

**Comment by cfsmp3** [comment]
Closing - we know it's fixed (plus no reply from user)
