### ISSUE TITLE
[BUG] Stream mode does not work for in-progress TS file

### ISSUE THREAD

**Issue by MaximVol** [CCExtractor/ccextractor#1081]
CCExtractor version: 0.84

**In raising this issue, I confirm the following (please check boxes, eg [X] - and delete unchecked ones):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X] - and delete unchecked ones):**

- [X] I absolutely love CCExtractor, but have not contributed previously.

**Necessary information**
- Is this a regression (did it work before)? [X] NO | [ ] YES - *please specify the last known working version*
- What platform did you use? [ ] Windows - [X] Linux - [ ] Mac

CCExtractor in stream mode work incorrectly with in-progress TS file, after some time it dies with "error while decoding MB" error message.

TS file is recording by StreamLink program:

streamlink --output 1.ts https://www.bloomberg.com/live/us best

Command line of CCExtractor is following:

ccextractor --stream -out=srt -nobom -o 1.srt 1.ts

Output of CCExtractor is:

CCExtractor 0.84, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: 1.ts
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: Auto] [Debug: No] [Buffer input: No]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .srt] [Encoding: UTF-8] [Delay: 0] [Trim lines: No]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: Yes, no timeout] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]

-----------------------------------------------------------------
Opening file: 1.ts
[warning][(null)] start time for stream 2 is not set in estimate_timings_from_pts
[warning][(null)] start time for stream 3 is not set in estimate_timings_from_pts
[warning][(null)] start time for stream 4 is not set in estimate_timings_from_pts
[warning][(null)] PES packet size mismatch
Analyzing data in general mode
Creating 1.srt
Streaming |  00:40[warning][(null)] PES packet size mismatch
[error][(null)] error while decoding MB 67 1, bytestream -12
[info][(null)] concealing 3502 DC, 3502 AC, 3502 MV errors in P frame

Number of NAL_type_7: 0
Number of VCL_HRD: 0
Number of NAL HRD: 0
Number of jump-in-frames: 0
Number of num_unexpected_sei_length: 0

Total frames time:        00:00:00:000  (0 frames at 29.97fps)
Done, processing time = 33 seconds
This is beta software. Report issues to carlos at ccextractor org...

**Comment by thelastpolaris** [comment]
For how much time should I run CCExtractor with the stream you provided to get an error? I'm running CCExtractor 0.87 for 2 hours and it works pretty well (extracts subtitles).

**Comment by MaximVol** [comment]
I built latest version of CCExtractor from GitHub sources and it works correctly with such streams.
It seems that this issue is fixed in latest version.
Thanks a lot for investigation.
