### ISSUE TITLE
[BUG] Multi-track webvtt subtitles come out decapitated 

### ISSUE THREAD

**Issue by rayfoss** [CCExtractor/ccextractor#1093]
**Description**
The WEBVTT header is missing from all but one of the output subtitles. Is this intended behaviour? FFMpeg refuses to process these, for good reason.

**Video links (replace text below with your links)**

[tripple.zip](https://github.com/CCExtractor/ccextractor/files/3263768/tripple.zip)

**Necessary information**
- CCExtractor version (using the --version parameter preferably) : tag v0.88
- Is this a regression (did it work before)? [x] NO | [ ] YES - *please specify the last known working version*
- What platform did you use? [ ] Windows - [x] Linux - [ ] Mac
- What were the used arguments? `-out=webvtt`

**Paperwork**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.

- [x] I am an active contributor to CCExtractor.

**Comment by vikramcs** [comment]
Web Video Text Tracks Format (WebVTT) is a format for displaying timed text tracks (such as subtitles or captions) using the <track> element. The primary purpose of WebVTT files is to add text overlays to a <video>. WebVTT is a text based format, which must be encoded using UTF-8. Where you can use spaces you can also use tabs. There is also a small API available to represent and manage these tracks and the data needed to perform the playback of the text at the correct times.
WEBVTT

00:01.000 --> 00:04.000
Never drink liquid nitrogen.

00:05.000 --> 00:09.000
- It will perforate your stomach.
- You could die.

**Comment by cfsmp3** [comment]
@rayfoss could you confirm if this is still the case? (there was some webvtt related work some time ago, so this might or might not be fixed). Thanks.

**Comment by cfsmp3** [comment]
Closing due to OP @rayfoss not replying.
