### ISSUE TITLE
[QUESTION] Instructions for using ccextractor with Tesseract 4

### ISSUE THREAD

**Issue by rboy1** [CCExtractor/ccextractor#1096]
Please prefix your issue with one of the following: [QUESTION].

CCExtractor version (using the --version parameter preferably) : **0.88**

**My familiarity with the project is as follows (check one, eg [X] - and delete unchecked ones):**

- [ ] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [X] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [X] NO | [ ] YES - *please specify the last known working version*
- What platform did you use? [X] Windows - [ ] Linux - [ ] Mac

What are the instructions for using CCExtractor 0.88 with Tesseract 4? Does it mean Tesseract 3.04 won't work anymore?

The docs page doesn't seem to talk about this, can it updated to include that information please.

https://github.com/CCExtractor/ccextractor/blob/master/docs/OCR.md

**Comment by soulspark666** [comment]
According to https://github.com/UB-Mannheim/tesseract/wiki Tesseract 5.0 exists. I think updating the ccextractor to 5.0 build and then updating the OCR.md will be a better option.

**Comment by rboy1** [comment]
In the meanwhile can someone confirm if 0.88 works with Tesseract v3 or only v4 or both and/or if there's any difference in the stability/quality between the two.

**Comment by rboy1** [comment]
Anyone thoughts?

**Comment by vikramcs** [comment]
CCExtractor is a tool used to produce subtitles for TV recordings from almost anywhere in the world. We intend to keep up with all sources and formats.

Subtitles are important for many people. If you're learning a new language, subtitles are a great way to learn it from movies or TV shows. If you are hard of hearing, subtitles can help you better understand what's happening on the screen. We aim to make it easy to generate subtitles by using the command line tool or Windows GUI.

The official repository is (CCExtractor/ccextractor) and master being the most stable branch.

**Comment by NilsIrl** [comment]
I can confirm it works with both v3 and v4.

However I've had terrible results with v4

**Comment by NilsIrl** [comment]
For me what I did is I just installed tesseract4 instead of tesseract3 and then built it
