### ISSUE TITLE
[QUESTION] -o [filename] ignored?

### ISSUE THREAD

**Issue by djaydev** [CCExtractor/ccextractor#1107]
Ccextractor ran with following command:
ccextractor /watch/The\ Boondocks/Season\ 4/The\ Boondocks\ -\ S04E01\ -\ Pretty\ Boy\ Flizzy.mkv -o /watch/test.srt

No matter what filename I specify after "-o" it uses what seems to be the default filename.

It detects, extractors subs, and everything else correctly.  Filename is the only issue.

Resulting output from Ccextractor after above command:

CCExtractor 0.88, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: /watch/The Boondocks/Season 4/The Boondocks - S04E01 - Pretty Boy Flizzy.mkv
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: Auto] [Debug: No] [Buffer input: No]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .srt] [Encoding: UTF-8] [Delay: 0] [Trim lines: No]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]
[Quantisation-mode: CCExtractor's internal function]

-----------------------------------------------------------------

Opening file: /watch/The Boondocks/Season 4/The Boondocks - S04E01 - Pretty Boy Flizzy.mkv

File seems to be a Matroska/WebM container

Analyzing data in Matroska mode

Document type: matroska
Timecode scale: 1000000
Muxing app: libebml v1.3.0 + libmatroska v1.4.1
Writing app: mkvmerge v6.9.1 ('Blue Panther') 64bit built on Apr 18 2014 18:23:38

Track entry:
    Track number: 1
    UID: 14161443255092300682
    Type: video
    Codec ID: V_MPEG4/ISO/AVC

Notice: NAL of type 7 had to be skipped because remove_03emu failed.

Track entry:
    Track number: 2
    UID: 9408821473790462100
    Type: audio
    Codec ID: A_AC3

Track entry:
    Track number: 3
    UID: 14035373191123350963
    Type: subtitle
    Codec ID: S_TEXT/UTF8
    Language: und

  0%  |  00:00
  0%  |  00:01
  0%  |  00:01
...
...
 99%  |  22:35

100%  |  22:35
Output file: /watch/The Boondocks/Season 4/The Boondocks - S04E01 - Pretty Boy Flizzy_und.srt

Found AVC track. 

Total frames time:	  00:00:00:000  (0 frames at 29.97fps)

Min PTS:				00:00:00:000
Max PTS:				00:22:35:063
Length:				 00:22:35:063

Done, processing time = 1 seconds
Issues? Open a ticket here
https://github.com/CCExtractor/ccextractor/issues

**Comment by thealphadollar** [comment]
@djaydev Thank you for the report, I'll try to look into this around 20th and get back to you with more details or a fix.

**Comment by thealphadollar** [comment]
@djaydev Can you please provide the video file as well if it is not under any license?

**Comment by cfsmp3** [comment]
I haven't look into this but my (uneducated) guess would be that this only
affects .mkv files (but probably all of them).

**Comment by djaydev** [comment]
@thealphadollar I don't have a sample file I can upload but it happens on every MKV file I have,  .TS or .MP4 containers all work fine with "-o" and the codec doesn't seem to make a difference.

**Comment by thealphadollar** [comment]
@djaydev Hey, I cannot reproduce the error since for me it is respecting the `-o` parameter given and producing the output of the file in the desired filename in the specified folder. Below is the argument I used exactly after compiling the latest version of CCExtractor with commit hash 0f2a5b3

`../ccextractor ./Discovery\ Channel\ -\ Worlds\ Best\ Beaches\ HD\ 720p.mkv -o subs.srt`

I built this using the build script inside linux folder. Please confirm the exact steps and the file you have given to reproduce the error.

**Comment by djaydev** [comment]
Since it's working for you it has to be something I'm doing on my system.  Thanks for looking into it.

I compiled from master branch on Sept 10, 2019
