### ISSUE TITLE
[first use] issues

### ISSUE THREAD

**Issue by fredsky2003** [CCExtractor/ccextractor#1112]
using CC extractor GUI in Windows

1) i got some NUL characters when extracting to SRT or TTML. i've to use notepad++ to get rid of those "\0".  please remove them all

2) make Encoding : UTF8 the default option. in the Preview screen, please display correctly those UTF8 characters (instead of a diamond with "?")

3) please add a SCC output option, that will be "as in the source". that means that it will easily allow : respect of horizontal and vertical positioning + roll-up mode

4) respect of horizontal and vertical positioning doesn't work, and first time ever i've seen a tool that use space to make fake horizontal position...

5) vertical positioning : not working either

6) in TTML export, i got a XML with wrong syntax (missing field); notepad++ raised error on save...

7) in ASS export, <i></i> seem to not be a valid way of indicating italic. at least the excellent EZconvert (you can get a free demo - max 25 subtitles) doesn't recognize them.
in TTML export, the span is misplaced to enable italic to work.

so an easy a fast tool to export from mpg/ts file as basic SRT.
for excellent result (but only with MXF and MOV), use Adobe Premiere

fred

**Comment by cfsmp3** [comment]
Each of these things need to go in its own ticket.

Samples are needed.

**Comment by cfsmp3** [comment]
closing, see previous comment
