### ISSUE TITLE
[BUG] eng.traineddate not found! No Switching Possible

### ISSUE THREAD

**Issue by anthonyeden** [CCExtractor/ccextractor#1113]
CCExtractor version (using the --version parameter preferably) : **0.88**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows:**

- [x] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [x] NO | [ ] YES - *unsure last known working version*
- What platform did you use? [x] Windows - [ ] Linux - [ ] Mac
- What were the used arguments? `ccextractor -hardsubx "input.mp4" -o out.srt`

**Video links (replace text below with your links)**

My source material is DVD Rips. I can supply a private Dropbox link if you supply an email address to send it to.

**Additional information**

When I run ccextractorwinfull.exe on Windows 7 x64, I get the following output:

    CCExtractor 0.88, Carlos Fernandez Sanz, Volker Quetschke.
    Teletext portions taken from Petr Kutalek's telxcc
    --------------------------------------------------------------------------
    HardsubX (Hard Subtitle Extractor) - Burned-in subtitle extraction subsystem
    eng.traineddata not found! No Switching Possible

Then, I get the 'your program has stopped working' Windows error message. When I manage to load it in my VS2017 debugger, it mentions an access violation.

This could be an installation issue - are there dependancies that must be installed? I couldn't find a full guide on installation.

I have found and places 'eng.traineddata' in the same folder as 'ccextractorwinfull.exe', but this doesn't make a difference.

**Comment by RaXorX** [comment]
Apparently you can fix this by putting the eng.traineddata (by downloading it through the GitHub repo or copying it from the tessdata directory from the installation folder.

Nonetheless, all you have to do is create a folder named tessdata inside CCextractor folder where the "ccextractorwinfull.exe" is and it'll detect the eng.traineddata as usual.

Although, this only works for the English language and will only detect the said above file. If you do it for a different language it won't. Now there lies my problem, since I have tried everything in my case and I am trying to scan for Chinese language but apparently find nothing at all about it. I'll open a new bug thread for it perhaps.

**Comment by NilsIrl** [comment]
I don't know how relevant it is to your problem, especially because it seems to be a permission issue rather than anything else, but you can use the `TESSDATA_PREFIX` environment variable to show where the data is located

**Comment by cfsmp3** [comment]
It would be useful to display a detailed error message that is actually helpful (for example, write which specific directories were checked for the train files, and what actions the user can take to fix the problem - maybe set the env variable, or actually download the required files and where from).

**Comment by cfsmp3** [comment]
@anthonyeden I'm closing this because there's been work about it in the past few weeks - feel free to reopen if you are still having problems.
