### ISSUE TITLE
[QUESTION] Quick way to check for Closed Captions

### ISSUE THREAD

**Issue by HaveAGitGat** [CCExtractor/ccextractor#1117]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : **X.X**

**My familiarity with the project is as follows (check one, eg [X] - and delete unchecked ones):**

- [ X] I have used CCExtractor just a couple of times.

**Necessary information**
- Is this a regression (did it work before)? [X] NO | [ ] YES - *please specify the last known working version*
- What platform did you use? [X ] Windows - [ ] Linux - [ ] Mac

**Additional information**

Just wondering if there's a quick way to check for Closed Captions without actually extracting anything? At the moment I use:
`
--screenfuls 1`

And then parse the output but this still takes some time (about 8 seconds per file) which adds up.

**Comment by HaveAGitGat** [comment]
I've started using `-endat 01:00 --screenfuls 1` so it stops after the first minute which is a lot quicker but still takes a couple of seconds to process and there's the possibility that a file will have closed captions after the first minute.

**Comment by cfsmp3** [comment]
There's no way to be sure that there's no captions without processing the whole file.

**Comment by vikramcs** [comment]
I've started using -endat 01:00 --screenfuls 1 so it stops after the couples of minute which is a lot quicker but still takes a couple of seconds to process and there's the possibility that a file will have closed captions after the first minute.
</head>
  <body>
    <par>
      <video region="videoregion" src="Movie_Sample.mov"/>
      <textstream region="textregion" src="Movie_Caption.qt.txt"/>  
    </par>
    
  </body>
</smil>

**Comment by HaveAGitGat** [comment]
@vikramcs  ?

**Comment by canihavesomecoffee** [comment]
@HaveAGitGat It's some sort of spam bot...
