### ISSUE TITLE
[PROPOSAL] Add an option to output Scenarist Closed Caption format (*.SCC) and/or McPoodle's Disassembly format (*.CCD)

### ISSUE THREAD

**Issue by The-Bart-The** [CCExtractor/ccextractor#1120]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : THIS WOULD APPLY TO VERSIONS AFTER **0.88**

**In raising this issue, I confirm the following (please check boxes, eg [X] - and delete unchecked ones):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [X] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X] - and delete unchecked ones):**

- [ ] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [x] I am an active contributor to CCExtractor. (I have posted once before. I use CCExtractor A LOT.)

**Necessary information**
- Is this a regression (did it work before)? [X] NO | [ ] YES - *please specify the last known working version*
- What platform did you use? [X] Windows - [ ] Linux - [ ] Mac
- What were the used arguments? `-autoprogram` (not applicable yet)

**Video links (replace text below with your links)**

Please make the affected input file available for us (no screenshots, those don't help!). Public links to Dropbox, Google Drive, etc, are all fine. If it is not possible to make it available publicly, send us a private invitation (both Dropbox and Google Drive allow that). In this case we will download the file and upload it to the private developer repository.

Do *not* upload your file to any location that will require us to sign up or endure a wait list, slow downloads, etc. If your upload expires make sure you keep it active somehow (replace links if needed). Keep in mind that while we go over all tickets some may take a few days, and it's important we have the file available when we actually need it.

**Additional information**

In my spare time I've been writing a script (JavaScript in a web page for now) to convert closed caption disassembly files to advanced substation alpha.  It's a long story, but the punchline is I like to watch my shows with the captions looking like captions.  That means black background behind the text, monospaced fonts, coordinate-positioning, etc., but not all players/playback devices support all the features.

Usually I output into McPoodle's RAW format and command-line programs from SCC_TOOLS to convert to disassembly, but if there was a problem with reception when I recorded the show, then synchronization issues occur (RAW data being what it is). CCExtractor gives me no synchronization issues that I can see when outputting to text formats.

Anyway, my script is over 99% finished for pop-on captions, 0% for paint-on captions, and 0% for roll-up captions. I can post my work so far, if anyone's interested.

Thank you all for your time, and thank you for such a useful project that I use nearly every day.

PS: Make sure you set an alert in GitHub so you get notifications about your ticket. We may need to ask questions and we do everything inside GitHub's system.

**Comment by cfsmp3** [comment]
Send a pull request? :-)

**Comment by NilsIrl** [comment]
I will try to have a look at this tomorrow

**Comment by NilsIrl** [comment]
Best reference I could find: http://www.theneitherworld.com/mcpoodle/SCC_TOOLS/DOCS/SCC_FORMAT.HTML

A nice summary: https://resolver.tools/kb/scc-sonic-scenarist/

**Comment by NilsIrl** [comment]
**real** reference: https://www.govinfo.gov/app/details/CFR-2011-title47-vol1/CFR-2011-title47-vol1-sec15-119/

**Comment by NilsIrl** [comment]
other tutorial/information: 

https://labs.inqscribe.com/exporter/scc/
http://docs.inqscribe.com/2.2/format_scc.html

**Comment by NilsIrl** [comment]
For disassembly:

http://www.theneitherworld.com/mcpoodle/SCC_TOOLS/DOCS/SCC_TOOLS.HTML#ccd
http://docs.inqscribe.com/2.2/format_scc.html#iccd

**Comment by NilsIrl** [comment]
This is the extended standard: https://www.techstreet.com/standards/cta-608-e-r2014?product_id=1815447

**Comment by NilsIrl** [comment]
@The-Bart-The do you have any files that I can test it on and verify if my output is correct?

**Comment by The-Bart-The** [comment]
Here you go: https://www.dropbox.com/s/x7cpz57rw5kz2tw/Broadcast%20Source.zip?dl=1 direct from The Sears Tower or wherever my local Fox affiliate broadcasts.

The video file should produce the included SCC & Disassembly files (which I use to generate the included subtitle file).

**Comment by The-Bart-The** [comment]
The rest of the Disassembly standard is linked from the main McPoodle page here http://www.theneitherworld.com/mcpoodle/SCC_TOOLS/DOCS/CC_CHARS.HTML for character codes and here http://www.theneitherworld.com/mcpoodle/SCC_TOOLS/DOCS/CC_CODES.HTML for control codes.

**Comment by NilsIrl** [comment]
Is there a way I could have more examples?

It would be nice especially if I can have some with colours.

**Comment by The-Bart-The** [comment]
> 
> 
> Is there a way I could have more examples?
> 
> It would be nice especially if I can have some with colours.
> Is there a way I can generate examples?
> 
> @cfsmp3

Answering your second question first:

You can generate examples by using older versions of CCExtractor to convert to McPoodle's RAW format and then using raw2scc.exe and ccasdi.exe from SCC_TOOLS to create the *.scc and *.ccd files, respectively.

I use CCExtractor 0.69 to generate the RAW files because it's the last version that [both worked for me **AND** outputted only caption data in the RAW file.](https://github.com/CCExtractor/ccextractor/issues/915)

I'll find some more examples to upload over (hopefully) the next few minutes.

**Comment by NilsIrl** [comment]
> I'll find some more examples to upload over (hopefully) the next few minutes.

It should be okay now that you've told me how to do it myself.

**Comment by The-Bart-The** [comment]
https://www.dropbox.com/s/kko531yt37qq5n7/further%20examples.zip?dl=1

**Comment by ValZapod** [comment]
> This is the extended standard: https://www.techstreet.com/standards/cta-608-e-r2014?product_id=1815447

Why you are pointing to those fakers? CTA made all its standards free of charge. Point to https://shop.cta.tech/products/line-21-data-services, please.

**Comment by cfsmp3** [comment]
@ValZapod they used to be non-free (I bought CEA-708 myself). But it's great to see them freely available. Thanks for pointing it out!
