### ISSUE TITLE
[QUESTION] Can't PIP3 INSTALL python modules under OSX High Sierra (Python 3.7)

### ISSUE THREAD

**Issue by RogerVFbr** [CCExtractor/ccextractor#1124]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : current on Github.

**In raising this issue, I confirm the following (please check boxes, eg [X] - and delete unchecked ones):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [X] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X] - and delete unchecked ones):**

- [X] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [X] NO | [ ] YES - *please specify the last known working version*
- What platform did you use? [ ] Windows - [ ] Linux - [X] Mac
- What were the used arguments? `-autoprogram`

Even after installing all required dependencies I still can't install the Python module. I couldn't find anything in the docs stating incompatibility to Python 3. CLI works properly (tested on Google Drive provided TS file). After running "pip3 install ccextractor", last line of the error says...

        print os.getcwd()
               ^
    SyntaxError: invalid syntax

Which seems linked to Python 2.7 printing synthax. Any help would be appreciated, ccextractor is to become part of an important module of our project.

**Comment by cfsmp3** [comment]
This is a python question actually...

Probably replacing that line with
```
print (os.getcwd())
```

Will fix the problem.

@thealphadollar can you take a look at our general Python3 support?

**Comment by thealphadollar** [comment]
Sure, would love to. I'll patch this up soon as well.

**Comment by thealphadollar** [comment]
Hey @RogerVFbr what you are actually installing are the extension modules for CCExtractor available [here](https://github.com/Diptanshu8/CCExtractor-extension-module). @cfsmp3 Are these modules officially supported? If yes, can we bring them under our organisation so that better support can be provided?

**Comment by cfsmp3** [comment]
@thealphadollar I'm unsure of the status of these modules (I don't have high hopes for them to be honest) but I've forked that repo into our org and given you write permissions.

Feel free to take over its maintenance.

**Comment by cfsmp3** [comment]
Closing this since it's not really part of the CCExtractor core. Anyone affected, please open a bug in the python repo.
