### ISSUE TITLE
[BUG] X-TIMESTAMP-MAP formatting error

### ISSUE THREAD

**Issue by tozawa-xumo** [CCExtractor/ccextractor#1125]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : **X.X**
latest stable building GitHub

**In raising this issue, I confirm the following (please check boxes, eg [X] - and delete unchecked ones):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X] - and delete unchecked ones):**

- [ ] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [x] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [x] NO | [ ] YES - *please specify the last known working version*
- What platform did you use? [ ] Windows - [x] Linux - [x] Mac
- What were the used arguments? `-autoprogram`
-in=ts, -out=webvtt
**Video links (replace text below with your links)**
It happens whenever the output is webvtt.

**Additional information**
There is error in the X-TIMESTAMP-MAP.

X-TIMESTAMP-MAP=MPEGTS:65442, LOCAL 00:00:00.000
should be corrected to
X-TIMESTAMP-MAP=MPEGTS:65442,LOCAL:00:00:00.000
(no space before "LOCAL" and a colon needed between "LOCAL" and "00:00:00.000"

It's a simple fix on line 217 of ccx_encoders_webvtt.c

**Comment by prs-prabodh** [comment]
Can I work on this one?

**Comment by tozawa-xumo** [comment]
Sure.  I don’t heave time to make a pull request.  If you could work on it, I would appreciate it.

Thanks
