### ISSUE TITLE
Tickertext skips frames through video

### ISSUE THREAD

**Issue by christina-tzogka** [CCExtractor/ccextractor#1159]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : **X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X] - and delete unchecked ones):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).

- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)

**My familiarity with the project is as follows (check one, eg [X] - and delete unchecked ones):**

- [ ] I have never used CCExtractor.
- [X] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [X] NO | [ ] YES - *please specify the last known working version*
- What platform did you use? [ ] Windows - [X] Linux - [ ] Mac
- What were the used arguments? `**-hardsubx -tickertext -conf_thresh 80 -whiteness_thres 80 -ocrlang grc**'

**Video links (replace text below with your links)**
https://www.youtube.com/watch?v=zDdr5FbW02o

**Additional information**

I am trying to run ccextractor using tesseract trained data for greek ticker-text. 
The main problem is that extracting tickers process starts after the 30th sec of video (i.e 1000th frame) and goes through 1000 batch of frames.
As a result of this, many frames are being skipped...
I would appreciate it if someone could give me an advice about what may go wrong!

**Comment by gauravahlawat81** [comment]
Hey, I was not able to reproduce this error, can you please provide the exact command you ran which gave the mentioned error ?

**Comment by cfsmp3** [comment]
@christina-tzogka feel free to reopen if you are still having problems.
