### ISSUE TITLE
CCExtractor fails to extract srt,webvtt but spupng is ok from the same track

### ISSUE THREAD

**Issue by Murmur** [CCExtractor/ccextractor#1163]
I made a small TS test file  and a text file with detailed debug information. 
http://akini.mbnet.fi/videos/test1_dvbsub.ts
http://akini.mbnet.fi/videos/test1_readme.txt

File has two dvbsub streams (0xc37 works for srt,vtt,png extract. 0xc4f works only for png extract):
```
Stream #0:2[0xc37](fin): Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006)
Stream #0:4[0xc4f](swe): Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006) (hearing impaired)
```

CCExtractor test commands:
```
ccextractor -codec dvbsub -utf8 -nobom -nofc -noteletext -nocodec teletext -nomyth -nots \
  -oem 2 -quant 2 \
  -in=ts "test1_dvbsub.ts" -datapid 0xc37 \
  -out=srt -o test1_c37.srt -delay 0

ccextractor -codec dvbsub -utf8 -nobom -nofc -noteletext -nocodec teletext -nomyth -nots \
  -oem 2 -quant 2 \
  -in=ts "test1_dvbsub.ts" -datapid 0xc4f \
  -out=srt -o test1_c4f.srt -delay 0

ccextractor -codec dvbsub -utf8 -nobom -nofc -noteletext -nocodec teletext -nomyth -nots \
  -oem 2 -quant 2 \
  -in=ts "test1_dvbsub.ts" -datapid 0xc4f \
  -out=spupng -o test1_c4f.xml -delay 0
```

**Results for text extract**
out=srt+webvtt works fine for 0xc37 track but empty on 0xc4f dvbsub track.
out=spupng works fine for both dvbsub tracks.

This means have to use a standalone tesseract command line app to convert png to text file, use python or something script to write the final srt,webvtt text files.

**Comment by mridullpandey** [comment]
hi can i take this up

**Comment by cfsmp3** [comment]
No need to ask - you can work on anything that is open :-)

**Comment by cfsmp3** [comment]
@Murmur that link no longer works, please reopen the issue if you still have problems and can provide a sample
