### ISSUE TITLE
MP4 (from itunes) files not being processed (no subs)

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#1223]
This comes from an email:

```
CCExtractor 0.88, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: D:\Documents\NoteBurner Video Converter\Adam's Rib (1080p HD).mp4
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: Auto] [Debug: No] [Buffer input: Yes]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .srt] [Encoding: Latin-1] [Delay: 0] [Trim lines: No]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]
[Quantisation-mode: CCExtractor's internal function]


-----------------------------------------------------------------

Opening file: D:\Documents\NoteBurner Video Converter\Adam's Rib (1080p HD).mp4
Detected MP4 box with name: ftyp
Detected MP4 box with name: free
Detected MP4 box with name: mdat

File seems to be a MP4

Analyzing data with GPAC (MP4 library)

Analyzing data with GPAC (MP4 library)
Opening 'D:\Documents\NoteBurner Video Converter\Adam's Rib (1080p HD).mp4':

This is where the program hangs and doesn’t finish on all of my MP4 conversions
Running PID various numbers come up each time I try
Status Code: Done, Code = - 1073741819

There is nothing that comes up on the preview screen
And the file output for .srt is 0kb
```

The file is available [here](https://drive.google.com/open?id=19cVFdWwhY9stTNIay6xXepWA5524uuR8).

**Comment by eshandhawan51** [comment]
CCExtractor 0.88, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: /home/eshan/Downloads/Adam's Rib.mp4
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: Auto] [Debug: No] [Buffer input: No]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .srt] [Encoding: UTF-8] [Delay: 0] [Trim lines: No]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No][Filter profanity: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]
[Quantisation-mode: CCExtractor's internal function]

-----------------------------------------------------------------
Opening file: /home/eshan/Downloads/Adam's Rib.mp4
Detected MP4 box with name: ftyp
Detected MP4 box with name: free
Detected MP4 box with name: mdat
File seems to be a MP4
Analyzing data with GPAC (MP4 library)
Opening '/home/eshan/Downloads/Adam's Rib.mp4': [iso file] Unknown box type c608
[iso file] Unknown box type desc
[iso file] Box "data" is invalid in container desc
[iso file] Unknown box type gmhd
[iso file] Unknown box type gmin
[ISO file] dataReferenceIndex set to 0 in sample entry, overriding to 1
[isom] not enough bytes in box text: 36 left, reading 51 (file ../src/thirdparty/gpacmp4/box_code_3gpp.c, line 339)
[iso file] Read Box "text" failed (Invalid IsoMedia File) - skipping
ok
Track 1, type=soun subtype=MPEG
Track 2, type=vide subtype=avc1
Track 3, type=clcp subtype=c608
Track 4, type=text subtype=text
MP4: found 4 tracks: 1 avc and 2 cc
Processing track 1, type=soun subtype=MPEG
Processing track 2, type=vide subtype=avc1
Processing track 3, type=clcp subtype=c608
Processing track 4, type=text subtype=text

Unsupported track type text:text! Please report.
  0%  |  00:00
Unsupported track type text:text! Please report.
  3%  |  00:11
Unsupported track type text:text! Please report.
  6%  |  01:16
Unsupported track type text:text! Please report.
 10%  |  03:37
Unsupported track type text:text! Please report.
 13%  |  05:46
Unsupported track type text:text! Please report.
 16%  |  09:14
Unsupported track type text:text! Please report.
 20%  |  10:31
Unsupported track type text:text! Please report.
 23%  |  16:37
Unsupported track type text:text! Please report.
 26%  |  21:44
Unsupported track type text:text! Please report.
 30%  |  27:25
Unsupported track type text:text! Please report.
 33%  |  31:22
Unsupported track type text:text! Please report.
 36%  |  32:41
Unsupported track type text:text! Please report.
 40%  |  37:18
Unsupported track type text:text! Please report.
 43%  |  42:35
Unsupported track type text:text! Please report.
 46%  |  46:42
Unsupported track type text:text! Please report.
 50%  |  50:34
Unsupported track type text:text! Please report.
 53%  |  53:32
Unsupported track type text:text! Please report.
 56%  |  57:56
Unsupported track type text:text! Please report.
 60%  |  58:56
Unsupported track type text:text! Please report.
 63%  |  62:02
Unsupported track type text:text! Please report.
 66%  |  67:32
Unsupported track type text:text! Please report.
 70%  |  71:39
Unsupported track type text:text! Please report.
 73%  |  72:58
Unsupported track type text:text! Please report.
 76%  |  76:36
Unsupported track type text:text! Please report.
 80%  |  80:23
Unsupported track type text:text! Please report.
 83%  |  84:44
Unsupported track type text:text! Please report.
 86%  |  88:25
Unsupported track type text:text! Please report.
 90%  |  92:56
Unsupported track type text:text! Please report.
 93%  |  96:50
Unsupported track type text:text! Please report.
100%  |  100:28
Closing media: ok
Found 1 AVC track(s). Found 2 CC track(s).


Total frames time:	  00:00:00:000  (0 frames at 29.97fps)

Min PTS:				00:00:00:000
Max PTS:				01:40:28:000
Length:				 01:40:28:000
Done, processing time = 0 seconds
Issues? Open a ticket here
https://github.com/CCExtractor/ccextractor/issues


This is the log generated when I tried the same file. there seems unsupported type problem
and it generated 3 files 
2 of which are empty but adams's rib_2.srt has the subtitles 
[Adam's Rib.zip](https://github.com/CCExtractor/ccextractor/files/4139156/Adam.s.Rib.zip)

**Comment by djlaporte2001** [comment]
Thanks for figuring this out. I downloaded your file above and it worked. I'm using CCextractor GUI 0.88 for Windows and have not been able to replicate your settings above. I'm having issues figuring out what you did to get these three output files:

The only differences that I could find from your log was:
The Buffer Input was set to No (i don't know how you did that)
Encoding was UTF-8 (i figured out how to produce this setting)
Filter Profanity was set to No (i don't see that setting available)

And then further down your log you seem to be processing an "ISO file unknown box type c608"
I'm not sure if I understand how or why the log is working with an ISO file; is that another setting which needs to be changed.

I'm just wondering how and if I can replicate your settings with CCextractor GUI 0.88 for Windows. Are there any instructions or could you provide me with instructions with the settings you choose to produce those three files? I have about 200 other files that I would like to test your settings on to see if will work on those files also.

Thanks.

**Comment by eshandhawan51** [comment]
@djlaporte2001 you can use -nobi or --nobufferinput  to change buffer input to no 
but that's not really  the matter

**Comment by djlaporte2001** [comment]
So what did you do differently in the settings to process the video file and return three files? My default settings using CCExtractor GUI 0.88 for Windows is only producing 1 file with 0kb and the program hangs at the section where it says that it is opening the file?

Are you using the same default settings that I used above or did you change some settings in the tabs below to produce those three files? If so, could you share with me which tabs in the program you accessed and what settings you changed? 

These are the tabs that I see in the program: 
Input files, Input options, Advanced Input Options, Decoders, Output 1, Output 2, Output 3, Credits, Debug, HDHomerun, Burned-in Subtitle Extraction, Execution

I'm just trying to duplicate what you did and unfortunately have no idea how you were able to process that file so easily.

**Comment by eshandhawan51** [comment]
I am seeing to it that the issue gets resolved as soon as possible :)

**Comment by djlaporte2001** [comment]
I'm sorry, I thought you already found a solution because you were able to produce those three files where the second one worked perfectly. I tested it with my video and it worked. I thought I just needed to figure out how you did it. I'll wait and see what your team finds out. Thanks.

**Comment by cfsmp3** [comment]
Seems to work OK with the current version (as in the open we have on
github, which is pre-0.89, not 0.88 even though there's a number of
warnings about "text" not being supported).

**Comment by djlaporte2001** [comment]
And that's using the default settings? Could you send me a link to the version you are using and I will test it and provide feedback?




Get Outlook for Android







On Sun, Feb 2, 2020 at 1:28 AM -0500, "Carlos Fernandez Sanz" <notifications@github.com> wrote:










Seems to work OK with the current version (as in the open we have on


github, which is pre-0.89, not 0.88 even though there's a number of


warnings about "text" not being supported).

**Comment by djlaporte2001** [comment]
And that's using the default settings? Could you send me a link to the version you are using and I will test it and provide feedback?

I can't seem to find a download link for CCextractor pre-0.89 GUI for Windows anywhere.

**Comment by cfsmp3** [comment]
On Sun, Feb 2, 2020 at 6:07 AM djlaporte2001 <notifications@github.com>
wrote:

> And that's using the default settings? Could you send me a link to the
> version you are using and I will test it and provide feedback?
>
> I can't seem to find a download link for CCextractor pre-0.89 GUI for
> Windows anywhere.
>
There's one here:

https://github.com/CCExtractor/ccextractor/issues/1116

Not totally up to date but you can give it a try.

>

**Comment by djlaporte2001** [comment]
I downloaded the file on the link you sent. Gave it a try using the default settings, again still seeing the same issue. Producing only 1 file at 0kb and hanging at the same spot. Unable to produce the three files that "eshandhawan51" did. Would really like to know how he produced what he did but until its figured out I will wait patiently for instructions.

**Comment by djlaporte2001** [comment]
Just an FYI: I tried using an older version of CCextractor 0.85GUI for Windows and it worked flawlessly.

**Comment by cfsmp3** [comment]
Labeling easy since it's seems a regression.

**Comment by djlaporte2001** [comment]
Yeah, I'm not sure why the latest version was having difficulty. I'm sure someone will figure that out. Anyways, your team has a great product, i'm enjoying it immensely.

**Comment by ahmedtds** [comment]
@cfsmp3 re-open my relevant issue please: https://github.com/CCExtractor/ccextractor/issues/1116

I tried all of your new builds and they still crash. I can send sample if you want.

**Comment by ahmedtds** [comment]
@cfsmp3 sorry I'm not hijacking I thought they were relevant because both are occuring on itunes files. I think they are related, why do you think they are not?

**Comment by magauthority** [comment]
I encountered this same issue on Ubuntu 20.04.1 using the apt-get available build (which was 87 I believe) so then I downloaded the .88 source and compiled, and encountered the same issue when trying to extract subtitles from an .mp4 file, although it worked perfectly with the same file only in an .mkv container. Strange. Reverting back to 0.85b worked flawlessly. 

Here's the specific error messages: 

CCExtractor 0.88, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: tempmp4file.mp4
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: Auto] [Debug: No] [Buffer input: No]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .srt] [Encoding: UTF-8] [Delay: 0] [Trim lines: No]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No][Filter profanity: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]
[Quantisation-mode: CCExtractor's internal function]

-----------------------------------------------------------------
Opening file: tempmp4file.mp4
Detected MP4 box with name: ftyp
Detected MP4 box with name: free
Detected MP4 box with name: mdat
File seems to be a MP4
Analyzing data with GPAC (MP4 library)
Opening 'tempmp4file.mp4': [iso file] Unknown box type gmhd
[iso file] Unknown box type gmin
[ISO file] dataReferenceIndex set to 0 in sample entry, overriding to 1
[isom] not enough bytes in box text: 36 left, reading 51 (file ../src/thirdparty/gpacmp4/box_code_3gpp.c, line 339)
[iso file] Read Box "text" failed (Invalid IsoMedia File) - skipping
ok
Track 1, type=vide subtype=avc1
Track 2, type=soun subtype=ac-3
Track 3, type=text subtype=text
MP4: found 3 tracks: 1 avc and 1 cc
Processing track 1, type=vide subtype=avc1
Processing track 2, type=soun subtype=ac-3
Processing track 3, type=text subtype=text

Unsupported track type text:text! Please report.
  0%  |  00:00
Unsupported track type text:text! Please report.
 16%  |  18:54
Unsupported track type text:text! Please report.
 33%  |  30:00
Unsupported track type text:text! Please report.
 50%  |  34:40
Unsupported track type text:text! Please report.
 66%  |  35:27
Unsupported track type text:text! Please report.
100%  |  38:47
Closing media: ok
Found 1 AVC track(s). Found 1 CC track(s).


Total frames time:        00:00:00:000  (0 frames at 29.97fps)

Min PTS:                                00:00:00:000
Max PTS:                                00:38:47:830
Length:                          00:38:47:830
Done, processing time = 0 seconds

No captions were found in input.
Issues? Open a ticket here
https://github.com/CCExtractor/ccextractor/issues


This would result in a srt file with nothing inside it. 

Love your work, thank you so much for this program. It makes a world of difference for my deaf son.

**Comment by LostDingo** [comment]
Hello,

I am new to this program, and am having the same issue with .m4v files from iTunes. When I tried 0.88, it recognized that there was one CC track in the media file but had the "Unsupported Track Type" text appear and delivered an SRT file without anything inside it. I tried 0.85b as suggested above, but it doesn't recognize the presence of any CC tracks in the media file. 

This is what the 0.88 program delivered:

...

Track 1, type=soun subtype=drms
Track 2, type=vide subtype=drmi
Track 3, type=clcp subtype=p608
Track 4, type=soun subtype=drms
MP4: found 4 tracks: 0 avc and 1 cc
Processing track 1, type=soun subtype=drms
Processing track 2, type=vide subtype=drmi
Processing track 3, type=clcp subtype=p608

Unsupported track type clcp:p608! Please report.

...[many of the above "Unsupported track type..." message repeated]...

Processing track 4, type=soun subtype=drms

Closing media: ok
Found no AVC track(s). Found 1 CC track(s).


Total frames time:	  00:00:00:000  (0 frames at 29.97fps)

Min PTS:				00:00:00:000
Max PTS:				00:42:19:770
Length:				 00:42:19:770

Done, processing time = 54 seconds

No captions were found in input.


Any assistance would be much appreciated, if possible! Please and thank you!

**Comment by cfsmp3** [comment]
Closing, just tested and it works.
