### ISSUE TITLE
[BUG] BROKEN ASF SAMPLE.(SHOWS  INCOREECT FORMATTING IN GENERATED SRT FILE).

### ISSUE THREAD

**Issue by pavanjoshi914** [CCExtractor/ccextractor#1227]
CCExtractor version 0.88

In raising this issue, I confirm the following:

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [X] I have used the latest available version of CCExtractor to verify this issue exists.

My familiarity with the project is as follows:

- [X] I have used CCExtractor just a couple of times.

Necessary information:
- What platform did you use? [ ] Windows - [X] Linux - [ ] Mac
- What were the used arguments? `-in=asf`

VIDEO LINK:https://sampleplatform.ccextractor.org/sample/download/123
 

OUTPUT FILE:https://drive.google.com/open?id=1vO4OkROyzJ7UmfZENWJAI6MSMg0ZGeXl

OUTPUT REQUIRED:https://sampleplatform.ccextractor.org/regression/test/335/download

Warnings of invalid color code index selected was encountered:

`WARNING:get_decoder_line_encoded:Invalid Color index Selected 151587081
WARNING:get_decoder_line_encoded:Invalid Color index Selected 151587081
WARNING:get_decoder_line_encoded:Invalid Color index Selected 151587081
WARNING:get_decoder_line_encoded:Invalid Color index Selected 151587081
`

**Comment by pavanjoshi914** [comment]
someone who wants to fix it out can figure out these lines of code which are creating warnings in asf check:

https://github.com/CCExtractor/ccextractor/blob/6697ed34967343830178f8452e276ab0d94f08e0/src/lib_ccx/ccx_encoders_helpers.c#L286-L317

**Comment by cfsmp3** [comment]
Seems like a regression so fixing it is a matter of spending some time looking for the responsibly commit.

**Comment by pavanjoshi914** [comment]
@cfsmp3 i am already working on it soon i will genereate a PR..:smile:

**Comment by cfsmp3** [comment]
@NilsIrl did your last PR fix this as well? I assume so but want to confirm before closing.

**Comment by NilsIrl** [comment]
> @NilsIrl did your last PR fix this as well? I assume so but want to confirm before closing.

Yes it seems fine for me.
