### ISSUE TITLE
Some closed captioning does not work properly

### ISSUE THREAD

**Issue by elliotd123** [CCExtractor/ccextractor#124]
I emailed a file to you as well (espn.ts). We’ve found some transport streams that the CC ends up jumbled. It’s the same with VLC or FFMpeg-based software, but our IP set-top boxes display the CC just fine. They use software made by bitrouter: http://www.bitrouter.com/products/capstack.htm

**Comment by mailumangjain** [comment]
Hi there !
Can you just upload the sample at an shared location once more, please.
Thank you.

**Comment by anshul1912** [comment]
@mailumangjain Carlos has uploaded sample file in issue #136

**Comment by mailumangjain** [comment]
Yes, but those are TiVo mpg samples, I just wanted another sample of another format(.ts) to look more into it.

**Comment by anshul1912** [comment]
@mailumangjain  I missed that part, u r right
@elliotd123 we need that sample file

**Comment by cfsmp3** [comment]
I'm emailed elliotd123 in case he doesn't pay attention to github notifications, if he replies I'll make sure everyone has access to the file.

**Comment by cfsmp3** [comment]
Elliot sent me the broken file again - he still had it around.
I've uploaded it to the sample repository (directory /Elliot-ESPN). 
For developers without access, you can use this link to download it (the link will expire in a few days though):

https://www.transferbigfiles.com/fdf5f43c-7efb-4445-9185-57f659f2dc95/JWShG0-xXzwbtjVqNX82uA2

**Comment by cfsmp3** [comment]
Output is correct in current git version (don't know when it was fixed though).
