### ISSUE TITLE
[PROPOSAL] When converting roll-up captions using "don't duplicate lines…", add an option to start a new caption when the speaker changes.

### ISSUE THREAD

**Issue by The-Bart-The** [CCExtractor/ccextractor#1240]
CCExtractor version: this would affect versions after 0.88

# Necessary information

- Is this a regression (i.e. did it work before)? NO
- What platform did you use?  Windows
- What were the used arguments? --norollup

Basically the title. 

Simple (?): Look for signs the speaker has changed; like ">" or ">>>" or "Narrator:" or "Oprah:" any of which preceded by a new line, and start the next caption there.

Less Simple: Check if the captions are probably synchronized, and if so, also start a caption after a long pause at the end of a sentence. (Maybe detect uneven timing of characters, as if typed by a stenographer to distinguish live captioning from scripted.  Scripted roll-up captions have accurate timing and are sometimes used in news magazine programs and weekly documentary series like Frontline.)

Thanks again, everyone, for all your hard work.

**Comment by cfsmp3** [comment]
That's probably best done by a post-processing program to be honest. There's no need to add those kind of features directly into the main program.

After all, C is not really a convenient language for string manipulation.

However in Python that would take just a few lines of code.

**Comment by cfsmp3** [comment]
Closing because: won't-fix (just feel like CCExtractor itself is not the right place).
