### ISSUE TITLE
OCR mp4 hardsub problem.

### ISSUE THREAD

**Issue by artivision** [CCExtractor/ccextractor#1249]
Good day, cannot OCR mp4 hardsub, also need EL not ENG:

HardsubX (Hard Subtitle Extractor) - Burned-in subtitle extraction subsystem
eng.traineddata not found! No Switching Possible

**Comment by cfsmp3** [comment]
This is not a bug. You're just missing files.

**Comment by artivision** [comment]
Sir i have from AUR CCExtractor, Tesseract and Tesseract-data-ell. The problem is that google doesn't find any relevant results of an example command line that i choose language. Can you post one please?

**Comment by MackeyStingray** [comment]
You just need `-ocrlang ell`
