### ISSUE TITLE
[BUG] 0.88 crash on Windows

### ISSUE THREAD

**Issue by ahmedtds** [CCExtractor/ccextractor#1252]
CCExtractor version: **0.88**

# In raising this issue, I confirm the following:

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.
- [x] I have ticked all the boxes in this section and to prove it I'm deleting the section completely to remove boilerplate text.

# Necessary information

- Is this a regression (i.e. did it work before)? **YES** - 0.85 works without an issue
- What platform did you use? **Window 7 32-bit**
- What were the used arguments? `ccextractorwin.exe --gui_mode_reports -out=srt -bom -utf8 --nofontcolor -trim file.m4v`

# Video links

Can provide privately, it's a movie from iTunes, can't post publicly.

# Additional information

```
CCExtractor 0.88, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: C:\itunes\movie.m4v
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: Auto] [Debug: No] [Buffer input: Yes]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .srt] [Encoding: UTF-8] [Delay: 0] [Trim lines: Yes]
[Add font color data: No] [Add font typesetting: Yes]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]
[Quantisation-mode: CCExtractor's internal function]


-----------------------------------------------------------------

Opening file: C:\itunes\movie.m4v
Detected MP4 box with name: ftyp
Detected MP4 box with name: moov

File seems to be a MP4

Analyzing data with GPAC (MP4 library)
Opening 'C:\itunes\movie.m4v': 
```

and then crash

**Comment by ahmedtds** [comment]
All 4 binaries here gives same result as well: https://github.com/CCExtractor/ccextractor/files/3935480/CCExtractor_release_binary_test.zip

This bug might have relevance to this issue: https://github.com/CCExtractor/ccextractor/issues/1223

**Comment by cfsmp3** [comment]
Closing because there's no sample.

**Comment by ahmedtds** [comment]
@cfsmp3 Why are you so rude and what is this hostility? I said I can provide it.

**Comment by ahmedtds** [comment]
"If it is not possible to make it available publicly, send us a private invitation (both Dropbox and Google Drive allow that). In this case we will download the file and upload it to the private developer repository."

That's in your issue template but it doesn't say where to send it.

**Comment by ahmedtds** [comment]
I'm now contacting CCExtractor via other means about your abusive behaviour.

**Comment by canihavesomecoffee** [comment]
@ahmedtds You can either:
- join us on Slack (refer to https://ccextractor.org/public:general:support for how to do that) and then send it in a DM to Carlos there
- send carlos an email (refer to page above) with the link to the sample
- upload the sample to the sample platform (again, refer tot he page above)

**Comment by cfsmp3** [comment]
> @cfsmp3 Why are you so rude and what is this hostility?

I'm trying to keep our issue list clean (for a change) with only issues we can actually do something about, that's all. Not trying to be rude. Sorry it it came out that way.

About the sample, yes what @canihavesomecoffee said. If public is not an option send us a link privately (I believe the email still appears when you run the program) and we'll transfer it to our private repo.

**Comment by ahmedtds** [comment]
@cfsmp3 ok sorry for overracting, thanks for re-opening

I sent sample link to your email, sorry it took a while to upload, file was big.

**Comment by xvkdev** [comment]
I made a copy of the file - anyone wanting to work on this ping me on slack for a link to the file.

**Comment by cfsmp3** [comment]
I made a copy of the file - anyone wanting to work on this ping me on slack for a link to the file.

**Comment by NilsIrl** [comment]
> and then crash

What do you mean by "crash". On my side, it doesn't crash although there are many warning and error messages.

**Comment by cfsmp3** [comment]
I suspect this is a Windows only issue. @canihavesomecoffee can you try this in the SP? We'd need to test it in a clean Windows install. Most likely mine has too many things to be reliable.

**Comment by ryanchild** [comment]
I see the same output as posted in the reporter's "Additional Information" when opening an mp4 with the 0.88 gui in windows 10 home and the .srt file is 0 bytes.  No segfault.

If I copy the command line and run it in power shell, I get:
```
Analyzing data with GPAC (MP4 library)
###INPUTFILECLOSED
Opening '.\Star Trek - Enterprise - ''Carpenter Street'' (Recorded Jul 08, 2020, KTVDDT2) (TS) (^162_0) (02).mp4': [iso file] Unknown box type gmhd
[iso file] Unknown box type gmin
[ISO file] dataReferenceIndex set to 0 in sample entry, overriding to 1
```

I don't see previous versions on the download page but I happen to have a copy of 0.79 and it works fine.  Let me know if I can help by providing my input file.

**Comment by cfsmp3** [comment]
@ahmedtds @ryanchild I'm closing this since a fix was merged (and we also updated GPAC).
Please feel free to reopen if you still experience problems with the current master.
