### ISSUE TITLE
[BUG] CCExtractor crashes with error "Error: Broken AVC stream - forbidden_zero_bit not zero"

### ISSUE THREAD

**Issue by MaximVol** [CCExtractor/ccextractor#1266]
CCExtractor version: 0.87

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [X] I have used the latest available version of CCExtractor to verify this issue exists.

# Necessary information

- Is this a regression (i.e. did it work before)? NO
- What platform did you use? Window and Linux
- What were the used arguments? `ccextractorwin.exe cctest.ts`

# Video links

http://exchange.grabien.com/cctest.ts

(The file is big enough, 2.5 GB.)

# Additional information

CCExtractor crashes with "Error: Broken AVC stream - forbidden_zero_bit not zero" error message. The full log is below:

CCExtractor 0.87, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
Input: cctest.ts
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: Auto] [Debug: No] [Buffer input: Yes]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .srt] [Encoding: UTF-8] [Delay: 0] [Trim lines: No]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]
[Quantisation-mode: CCExtractor's internal function]
Opening file: cctest.ts
File seems to be a transport stream, enabling TS mode
Analyzing data in general mode
Found large gap(86) in PTS! Trying to recover ...
  0%  |  00:00
Found large gap(94) in PTS! Trying to recover ...
Found large gap(88) in PTS! Trying to recover ...
Found large gap(90) in PTS! Trying to recover ...
Found large gap(92) in PTS! Trying to recover ...
 42%  |  25:0500000000 | 00 00 00 01 E1 E0 76 F1 A4 00                    |     срvёд
Error: Broken AVC stream - forbidden_zero_bit not zero ...
Issues? Open a ticket here
https://github.com/CCExtractor/ccextractor/issues

**Comment by manybuddies** [comment]
CCExtractor version: 0.88

**Necessary Information**
Is this a regression (i.e. did it work before)? no
What platform did you use? Windows
What were the used arguments?
ccextractorwinfull  "Born.Again.E05-E06.200427.1080i.IPTV.H264-WiND.ts" --service 1[EUC-KR]

**Video Link:**
https://drive.google.com/file/d/1Cwhqfv2RVDvyHCkZzCy5TGCzVKyl9vX4/view?usp=sharing

**Error Log**
Extracting closed caption from "Born.Again.E05-E06.200427.1080i.IPTV.H264-WiND.ts"...
CCExtractor 0.88, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: Born.Again.E05-E06.200427.1080i.IPTV.H264-WiND.ts
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[CEA-708: 1 decoders active]
[CEA-708: using charset "EUC-KR" for service 1]
[Timing mode: Auto] [Debug: No] [Buffer input: Yes]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .srt] [Encoding: UTF-8] [Delay: 0] [Trim lines: No]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]
[Quantisation-mode: CCExtractor's internal function]

-----------------------------------------------------------------
Opening file: Born.Again.E05-E06.200427.1080i.IPTV.H264-WiND.ts
File seems to be a transport stream, enabling TS mode
Analyzing data in general mode
 60%  |  37:1200000000 | 7C 49 5E 01 AF 18 49 12 76 C1                    | |I^ ¯ I vÁ
Error: Broken AVC stream - forbidden_zero_bit not zero ...

**Comment by cfsmp3** [comment]
@MaximVol @manybuddies None of those links work. Feel free to reopen if you still have issues with the current master and can provide fresh download links.
