### ISSUE TITLE
BUG : Error: Broken AVC stream

### ISSUE THREAD

**Issue by TahaRsystem** [CCExtractor/ccextractor#1281]
I am using ccextractor version: 0.88 on linux ubuntu 18.04.

I am sending udp stream to ccextractor from ffmpeg with command:
ffmpeg -re -i HE-AAC-V1.ts -map i:0x3e8 -map i:0x44c -c copy -f mpegts udp://127.0.0.1:1235

I am receiving udp stream as input to ccextractor and taking dump from it as output.srt :
./ccextractor -in=ts  -udp 127.0.0.1:1235 -o output.srt

but after few seconds of running i get error in ccextractor: 
Found large gap(153) in PTS! Trying to recover ...
TS continuity counter not incremented prev/curr 2/11
00000000 | 17 00 00 01 E0 00 00 80 80 05                    |     �  ��       
Error: Broken AVC stream - forbidden_zero_bit not zero ...

But when i run ccextractor with same input file directly then it is working fine:
./ccextractor -in=ts -quiet HE-AAC-V1.ts -o output.srt

What i was looking is to take udp stream as input in ccextractor and dump caption in pipe(fifo file).

**Comment by cfsmp3** [comment]
Have you tried writing the output of ffmpeg to a file and then feeding that file to CCExtractor?
This doesn't seem like a CCExtractor problem.

**Comment by arlovande** [comment]
I'm having the same problem for an RTMP stream I'm converting to UDP.  Don't know how to feed it to a file and not have the file get huge, though.

**Comment by cfsmp3** [comment]
The file is going to be huge if the stream is huge.
I'm going to close this ticket because the OP hasn't replied and this just seems like a network problem, not a CCExtractor problem.
