### ISSUE TITLE
Build pipelines can use updated versions

### ISSUE THREAD

**Issue by canihavesomecoffee** [CCExtractor/ccextractor#1284]
CCExtractor version: N/A

# In raising this issue, I confirm the following:

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.
- [x] I have ticked all the boxes in this section and to prove it I'm deleting the section completely to remove boilerplate text.

# Necessary information

- Is this a regression (i.e. did it work before)? NO
- What platform did you use? GitHub Actions
- What were the used arguments? `N/A`

# Video links

N/A

# Additional information

Our build pipelines for both Windows & Linux use some outdated GitHub actions. We should update them from v1 to v2 where applicable.

Especially for the upload artifact steps on Windows I think we can cut out a bunch of steps as it's now possible to upload multiple files to one artifact, use wildcards and so on.

**Comment by kvshravan** [comment]
Hello there, I wanna contribute to CCExtractor and I think it'd be better to start with this easy one.

**Comment by kvshravan** [comment]
@canihavesomecoffee  I have sent a PR , please check into it!
