### ISSUE TITLE
[BUG] Errors while compiling - implicit declaration of function 'write_wrapped'

### ISSUE THREAD

**Issue by subodhk01** [CCExtractor/ccextractor#1296]
CCExtractor version: Build failed ( last commit on master was: commit b1c22e503412f455d3740d0ce5fe9cabc66fe701 )

# In raising this issue, I confirm the following:

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.
- [x] I have ticked all the boxes in this section and to prove it I'm deleting the section completely to remove boilerplate text.

# Necessary information

- Is this a regression (i.e. did it work before)? NO
- What platform did you use? Mac
- What were the used arguments? make

# Additional information

Errors generated when compiling. [ Followed the procedure from https://github.com/CCExtractor/ccextractor/blob/master/docs/COMPILATION.MD ]

<img width="1107" alt="Screenshot 2021-02-08 at 14 55 27" src="https://user-images.githubusercontent.com/19875783/107200422-b056b380-6a1d-11eb-8472-9beb16d5f5d7.png">

**Comment by NilsIrl** [comment]
Which build system was used?

**Comment by subodhk01** [comment]
Sorry I don't understand
