### ISSUE TITLE
BUG - Colombian (DVB) subtitles not extracted

### ISSUE THREAD

**Issue by canihavesomecoffee** [CCExtractor/ccextractor#1301]
CCExtractor version: 0.85-0.88 & master

# Necessary information

- Is this a regression (i.e. did it work before)? No
- What platform did you use? Linux
- What were the used arguments? `-autoprogram` (originally as a stream, but mp4's from that stream don't work either)

# Video links

- https://sampleplatform.ccextractor.org/sample/163
- https://sampleplatform.ccextractor.org/sample/164
- https://sampleplatform.ccextractor.org/sample/165
- https://sampleplatform.ccextractor.org/sample/166
- https://sampleplatform.ccextractor.org/sample/167
- https://sampleplatform.ccextractor.org/sample/168

# Additional information

Reported on Slack. Streaming of Columbian TV is not yielding subtitles. Should be DVB (Spanish). VLC plays them correctly.
In case of questions, direct them to @fernaper.

**Comment by fernaper** [comment]
Can this issue be prioritized? We have no problem paying if necessary.
Is there any planning date to resolve this issue?
If not, is there any alternative to extract the subtitles?

Sorry to put pressure on you, but we are in a bit of a hurry.
Thank you for your hard work!
