### ISSUE TITLE
[QUESTION] How do I get CCExtractor to batch process my TS files?

### ISSUE THREAD

**Issue by Ronstang** [CCExtractor/ccextractor#1302]
I just started using CCExtractor GUI 0.88 manually as MCEBuddy has been using it for me for quite some time in the background but the look of the subs is horrible compared to the file I ran manually the other day out of need.

It is probably a user error but I wanted to test running multiple files through CCExtractor so I added several to the "input window" dragging and dropping as the GUI says.  But when I hit the execute button the first TS file was processed and a SRT file was produced, then it said it was analyzing the next file but just hung there and nothing happened.  When I deleted the first file from the queue and then hit execute again the second file processed and produced an SRT file once again...so I know there is nothing wrong with the TS file but CCExtractor would not process it automatically.

I don't know if I'm doing something wrong  or not so any advice would be greatly appreciated as I prefer the output of CCExtractor when I choose the settings so I would like to run all my TS files through in batches before I use ffmpeg to encode them to HEVC which destroys the CCs in the process.

Thank You

**Comment by cfsmp3** [comment]
Closing as this was solved by email
