### ISSUE TITLE
Seek logic using chapters in ifo/bup

### ISSUE THREAD

**Issue by anshul1912** [CCExtractor/ccextractor#131]
when startat is passed seeking should be done usinf ifo/bup files in DVD

**Comment by cfsmp3** [comment]
Assigned to bigharshrag since he's doing the DVD stuff now

**Comment by cfsmp3** [comment]
GSoC: This issue gives 4 points.

**Comment by cfsmp3** [comment]
I'm closing this, it's been around forever and honestly, I don't think anyone cares about IFO anymore.
