### ISSUE TITLE
[PROPOSAL] Make GUI window resizable

### ISSUE THREAD

**Issue by DocJellyBean** [CCExtractor/ccextractor#1318]
It would be nice if the GUI window could be resizable. At the moment one loads the input files, and have to scroll all the way to the end to start the process.

If that is not possible, perhaps place the Start button in the main app window.

**Comment by cfsmp3** [comment]
The GUI is going to be completely rewritten during GSoC.
Closing this issue because well, nothing about the old GUI is important :-)
But if you use it frequently you might want to come talk to us in slack and give ideas for the new GUI. There's already some prototypes @DocJellyBean
