### ISSUE TITLE
[BUG] Timestamps occasionally zero out

### ISSUE THREAD

**Issue by slifty** [CCExtractor/ccextractor#1327]
CCExtractor version: 0.88

# In raising this issue, I confirm the following:

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.
- [x] I have ticked all the boxes in this section and to prove it I'm deleting the section completely to remove boilerplate text.

# Necessary information

- Is this a regression (i.e. did it work before)? UNKNOWN
- What platform did you use? MAC
- What were the used arguments? `-stdout --stream -out=txt -dru -ru1 -customtxt 1100100 -`

# Video links

https://archive.org/details/ccextractor-zerobug

# Additional information

I'm pretty regularly getting output lines with `00:00:00,000|00:00:00,000` timestamps (in the midst of accurate position timestamps).  I can detect these moments in my script but it seems like it might be a ccextractor bug.

```
00:00:01,868|00:00:01,884|TH
00:00:01,884|00:00:01,900|THIN
00:00:01,868|00:00:01,935|THINGS
00:00:01,868|00:00:01,968|THINGS,
00:00:01,868|00:00:02,002|THINGS, A
00:00:01,868|00:00:02,035|THINGS, A FI
00:00:01,868|00:00:02,068|THINGS, A FIRE
00:00:01,868|00:00:02,102|THINGS, A FIRE,
00:00:01,868|00:00:02,135|THINGS, A FIRE, A
00:00:01,868|00:00:02,168|THINGS, A FIRE, A GA
00:00:01,868|00:00:02,202|THINGS, A FIRE, A GAS
00:00:01,868|00:00:02,235|THINGS, A FIRE, A GAS LE
00:00:01,868|00:00:02,268|THINGS, A FIRE, A GAS LEAK
00:00:01,868|00:00:02,302|THINGS, A FIRE, A GAS LEAK O
00:00:01,868|00:00:02,335|THINGS, A FIRE, A GAS LEAK OR
00:00:01,868|00:00:02,402|THINGS, A FIRE, A GAS LEAK OR
00:00:00,000|00:00:00,000|A
00:00:02,469|00:00:02,502|A GE
00:00:02,469|00:00:02,535|A GEND
00:00:02,469|00:00:02,569|A GENDER
00:00:02,469|00:00:02,602|A GENDER R
00:00:02,469|00:00:02,635|A GENDER REV
00:00:02,469|00:00:02,669|A GENDER REVEA
00:00:02,469|00:00:02,702|A GENDER REVEAL
00:00:02,469|00:00:02,736|A GENDER REVEAL GO
00:00:02,469|00:00:02,769|A GENDER REVEAL GONE
00:00:02,469|00:00:02,802|A GENDER REVEAL GONE W
00:00:02,469|00:00:02,836|A GENDER REVEAL GONE WRO
00:00:02,469|00:00:02,869|A GENDER REVEAL GONE WRONG
00:00:02,469|00:00:06,406|A GENDER REVEAL GONE WRONG
00:00:00,000|00:00:00,000|YE
00:00:06,473|00:00:06,506|YEAH
00:00:06,473|00:00:06,539|YEAH,
00:00:06,473|00:00:06,573|YEAH, TH
00:00:06,473|00:00:06,606|YEAH, THAT
00:00:06,473|00:00:06,639|YEAH, THAT'S
00:00:06,473|00:00:06,673|YEAH, THAT'S -
00:00:06,473|00:00:07,407|YEAH, THAT'S -
00:00:00,000|00:00:00,000|[
00:00:07,474|00:00:07,507|[ AP
00:00:07,474|00:00:07,540|[ APPL
00:00:07,474|00:00:07,574|[ APPLAU
00:00:07,474|00:00:07,607|[ APPLAUSE
00:00:07,474|00:00:07,640|[ APPLAUSE ]
00:00:07,474|00:00:08,541|[ APPLAUSE ]
00:00:08,608|00:00:08,624|TO
00:00:08,624|00:00:08,640|TOO
00:00:08,608|00:00:08,675|TOO RE
00:00:08,608|00:00:08,708|TOO REAL
```

**Comment by PunitLodha** [comment]
@slifty File is missing. Can you reupload it?

**Comment by slifty** [comment]
Oh nuts I didn't realize those timed out.  I'll generate another one and upload it to the internet archive.

**Comment by canihavesomecoffee** [comment]
@slifty I'll add it to the sample platform too, that's a guarantee it'll stay online for as long as our org exists :)

**Comment by canihavesomecoffee** [comment]
This also happens when just passing the file to CCExtractor (omitting the `stream`parameter) on Linux. So it's not MacOS specific.

**Comment by cfsmp3** [comment]
@PunitLodha see link above :-)
