### ISSUE TITLE
[BUG] 0.88 is crashing and not detecting OP-47 on a belgian MXF file (track Text / ID : 5-888)

### ISSUE THREAD

**Issue by miambe** [CCExtractor/ccextractor#1336]
# In raising this issue, I confirm the following:

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.
- [x] I have ticked all the boxes in this section and to prove it I'm deleting the section completely to remove boilerplate text.

# Necessary information

- Is this a regression (i.e. did it work before)? NO
- What platform did you use? Windows
- What were the used arguments? -in=mxf -datastreamtype Text -out=srt -bom -latin1 

# Video links

* https://sampleplatform.ccextractor.org/sample/169

# Additional information

I'm working for a local belgian television in the French speaking part of the country. We must use OP-47 files with subtitles on page 888 to get it working with the television providers.

ccextractorwin.exe is crashing when I try to submit any MXF file with a Text track
ID: 5-888:
Format: Teletext Subtitle
MuxingMode: Ancillary data / OP-47 / SDP

**Comment by canihavesomecoffee** [comment]
Can confirm this sample crashes on Linux:

```
#0  0x00007ffff77c6cf0 in __memcmp_avx2_movbe () from /usr/lib/libc.so.6
#1  0x00005555555b0948 in read_packet (demux=0x7ffff632a010, data=0x555555993c10) at ../src/lib_ccx/ccx_demuxer_mxf.c:549
#2  0x00005555555b0b05 in ccx_mxf_getmoredata (ctx=0x5555559934a0, ppdata=0x7fffffffd338) at ../src/lib_ccx/ccx_demuxer_mxf.c:600
#3  0x00005555555f4acb in general_loop (ctx=0x5555559934a0) at ../src/lib_ccx/general_loop.c:888
#4  0x000055555558d254 in api_start (api_options=...) at ../src/ccextractor.c:204
#5  0x000055555558dfbf in main (argc=0x8, argv=0x7fffffffddb8) at ../src/ccextractor.c:463
```
