### ISSUE TITLE
Specifying a given timeformat for output

### ISSUE THREAD

**Issue by shubham162019** [CCExtractor/ccextractor#1339]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

To get the version of CCExtractor, you can use `--version`.

Please check all that apply and **remove the ones that do not**.

In the necessary information section, if this is a regression (something that used to work does not work anymore), make sure to specify the last known working version.

Only specify the minimum number of arguments needed to reproduce the issue.

In the additional information section, describe your problem.

Please make the affected input file available for us (no screenshots, those don't help!). Public links to Dropbox, Google Drive, etc, are all fine. If it is not possible to make it available publicly, send us a private invitation (both Dropbox and Google Drive allow that). In this case we will download the file and upload it to the private developer repository. Methods to send the private invitation to us can be found [here](https://ccextractor.org/public:general:support#email).

Do **not** upload your file to any location that will require us to sign up or endure a wait list, slow downloads, etc. If your upload expires make sure you keep it active somehow (replace links if needed). Keep in mind that while we go over all tickets some may take a few days, and it's important we have the file available when we actually need it.

Make sure to enable notifications in GitHub so you get notifications about your ticket. We may need to ask questions and we do everything inside GitHub's system.

Once you have read all of the instructions **delete all the text from here to the top**.

CCExtractor version: {replace with the version}

# In raising this issue, I confirm the following:

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.
- [x] I have ticked all the boxes in this section and to prove it I'm deleting the section completely to remove boilerplate text.

# Necessary information

- Is this a regression (i.e. did it work before)? NO
- What platform did you use? Linux
- What were the used arguments? ./ccextractor -df -out=smptett -utf8 "Sample_Video_CC.mxf" -o out.xml

# Video links

* {Replace with a link to a video file}

# Additional information

Is There a way to specify the output time format , for eg:- HH:MM:SS:FF (Hours:Minutes:Seconds:Frames) instead of HH:MM:SS.MS (Hours:Minutes:Seconds.Milliseconds)?

**Comment by cfsmp3** [comment]
No.
