### ISSUE TITLE
PROPOSAL: make it possible to build GUI with cmake

### ISSUE THREAD

**Issue by Artturin** [CCExtractor/ccextractor#1366]
Currently it is not possible

**Comment by canihavesomecoffee** [comment]
Which GUI do you refer to?

https://github.com/CCExtractor/ccextractorfluttergui?

**Comment by Artturin** [comment]
> Which GUI do you refer to?
> 
> https://github.com/CCExtractor/ccextractorfluttergui?

https://github.com/CCExtractor/ccextractor/blob/0bbdfc13eee68b39ed2196c05d87b87dd
https://github.com/CCExtractor/ccextractor/tree/master/src/GUI7a3eefc/linux/Makefile.am#L384

If that's going to be deprecated then I can package the fluttering instead

**Comment by canihavesomecoffee** [comment]
The one you link to is indeed planned to be replaced in favour of the flutter one.

We have multiple ones (a C# one, the one you linked, another one somewhere else) and @Techno-Disaster is creating the Flutter one to have a cross-platform, decent GUI.
