### ISSUE TITLE
Missed dll

### ISSUE THREAD

**Issue by Slava46** [CCExtractor/ccextractor#1367]
For new version 0.91 wrote that missed url_launcher_windows_plugin.dll for windows .msi version.
For 0.90 all fine starting.

**Comment by canihavesomecoffee** [comment]
It's an issue we're aware of.

Workaround is to download the windows.zip release for the GUI from here: https://github.com/CCExtractor/ccextractorfluttergui/releases/tag/v0.2.0

And then extract the DLL to your folder where CCExtractor was installed.

We'll fix it in the 0.92 release.

**Comment by Techno-Disaster** [comment]
@Slava46 were you able to install the GUI? Do let me know if there's any further issue or you need help with anything else :D

Any suggestions/feat requests are also welcome :D
