### ISSUE TITLE
[PROPOSAL] fresh GUI installation says 'url_launcher_windows_plugin.dll needed'

### ISSUE THREAD

**Issue by anemochore** [CCExtractor/ccextractor#1369]
I downloaded and installed v0.91 installer and it won't even launch. Please check and include your dependencies before release. :(

**Comment by canihavesomecoffee** [comment]
Duplicate of #1367.

See a temporary workaround until 0.92 is released.

**Comment by Techno-Disaster** [comment]
@anemochore were you able to install the GUI? Do let me know if there's any further issue or you need help with anything else :D

Any suggestions/feat requests are also welcome :D
