### ISSUE TITLE
Extract chinese hardsubs?

### ISSUE THREAD

**Issue by lumibliss** [CCExtractor/ccextractor#1379]
Hello,
I managed with the windows gui software to extract english subs to .srt
But for chinese it doesnt work..
Is it possible to make it work?
on DVB lang its chs
and OCR LANG its chi_tra..
But when I run it, it says no caption found (EXT_NO CAPTIONONS) or something like that. what am i doing wrong?

**Comment by canihavesomecoffee** [comment]
This seems related to https://github.com/CCExtractor/ccextractor/issues/224 (possibly duplicate).

@cfsmp3 Thoughts?

**Comment by cfsmp3** [comment]
> This seems related to #224 (possibly duplicate).
> 
> @cfsmp3 Thoughts?

Maybe, but who knows :-)
We need a Chinese developer to help here.

**Comment by cfsmp3** [comment]
Linking to this ticket: https://github.com/CCExtractor/ccextractor/issues/224
