### ISSUE TITLE
Where is 708 decoder in V0.93?

### ISSUE THREAD

**Issue by taozi1996** [CCExtractor/ccextractor#1380]
![屏幕截图 2021-09-23 110847](https://user-images.githubusercontent.com/31797996/134450188-a9e7ebf6-15da-4ac7-a9b0-0fabb58bc3dd.png)
![屏幕截图 2021-09-23 111030](https://user-images.githubusercontent.com/31797996/134450190-c5425050-ab40-4e85-ba7c-0b1300e386be.png)

**Comment by cfsmp3** [comment]
@Techno-Disaster

**Comment by Techno-Disaster** [comment]
> @Techno-Disaster

https://github.com/CCExtractor/ccextractorfluttergui/commit/0a283202ffb6c39434ad1fa42057eaee4029c03a done, should be up in the next release

**Comment by Techno-Disaster** [comment]
> > @Techno-Disaster
> 
> [CCExtractor/ccextractorfluttergui@0a28320](https://github.com/CCExtractor/ccextractorfluttergui/commit/0a283202ffb6c39434ad1fa42057eaee4029c03a) done, should be up in the next release

By the way @taozi1996  your settings will get reset automatically with the default ones if you install the new version. you can probably manually backup it though

**Comment by taozi1996** [comment]
> > > @Techno-Disaster
> > 
> > 
> > [CCExtractor/ccextractorfluttergui@0a28320](https://github.com/CCExtractor/ccextractorfluttergui/commit/0a283202ffb6c39434ad1fa42057eaee4029c03a) done, should be up in the next release
> 
> By the way @taozi1996 your settings will get reset automatically with the default ones if you install the new version. you can probably manually backup it though

Thanks.But the option "enable 708 decoder" is missing,I can't use it yet
![屏幕截图 2021-09-30 082506](https://user-images.githubusercontent.com/31797996/135366205-14d45560-7ab8-4ae7-883a-8b7b9dcf7859.png)
.

**Comment by Techno-Disaster** [comment]
> > > > @Techno-Disaster
> > > 
> > > 
> > > [CCExtractor/ccextractorfluttergui@0a28320](https://github.com/CCExtractor/ccextractorfluttergui/commit/0a283202ffb6c39434ad1fa42057eaee4029c03a) done, should be up in the next release
> > 
> > 
> > By the way @taozi1996 your settings will get reset automatically with the default ones if you install the new version. you can probably manually backup it though
> 
> Thanks.But the option "enable 708 decoder" is missing,I can't use it yet ![屏幕截图 2021-09-30 082506](https://user-images.githubusercontent.com/31797996/135366205-14d45560-7ab8-4ae7-883a-8b7b9dcf7859.png) .

@taozi1996 not sure why you need a enable switch explicitly? When the user enters the service number it's enabled anyway, and that's how it's shown in the current command box.

**Comment by taozi1996** [comment]
> > > > > @Techno-Disaster
> > > > 
> > > > 
> > > > [CCExtractor/ccextractorfluttergui@0a28320](https://github.com/CCExtractor/ccextractorfluttergui/commit/0a283202ffb6c39434ad1fa42057eaee4029c03a) done, should be up in the next release
> > > 
> > > 
> > > By the way @taozi1996 your settings will get reset automatically with the default ones if you install the new version. you can probably manually backup it though
> > 
> > 
> > Thanks.But the option "enable 708 decoder" is missing,I can't use it yet ![屏幕截图 2021-09-30 082506](https://user-images.githubusercontent.com/31797996/135366205-14d45560-7ab8-4ae7-883a-8b7b9dcf7859.png) .
> 
> @taozi1996 not sure why you need a enable switch explicitly? When the user enters the service number it's enabled anyway, and that's how it's shown in the current command box, did you hit enter to save?

I get it.I didn't enter to save it.Thank you!
