### ISSUE TITLE
[BUG] HardsubX not working on GUI 0.93 version? 

### ISSUE THREAD

**Issue by jma829** [CCExtractor/ccextractor#1382]
CCExtractor version: {0.93}

# In raising this issue, I confirm the following:

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.
- [x] I have ticked all the boxes in this section and to prove it I'm deleting the section completely to remove boilerplate text.

# Necessary information

- Is this a regression (i.e. did it work before)? {NO}
- What platform did you use? {Windows}
- What were the used arguments? `{replace with the arguments}`

# Video links

* https://drive.google.com/file/d/0B_61ywKPmI0TdlRWcVdnajVJUWs/view?usp=sharing&resourcekey=0-oCZT9NnDCE9h0jMzcma9wg

# Additional information

I have downloaded the 0.93 version and 0.92 version of windows MSI GUI to try to extract subtitle from a hardsub video, I tried using the sample file provided as a start but neither version seem to be working. ccextractor --gui_mode_reports --append -autoprogram -hardsubx -o transcriptEU +[input files] This is what I'm using for the settings. I also tried downloading it on a separate PC and running the sample file, still gives no results. I'm not sure if I am doing something wrong. I would appreciate any input or a guide on how to use this tool correctly in order to make HardSubX work in the GUI. Thanks in advance!

**Comment by canihavesomecoffee** [comment]
Sample also available here: https://sampleplatform.ccextractor.org/sample/173

**Comment by eddilara** [comment]
yeah doesn't work on windows

**Comment by cfsmp3** [comment]
Closing this it's supposed to be fixed. @jma829 @eddilara feel free to reopen and/or comment if you still have issues.
