### ISSUE TITLE
[BUG] Negative -delay values produce empty .srt output

### ISSUE THREAD

**Issue by muzicman0** [CCExtractor/ccextractor#1389]
CCExtractor version: 0.93

# Necessary information

- Is this a regression (i.e. did it work before)? YES (worked 0.88, does not work on 0.93)
- What platform did you use? Windows
- What were the used arguments? `-delay -10000`

# Video links

https://1drv.ms/u/s!AmIBKnKiJ1bih7QqG_PJfxvirnnV5g?e=bXHJe2

link above, but any of my recorded TV files have the same issue.

# Additional information

Negative -delay option on (at least) the CLI doesn't work (empty .srt file).  It did work on version 0.88.  I recently updated to the latest version (0.93) and it no longer works.  tried multiple files, and multiple negative values.

Positive delay options work fine (IE: -delay 1000)

**Comment by PunitLodha** [comment]
This was fixed recently. You can try compiling the code from the master branch

**Comment by muzicman0** [comment]
Thanks.  I saw that it had been fixed.  Compiling is probably beyond me right now, so I will just wait for now.

**Comment by muzicman0** [comment]
.94 is up, so I am checking it out to make sure it works for me.  Thanks!

**Comment by muzicman0** [comment]
I guess I will just stick with the old version.  .94 doesn't work on some files at all, and only pulls a few minutes of captions on others.

**Comment by PunitLodha** [comment]
This could be a big. Could you create a new issue for it? With details about which files aren't working.

Also, there was a change in the flags. In 0.94 :- 
-  if no params are provided:- extract whatever is available, if both(708 and 608) are available then extract both
- If -1/-2 is provided:- extract only 608 subs
- if -svc is provided:- extract only 708 subs
- if both -1/-2 and -svc are provided:- extract both 608 and 708
