### ISSUE TITLE
Case fixing in teletext

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#139]
For American closed captions CCExtractor is able to apply some case conversion rules so instead of all caps we get reasonably correct case.

We need to apply the same logic to Teletext (and well, DVB).

**Comment by Abhinav95** [comment]
#368 fixes this for teletext.

Old sample output:-
8
00:00:20,020 --> 00:00:24,500
WELL, FIVE IS PARTWAY
BETWEEN THREE... NEVER MIND.
9
00:00:24,540 --> 00:00:25,580
I'LL TELL YOU WHAT.
10
00:00:25,620 --> 00:00:27,180
HOW ABOUT WE GO
ROCK-PAPER-SCISSORS?
11
00:00:27,220 --> 00:00:28,380
OOH, I DON'T THINK SO.
12
00:00:28,420 --> 00:00:30,140
ANECDOTAL EVIDENCE SUGGESTS

New sample output with -sc:-
8
00:00:20,020 --> 00:00:24,500
Well, five is partway
between three... Never mind.
9
00:00:24,540 --> 00:00:25,580
I'll tell you what.
10
00:00:25,620 --> 00:00:27,180
How about we go
rock-paper-scissors?
11
00:00:27,220 --> 00:00:28,380
Ooh, I don't think so.
12
00:00:28,420 --> 00:00:30,140
Anecdotal evidence suggests
