### ISSUE TITLE
wrong comand line on windows

### ISSUE THREAD

**Issue by eddilara** [CCExtractor/ccextractor#1400]
for the windows gui version...its using ccextractor instead of the actual binary name of ccextractorwinfull.exe

**Comment by Techno-Disaster** [comment]
Seems to be the correct one? https://github.com/CCExtractor/ccextractorfluttergui/blob/master/lib/repositories/ccextractor.dart#L20

**Comment by eddilara** [comment]
oh ok...I was only looking at the cmd line in the gui
can't figure out why hardsubx cmd won't work on windows

**Comment by Techno-Disaster** [comment]
> oh ok...I was only looking at the cmd line in the gui can't figure out why hardsubx cmd won't work on windows someone who knows what they are doing should take a look at why its complaining about missing tesseract training data

tesseract stuff should be bundled in the msi afaik. 🤔
