### ISSUE TITLE
[BUG] CCExtractor crash in Rust decoder on ATSC1.0 TS Files.

### ISSUE THREAD

**Issue by m1tk4** [CCExtractor/ccextractor#1407]
# In raising this issue, I confirm the following:

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.
- [x] I have ticked all the boxes in this section and to prove it I'm deleting the section completely to remove boilerplate text.

# Necessary information

- Is this a regression (i.e. did it work before)? NO
- What platform did you use? {Window/Linux/Mac} Windows
- What were the used arguments?  "C:\Program Files (x86)\CCExtractor\ccextractorwinfull.exe" -out=ttxt kttv_20150520_1.ts.003

# Version

CCExtractor detailed version info
        Version: 0.94
        Git commit: 97b381a2b0bee35d3b22411772329eb540ee511b
        Compilation date: 2021-12-15
        CEA-708 decoder: Rust
        File SHA256: ff622c2997d8bd515e69a713da7b643cd2bd7fe5b8672153d9619a38026850d7
Libraries used by CCExtractor
        Tesseract Version: 4.00.00alpha
        Leptonica Version: leptonica-1.74 (Dec 31 2016, 10:56:23) [MSC v.1900 LIB Release x86]                                                                libGPAC Version: 1.0.1                                                                                                                                zlib: 1.2.11                                                                                                                                          utf8proc Version: 2.4.0                                                                                                                               protobuf-c Version: 1.3.1                                                                                                                             libpng Version: 1.6.37                                                                                                                                FreeType                                                                                                                                              libhash                                                                                                                                               nuklear                                                                                                                                               libzvbi                                                                                                                                                                               

# Video links
https://drive.google.com/file/d/13qBrgRKm8sTTqTUQvobwXuyviBf5s0MH/view?usp=sharing

# Additional information
CCExtractor crashes as follows on most ATSC1.0 sample files.

VLC decodes the closed captions correctly.

`
CCExtractor 0.94, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
Input: kttv_20150520_1.ts.003
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[CEA-708: 63 decoders active]
[CEA-708: using charset "none" for all services]
[Timing mode: Auto] [Debug: No] [Buffer input: Yes]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .txt] [Encoding: UTF-8] [Delay: 0] [Trim lines: No]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No][Filter profanity: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]
[Quantisation-mode: CCExtractor's internal function]

-----------------------------------------------------------------

Opening file: kttv_20150520_1.ts.003

File seems to be a transport stream, enabling TS mode

Analyzing data in general mode
  1%  |  00:00
  2%  |  00:00

New video information found
[1280 * 720] [AR: 03 - 16:9] [FR: 07 - 59.94] [progressive: yes]

  3%  |  00:00

XDS Notice: Program is now TMZ

XDS: ContentAdvisory: US TV Parental Guidelines. Age Rating: TV-PG (Parental Guidance Suggested)
  
XDS: 
    4%  |  00:00
  5%  |  00:00
  6%  |  00:00
thread '<unnamed>' panicked at 'index out of bounds: the len is 1 but the index is 1', src\decoder\service_decoder.rs:275:25
stack backtrace:
   0:   0x50862a - <unknown>
   1:   0x575581 - <unknown>
   2:   0x578ca8 - <unknown>
   3:   0x578820 - <unknown>
   4:   0x57928e - <unknown>
   5:   0x578e86 - <unknown>
   6:   0x577aef - <unknown>
   7:   0x50f102 - <unknown>
   8:   0x501381 - <unknown>
   9:   0x70b295 - <unknown>
  10:   0x736aba - <unknown>
  11:   0x7202d4 - <unknown>
  12:   0x71f3d3 - <unknown>
  13:   0x71ffa1 - <unknown>
  14:   0x7230be - <unknown>
  15:   0x722954 - <unknown>
  16:   0x69f53f - <unknown>
  17:   0x69ff55 - <unknown>
  18:   0x9d5687 - <unknown>
  19: 0x77286739 - BaseThreadInitThunk
  20: 0x77598aff - RtlGetFullPathName_UEx
  21: 0x77598acd - RtlGetFullPathName_UEx
`

**Comment by canihavesomecoffee** [comment]
File also available here: https://sampleplatform.ccextractor.org/sample/179
