### ISSUE TITLE
[QUESTION] Is there a Windows XP SP2 compatible binary for v0.88 or higher?

### ISSUE THREAD

**Issue by billh8** [CCExtractor/ccextractor#1408]
# Additional information

Currently using v0.87 on Windows XP SP2. Looking for "support for EIA-608 inside .mkv," added in v0.88.

v0.88 error:  "entry point inet_ntop could not be located in dynamic link library WS2_32.dll."
Latest v0.94 error:  "entry point AcquireSRWLockExclusive could not be located in dynamic link library KERNEL32.dll."

**Comment by canihavesomecoffee** [comment]
v0.89 is the last one we released with specific XP compatibility, but I see there's no binaries for that available for some reason...

@cfsmp3 Can you create that or should I look to backport some of the workflows to a 0.89 branch to try and get a Windows installer (or portable version) built?

**Comment by cfsmp3** [comment]
Right now I don't have any way to build for Windows. I need to setup a VM on my new system.

So if you can please go ahead

**Comment by canihavesomecoffee** [comment]
@billh8 Could you check if the portable zip I've build on my fork is working for you? https://github.com/canihavesomecoffee/ccextractor/releases/tag/v0.89a

It's the 0.89 version. If it works I can create a new release here.

**Comment by billh8** [comment]
Tested the v0.89 portable zip on WinXP SP2 without any errors. Also successfully tested it on 2 mkv files with EIA-608 captions. Thanks a lot!

**Comment by canihavesomecoffee** [comment]
Closing as it seems to be working. I uploaded the same zip to the 0.89 release, and if we make bugfixes for that branch there will be automated builds that add the same (portable) zip version.

@cfsmp3 I also updated the 0.94 release to state that 0.89 is the last supported one for XP... But we might need some other places to state that too perhaps? I.e. website, readme?

**Comment by cfsmp3** [comment]
> Closing as it seems to be working. I uploaded the same zip to the 0.89 release, and if we make bugfixes for that branch there will be automated builds that add the same (portable) zip version.
> 
> @cfsmp3 I also updated the 0.94 release to state that 0.89 is the last supported one for XP... But we might need some other places to state that too perhaps? I.e. website, readme?

I guess here
https://ccextractor.org/public/general/downloads/

We could have Windows XP and Windows 7 or above

@Techno-Disaster can you do this change?

**Comment by Techno-Disaster** [comment]
Done https://github.com/CCExtractor/website/commit/ee44fac1f644912317101e876e4f4a8ea1ae3eb5
