### ISSUE TITLE
[PROPOSAL] Return file drag and drop to the new GUI

### ISSUE THREAD

**Issue by r0ckingit** [CCExtractor/ccextractor#1413]
CCExtractor version: CCExtractor 0.94, Carlos Fernandez Sanz, Volker Quetschke.

# In raising this issue, I confirm the following:

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.

# Necessary information

- Is this a regression (i.e. did it work before)? {YES}
- What platform did you use? {Window}
- What were the used arguments? N/A

# Video links

* N/a

# Additional information

In the old GUI before the recent switch, we could drag our video file(s) to the input files tab. I'd like to see similar behavior return where we can drag file(s) to the "Selected files" box.

**Comment by r0ckingit** [comment]
Just noticed there is ccextractorfluttergui. This fits better there, apologies.

**Comment by canihavesomecoffee** [comment]
No worries @r0ckingit.

Looks like the issue was already on @Techno-Disaster's wishlist: https://github.com/CCExtractor/ccextractorfluttergui/issues/6

**Comment by Techno-Disaster** [comment]
> 

We also have https://github.com/CCExtractor/ccextractorfluttergui/pull/10 :P but looks like its dead.

**Comment by manoj1749** [comment]
Heyy @r0ckingit  Is anyone working on this issue, looks dead, if no one's working I am intrested to work on this

**Comment by cfsmp3** [comment]
@manoj1749 go for it, if there's been no changes in a long time let's assume it's abandoned.

**Comment by manoj1749** [comment]
ok sure👍

**Comment by manoj1749** [comment]
@cfsmp3  for this issue where should I make the pr
to this one or the other one [ccextractorfluttergui](https://github.com/CCExtractor/ccextractorfluttergui)
I was a bit confused as the issue was in this repository and it was labelled as flutter

**Comment by cfsmp3** [comment]
> @cfsmp3  for this issue where should I make the pr
> to this one or the other one [ccextractorfluttergui](https://github.com/CCExtractor/ccextractorfluttergui)
> I was a bit confused as the issue was in this repository and it was labelled as flutter

In the repository that contains that code, or course 😊

**Comment by manoj1749** [comment]
of course I know that, as this issue was labelled as Flutter GUI and the repository doesn't contain anything related to flutter, that's why I am asking

**Comment by cfsmp3** [comment]
> of course I know that, as this issue was labelled as Flutter GUI and the repository doesn't contain anything related to flutter, that's why I am asking

From the point of view of users, it's a CCExtractor thing (both the GUI and the CLI are part of the same thing).

Not unusual to find issues relative to the GUI here, it's fine. 

Just send a PR on the other repo and we can close the issue here when ready.

**Comment by manoj1749** [comment]
ok sure

**Comment by manoj1749** [comment]
Heyy @cfsmp3 , I had made the PR on the other repository regarding this issue https://github.com/CCExtractor/ccextractorfluttergui/pull/41 , can you review it once?

**Comment by cfsmp3** [comment]
@manoj1749 , @Techno-Disaster is the right person for that PR :-)

**Comment by manoj1749** [comment]
ok, thanks , I'll ask him for review then

**Comment by manoj1749** [comment]
- This issue can be closed as the drag and drop feature is added to the GUI application with the merged pr https://github.com/CCExtractor/ccextractorfluttergui/pull/41

**Comment by canihavesomecoffee** [comment]
Not closeable yet, we need a release from the GUI first

**Comment by Techno-Disaster** [comment]
probably can make a new release after https://github.com/CCExtractor/ccextractorfluttergui/pull/42

**Comment by Techno-Disaster** [comment]
@canihavesomecoffee https://github.com/CCExtractor/ccextractorfluttergui/releases/tag/v0.6.0

**Comment by canihavesomecoffee** [comment]
Then that'll all be included in the next release of CCExtractor :)
