### ISSUE TITLE
[QUESTION] concatenating files

### ISSUE THREAD

**Issue by sttaylor** [CCExtractor/ccextractor#1416]
I recently switched to the pretty new GUI (sorry, I don't have the release # handy) and now when I run CCExtractor, it creates a separate srt file for each vob file that it processes. What do I need to set so that they concatenate into a single srt file?

**Comment by cfsmp3** [comment]
@Techno-Disaster can you check this out?

**Comment by Techno-Disaster** [comment]
Hmm iirc there is a split mode option in the settings, if you turn it on any selected videos will be treated as a group and you should get only one srt file.

**Comment by cfsmp3** [comment]
@sttaylor feel free to reopen if you still have issues.
