### ISSUE TITLE
[Bug] (version .94)  parameter -inp=ts not understood

### ISSUE THREAD

**Issue by egossett** [CCExtractor/ccextractor#1437]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

I have a .ts file that contains programs 3, 4, and 6. I need subtitles for program 4.
I set the program number to 4 in "Obscure settings" and changed from "auto/default" to "ts" in "Basic settings"/input file format.

I get the error: parameter -inp=ts not understood

If I use "auto/default" for the input file format, the program number is ignored.

**Comment by egossett** [comment]
The parameter should be -in=ts

**Comment by canihavesomecoffee** [comment]
That's a GUI issue (I believe you're using the GUI?), so @Techno-Disaster...

**Comment by egossett** [comment]
Yes, it is a GUI issue. Too bad the gui doesn't let you edit the command line parameters in the basic settings tab. Should be a 2-minute fix.

**Comment by Techno-Disaster** [comment]
strange -in is -in according to https://github.com/CCExtractor/ccextractorfluttergui/blob/master/lib/models/settings_model.dart#L227

**Comment by egossett** [comment]
I have the latest version. The command box shows "inp=ts". If I run CCExtractor from the command line with "inp" replaced by "in", it works. That means the GUI has a small error in creating the correct command line.

**Comment by Techno-Disaster** [comment]
https://github.com/CCExtractor/ccextractorfluttergui/commit/155596b2633ef3be9050a70e8c4ba223eb5d2867 should fix it :D

**Comment by egossett** [comment]
Thank you very much for the fix. Since I am running this on Windows 10 and not a Unix system, I will need to wait for the next non-source update to use this fix.

**Comment by canihavesomecoffee** [comment]
Once the workflows finish you can normally download the artifacts for Windows, and replace the GUI exe in your installation folder. If you don't want to do that, yes, you'll have to wait until a new release is made.

**Comment by egossett** [comment]
Ok. I will try that.

**Comment by cfsmp3** [comment]
Closing since this was fixed - @egossett free feel to reopen if you still have issues with the last GUI version.
