### ISSUE TITLE
Fix HardsubX builds

### ISSUE THREAD

**Issue by PunitLodha** [CCExtractor/ccextractor#1445]
Tracking issue for fixing HardsubX builds on all platforms. 
New feature was added to the rust crate to optionally enable compiling of HardsubX. These platforms need fixing to add that feature flag in the `cargo build` command and make any required platform specific changes. Also need to update the compilation docs wherever required.

I haven't checked all. Some might already be working correctly without need for any changes.
- [x] Linux/cmake #1443 
- [x] Linux/build script #1443 
- [build_hardsubx](https://github.com/CCExtractor/ccextractor/blob/master/linux/build_hardsubx) and [build](https://github.com/CCExtractor/ccextractor/blob/master/linux/build)
- [x] Linux/autoconf #1443 
- [Makefie.am](https://github.com/CCExtractor/ccextractor/blob/master/linux/Makefile.am) and [configure.ac](https://github.com/CCExtractor/ccextractor/blob/master/linux/configure.ac)

- [ ] Windows/(Release/Debug)-Full
- Issue with `ffmpeg-sys-next` build script. [logs](https://github.com/CCExtractor/ccextractor/runs/7178625210?check_suite_focus=true) |  [Issue](https://github.com/zmwangx/rust-ffmpeg-sys/issues/42)

- [ ] Mac/cmake (Need to confirm if Mac requires anything specific for cmake)
- [ ] Mac/build script
- [build.command](https://github.com/CCExtractor/ccextractor/blob/master/mac/build.command)
- [x] Mac/autoconf
- [Makefie.am](https://github.com/CCExtractor/ccextractor/blob/master/mac/Makefile.am) and [configure.ac](https://github.com/CCExtractor/ccextractor/blob/master/mac/configure.ac)

**Comment by shashwat1002** [comment]
@PunitLodha 

for autoconf, the linux and mac scripts seem to be identical in master (I see the mac specific clause only adds new sources)
So I am copying the autoconf script for mac for now. But I have no way of testing locally.

**Comment by PunitLodha** [comment]
Fixed by #1480 
Thanks @prateekmedia
