### ISSUE TITLE
Bad timing in the DVD "The Net"

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#145]
The original DVD of The Net (which had closed captions instead of DVD subtitles) doesn't get along well with CCExtractor. In particular, timing is incorrect (it goes off around 2 minutes by the end of the movie).

VOBs are available in the developer repository.

**Comment by ivladak** [comment]
Here are my solutions along with a pdf copy of my proposal.

2015-03-27 0:02 GMT+03:00 cfsmp3 <notifications@github.com>:

> The original DVD of The Net (which had closed captions instead of DVD
> subtitles) doesn't get along well with CCExtractor. In particular, timing
> is incorrect (it goes off around 2 minutes by the end of the movie).
>
> VOBs are available in the developer repository.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CCExtractor/ccextractor/issues/145>.
>



-- 
С уважением, Владислав Иванишин

**Comment by cfsmp3** [comment]
Timing seems correct to me (when playing the VOB against the .srt), *however* there seems to be some corruption (could be the source though) at the first subtitle frame so it's worth checking it out.

Anshul, I'm assigning this to you since I also noticed that + (the file sequence stuff) is broken after the librarization stuff.

**Comment by cfsmp3** [comment]
Stale
