### ISSUE TITLE
[QUESTION] FreeBSD pkg/port

### ISSUE THREAD

**Issue by Baenwort** [CCExtractor/ccextractor#1450]
CCExtractor version:  0.85_21 on FreeBSD

# Necessary information

- Is this a regression (i.e. did it work before)? {YES}
- What platform did you use? {FreeBSD 13.1}
- What were the used arguments? `{ccextractor --version or any other use of ccextractor}`

# Additional information
 

> ld-elf.so.1: Shared object "libjxl.so.0.6" not found, required by "ccextractor"

Since upgrading to FreeBSD 13.1 I have been getting the missing shared object when trying to use ccextractor installed from the pkg manager. 

From https://www.freshports.org/multimedia/ccextractor/ I see that the the port is being pulled due to outdated dependencies. I wanted to ask if there is any hope for a update to the FreeBSD port of CCExtractor or if I should start a hunt for some other way to extract close captioning from the TV shows I record from OTA?

Thank you for your time,

**Comment by Baenwort** [comment]
For anyone else who is hoping to get ccextractor to work on a FreeBSD based system a port has been created at: https://github.com/PhilOleson/freebsd-ports/tree/master/ccextractor that I'm able to complete a 'make install clean' on and it runs and extracts subs on my system.

**Comment by cfsmp3** [comment]
Closing - this is not really actionable, if someone wants to send us a PR we'll merge, but I don't think anyone in the team uses FreeBSD?
