### ISSUE TITLE
[BUG] stdout argument not respected when multiple CC track found.

### ISSUE THREAD

**Issue by Adityashaw** [CCExtractor/ccextractor#1453]
```
ccextractor --version
CCExtractor 0.94, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
CCExtractor detailed version info
	Version: 0.94
	Git commit: Unknown
	Compilation date: 2022-09-06
	CEA-708 decoder: Rust
	File SHA256: Could not open file
Libraries used by CCExtractor
	libGPAC Version: 1.0.1
	zlib: 1.2.11
	utf8proc Version: 2.4.0
	protobuf-c Version: 1.3.1
	libpng Version: 1.6.37
	FreeType 
	libhash
	nuklear
	libzvbi
```

# In raising this issue, I confirm the following:

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [ ] I have used the latest available version of CCExtractor to verify this issue exists.
- [ ] I have ticked all the boxes in this section and to prove it I'm deleting the section completely to remove boilerplate text.

# Necessary information

- Is this a regression (i.e. did it work before)? NO
- What platform did you use? Linux (`Linux hp 5.15.61-1-lts #1 SMP Wed, 17 Aug 2022 15:11:32 +0000 x86_64 GNU/Linux
`)
- What were the used arguments? `ccextractor -stdout -quiet input.mkv`

PS: I downloaded and renamed below file.

# Video links

*  `https://www.libde265.org/hevc-bitstreams/tos-4096x1720-tiles.mkv`

# Additional information

*Expected*: Output on stdout/terminal
*Actual*: Output on multiple srt files

How can I get all/one CC output on stdout instead of creating multiple files?

**Comment by abhi-kr-2100** [comment]
I'm working on this.

I've successfully built the latest checkout from source and reproduced this bug. Currently, I'm exploring the codebase to get familiar with it. I'll post here as I make progress towards identifying and fixing this issue.

**Comment by abhi-kr-2100** [comment]
I've made a pull request fixing this issue for the particular case of .mkv or Matroska input files with multiple CC tracks.

**Comment by cfsmp3** [comment]
@Adityashaw is the bug still there?

**Comment by Adityashaw** [comment]
> @Adityashaw is the bug still there?

I do not see any new version on `Arch User Repository` since I posted this issue. I won't be able to compile myself this month due to timing constraints.

Hence, I won't be able to confirm the existence of the issue as of now.

**Comment by cfsmp3** [comment]
> 
> Hence, I won't be able to confirm the existence of the issue as of now.

Closing for now. Feel free to reopen when you have a chance to verify.
