### ISSUE TITLE
[BUG] "Build CCExtractor on Windows" CI is broken

### ISSUE THREAD

**Issue by abhi-kr-2100** [CCExtractor/ccextractor#1461]
# In raising this issue, I confirm the following:

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.
- [x] I have ticked all the boxes in this section and to prove it I'm deleting the section completely to remove boilerplate text.

# Necessary information

- Is this a regression (i.e. did it work before)? {YES}
- What platform did you use? {Window}
- What were the used arguments? {N/A}
---
The CI check "Build CCExtractor on Windows" has failed for every currently open PR (while all other CI tests pass). However, most of these PRs don't make changes that would cause build to break only on Windows. The "Build CCExtractor on Windows" CI seems to be broken.

From the details, the following error about leptonica can be seen:
```
EXEC : error : failed to run custom build command for `leptonica-sys v0.4.1` [D:\a\ccextractor\ccextractor\windows\ccextractor.vcxproj]
```

**Comment by PunitLodha** [comment]
Fixed by #1480
