### ISSUE TITLE
cant 

### ISSUE THREAD

**Issue by ikiss68** [CCExtractor/ccextractor#1462]
Please prefix your issue with one of the following: , [QUESTION]
To get the version of CCExtractor, you can use ` latest version`.

Hello i cant take out the DVBSUB from the mpeg file, whitch is contains hungarian DVB sub for movie, please help..  if u want i can send the whole mpeg file. my mail: zoleeszolnok@me.com
I tired several times but the app cant find it, but it contans!!!

**Comment by abhi-kr-2100** [comment]
Hello, @ikiss68. This may not solve the bug in CCExtractor that's causing this issue but can you try doing an `ffmpeg -i infile.ts -map v:0 -map a:0 -map s:0 -c copy -format mpegts outfile.ts` and then run CCExtractor on `outfile.ts`.

Issue #1455 is similar; this might be related.

**Comment by ikiss68** [comment]
Thanks but my file is infile.mpeg not .ts extention. Is it good?

**Comment by abhi-kr-2100** [comment]
Maybe you'll need to change the `-format` argument. First try without passing any formats, then try others that you may feel are suitable.

Can you also post here the output of running `file infile.mpeg`?

**Comment by ikiss68** [comment]
It would be better if I could send the mpeg file (6gbyte) because I have a Mac not windows Regards, Zoli2022. nov. 30. dátummal, 21:44 időpontban abhi-kr-2100 ***@***.***> írta:﻿
Maybe you'll need to change the -format argument. First try without passing any formats, then try others that you may feel are suitable.
Can you also post here the output of running file infile.mpeg?

**Comment by abhi-kr-2100** [comment]
I've sent you a mail requesting the file. Regards.

**Comment by cfsmp3** [comment]
Closing since we don't have a sample.
