### ISSUE TITLE
[QUESTION][BUG] Unable to extract hardcoded subs

### ISSUE THREAD

**Issue by worthaglimpse** [CCExtractor/ccextractor#1466]
I have built ccextractor with hardsubx, placed hebrew training file in tessdata, I am still unable to extract hardcoded subtitles. It says [iso file] Found stts entry with sample_delta=0 - forbidden ! Fixing to 1 
After that it just stops within seconds and says No captions were found in input.

**Comment by cfsmp3** [comment]
@worthaglimpse We'd need a sample in order to look into it.
Feel free to open the issue with a link to a video we can download.
