### ISSUE TITLE
[BUG] Unable to extract CEA708 closed captions

### ISSUE THREAD

**Issue by ProjectEGU** [CCExtractor/ccextractor#1468]
CCExtractor version: 0.94

# In raising this issue, I confirm the following:

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.
- [x] I have ticked all the boxes in this section and to prove it I'm deleting the section completely to remove boilerplate text.

# Necessary information

- Is this a regression (i.e. did it work before)? `No`
- What platform did you use? `Windows`
- What were the used arguments? `ccextractorwinfull.exe cea708_dtv.mpg`

# Video links

https://www.pixeltools.com/mpeg/cea708_dtv.mpg

# Additional information

Relevant MediaInfo portion:
```
Text
ID                                       : 481 (0x1E1)-1
Menu ID                                  : 1 (0x1)
Format                                   : EIA-708
Muxing mode                              : A/53 / DTVCC Transport
Muxing mode, more info                   : Muxed in Video #1
Duration                                 : 5 s 5 ms
Bit rate mode                            : Constant
Stream size                              : 0.00 Byte (0%)
```
Relevant info from [pixeltools website](https://www.pixeltools.com/tech-tip-closed-captioning-existing.html):
`CEA 708 DTV User moveable and re-sizable captioning for HDTV`

Expected text content:
```
This is a demo of the 
Closed Captioning Insertion 
From PixelTools 
Have a Nice Day!
```

**Comment by tirth-bhagwat** [comment]
I tried to extract subtitles from the same video file on Fedora 37 (6.1.18-200.fc37.x86_64) but a blank `.srt` file is generated.

Command: `/home/tirth/Forks/ccextractor-fork/linux/ccextractor cea708_dtv.mpg > ./op2.txt`
Output of command : [op2.txt](https://github.com/CCExtractor/ccextractor/files/11002205/op2.txt)
