### ISSUE TITLE
Personal Pronoun Capitalization

### ISSUE THREAD

**Issue by Fogdood** [CCExtractor/ccextractor#147]
I have developed a word list which I use in conjunction with your option to convert the case of captions & use an external list for names & such. In version .69, this works great & except where it always capitalizes the new line, whether it is the continuation of an existing sentence or not, is perfect. Unfortunately, every newer release fails to capitalize the personal pronoun "I". If it were possible to do a simple search & replace on this, it would not be an issue, but I have found no way to do that, as every subtitle editor I use (I have many) is incapable of locating every instance of the simple word "I" correctly, making it a manual task of, sometimes, herculean proportions. I am hoping you will eventually be able to correct this situation, as I'm sure I'm missing out on other improvements I have so far been unable to enjoy.

**Comment by anshul1912** [comment]
@Fogdood can you check it with git version please, this issue is resolved
