### ISSUE TITLE
[BUG] missing file on dropbox for docker. Installation failed

### ISSUE THREAD

**Issue by AhmedGit** [CCExtractor/ccextractor#1472]
While installing as end user from docker, it threw this error:

 => ERROR [27/37] RUN wget https://www.dropbox.com/s/dl/h2owqbmnrsvqo0c/ord_map_en.json                                                                                                                     0.9s
------
 > [27/37] RUN wget https://www.dropbox.com/s/dl/h2owqbmnrsvqo0c/ord_map_en.json:
#30 0.341 --2023-01-23 13:42:22--  https://www.dropbox.com/s/dl/h2owqbmnrsvqo0c/ord_map_en.json
#30 0.346 Resolving www.dropbox.com (www.dropbox.com)... 162.125.69.18, ::ffff:162.125.69.18
#30 0.397 Connecting to www.dropbox.com (www.dropbox.com)|162.125.69.18|:443... connected.
#30 0.575 HTTP request sent, awaiting response... 404 Not Found
#30 0.844 2023-01-23 13:42:23 ERROR 404: Not Found.
#30 0.844
------
executor failed running [/bin/sh -c wget https://www.dropbox.com/s/dl/h2owqbmnrsvqo0c/ord_map_en.json]: exit code: 8

**By manually checking the ord_map_en.json file, the link is not working, it gives 404 error.

I manually checked this link too, it is not found: https://www.dropbox.com/s/dl/yzkijd7j5yflhli/char_dict_en.json

please update the links so that it works. thanks.

**Comment by canihavesomecoffee** [comment]
Closing as it's not the correct repo (see https://github.com/CCExtractor/Rekognition/issues/230)
