### ISSUE TITLE
I am not able to setup this project locally 

### ISSUE THREAD

**Issue by amaranand360** [CCExtractor/ccextractor#1476]
I am following the steps from Link: https://github.com/CCExtractor/ccextractor/wiki/Installation#windows
here in Step 2. Re-target and Build, how do I know  VS version and Windows SDK version that match my installation?

**Comment by manoj1749** [comment]
- you can just  go to Help > About to find your Visual Studio version in the Visual Studio app.
- And I didn't get what you mean by WIndows SDK, but windows is an OS not an SDK, and your windows version will be the one you using like Windows 11 or 10 or something.

**Comment by amaranand360** [comment]
Can you plz explain this step:
https://github.com/CCExtractor/ccextractor/wiki/Installation#step-2-re-target-and-build

**Comment by manoj1749** [comment]
Everything is clearly explained, which part should I need to explain

**Comment by amaranand360** [comment]
Step 2. Re-target and Build,   Can you plz  explain the  step 2 properly,
In step 2  How do I know VS version and Windows SDK version that match my installation.
