### ISSUE TITLE
Cannot open input file 'ccx_rust.lib'

### ISSUE THREAD

**Issue by amaranand360** [CCExtractor/ccextractor#1477]
I clicked on build I am getting ` Error LNK1181 Cannot open input file 'ccx_rust.lib'`

Error pic
![Screenshot (14)](https://user-images.githubusercontent.com/122713145/218297109-4edd4118-a94a-42e3-82e0-c9b16edde1dc.png)

OUTPUT PIC
![Screenshot (15)](https://user-images.githubusercontent.com/122713145/218297259-af0e1125-1b82-4b3c-870b-8ca229990f8c.png)

**Comment by PunitLodha** [comment]
Is this still an issue on the latest master branch?

**Comment by cfsmp3** [comment]
@amaranand360 Please reopen the issue if you still have problems.
