### ISSUE TITLE
[BUG] Rust decoder not used for 708 captions on MPEG-TS files

### ISSUE THREAD

**Issue by ArchitBhonsle** [CCExtractor/ccextractor#1500]
CCExtractor version: 0.94 (Build from master with `cmake` and no flags)

# In raising this issue, I confirm the following:

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.
- [x] I have ticked all the boxes in this section and to prove it I'm deleting the section completely to remove boilerplate text.

# Necessary information

- Is this a regression (i.e. did it work before)? Yes (I think this was supposed to work before)
- What platform did you use? Linux
- What were the used arguments? `./build/ccextractor ~/Downloads/CCExtractor/7236304cfcfce141c7cec31647c1268a3886063390ce43c2f71188c70f5494c4/video.ts -608 -708 -out=smi `

# Video links

https://sampleplatform.ccextractor.org/sample/7236304cfcfce141c7cec31647c1268a3886063390ce43c2f71188c70f5494c4

# Additional Information

I'm pretty sure this is using the C decoder for 708. The reason I think this is C is because C does everything [in uppercase](https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/ccx_encoders_sami.c#L18) while rust is [in lowercase](https://github.com/CCExtractor/ccextractor/blob/master/src/rust/src/decoder/tv_screen.rs#L336). 

[Command and logs](https://github.com/CCExtractor/ccextractor/files/10978258/smi-output.txt)
[Subtitles produced](https://github.com/CCExtractor/ccextractor/files/10978263/video.smi.txt)

**Comment by marcybelardo** [comment]
I think in this case, C was showing up because there isn't an implementation for the 608 decoder in Rust yet. 

[Reproducing logs with same command](https://github.com/CCExtractor/ccextractor/files/11080543/both_decoders.txt)
[Command/logs with only 708 enabled](https://github.com/CCExtractor/ccextractor/files/11080542/708_only.txt)

I believe even after the decoder for 708 is fixed, the C encoding will show up in stdout until 608 is ported to Rust too
