### ISSUE TITLE
DVB subtitles from TNT (France)

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#151]
I have tried to extract dvb subtitles in text or picture format of of a
dvb-t record from TNT in France without any success.
Are there any limitation in dvb subtitles support with current version of
cc extractor ?

Here is the extract of the record I tried to
http://dl.free.fr/gn7ofWDq0

[Carlos' note: Uploaded to /Franck/m6record.ts in developer's repository]

Vlc can display the subtitles without any problem
I tried buy a build version of 0.76 of ccextractor
It look like there is a problem in pts parsing as min and max pts are indentical

===========
Here is the result:
Opening file: /home/franck/sub/videos/m6record.ts
File seems to be a transport stream, enabling TS mode
Analyzing data in general mode

Number of NAL_type_7: 0
Number of VCL_HRD: 0
Number of NAL HRD: 0
Number of jump-in-frames: 0
Number of num_unexpected_sei_length: 0

Total frames time:        00:00:00:000  (0 frames at 29.97fps)

Min PTS:                                13:33:58:190
Max PTS:                                13:33:58:190
Length:                          00:00:00:000

**Comment by kisselef** [comment]
Looks like the problem appears when parsing PSI.
Here is my debug output for "parse_PMT":

Read PMT packet  (id: 2) program number: 1
  section length: 81  number: 0  last: 0
  version_number: 0  current_next_indicator: 1
  PCR_PID: 120  data length: 68  payload_length: 4294967252

Program Info Length is 0, and payload length becomes a huge value when casted to unsigned (tspacket+188-buf = -44 signed). Probably, @anshul1912 knows the reason. If not, I'll try to find out how to calculate it accurately. 

@anshul1912 ?

**Comment by kisselef** [comment]
I've found a problem in TS Packets handling. Seems that my quick fix will break correct application flow for other files and I had also met some unexpected behavior of an application for this file. So, fixing will take a while, but it is in progress.

**Comment by kisselef** [comment]
There were "empty" PES packets (00 00 01 BE 00 01 FF) in the dvb-subtitle stream. Since minimum size for video PES is 9 bytes, but we were parsing non video PES, parsing had to be terminated. I tested fix using couple TS and PS files and everything worked fine, so it seems fix https://github.com/CCExtractor/ccextractor/pull/154 doesn't affect other stream and file types.
