### ISSUE TITLE
Crash on PMT parsing

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#153]
"http://www.worldtrad.org/Bones - 16.ts"

That file causes a crash here:
int write_section(struct lib_ccx_ctx *ctx, struct ts_payload *payload, unsigned char*buf, int size, int pos)
{
	if (payload->pesstart)
	{
		memcpy(payload->section_buf, buf, size);

(size == -3)

**Comment by mailumangjain** [comment]
http://www.worldtrad.org/Bones : Link not working (here) !
If @cfsmp3 finds it working, can he/anyone upload to developer repository ?

**Comment by wforums** [comment]
It's not just that, it's the total link you need: "http://www.worldtrad.org/Bones - 16.ts" - That's the reason why Carlos put it between quotes.

**Comment by mailumangjain** [comment]
okay, got you :)

**Comment by cfsmp3** [comment]
Yes, this is fixed.
