### ISSUE TITLE
[BUG] CCextractor uses bashism in configure script

### ISSUE THREAD

**Issue by utkarsh2102** [CCExtractor/ccextractor#1549]
Originally reported as: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=998781

> Hi,
> 
> Your package uses configure script with bash features not present in
> POSIX without explicitly declaring the need to bash shell; this
> currently works as configure scripts select bash, but when dash enables
> LINENO support, your configure script will start failing:
> 
>      checking pkg-config m4 macros... ./configure: 4747: test: yes: unexpected operator
>      no
>      configure: error: 
>      pkg-config is required.
>      	cd linux && tail -v -n \+0 config.log
> 
> To test this, you can install dash from experimental and re-run the
> configure script.
> 
> Please replace non-POSIX features with their equivalents to make sure
> the script runs with dash. Most common ones are usage of == instead of =
> and for with arrays (not lists).

**Comment by utkarsh2102** [comment]
Hi @prateekmedia,

I believe this patch works:

```
--- a/linux/configure.ac
+++ b/linux/configure.ac
@@ -15,7 +15,7 @@ AC_PROG_MAKE_SET
 
 #Checks for "pkg-config" utility
 AC_MSG_CHECKING([pkg-config m4 macros])
-if test m4_ifdef([PKG_CHECK_MODULES], [yes], [no]) == yes; then
+if test m4_ifdef([PKG_CHECK_MODULES], [yes], [no]) = yes; then
        AC_MSG_RESULT([yes]);
 else
        AC_MSG_RESULT([no]);
diff --git a/mac/configure.ac b/mac/configure.ac
index 7cf89f2..81781c7 100644
--- a/mac/configure.ac
+++ b/mac/configure.ac
@@ -15,7 +15,7 @@ AC_PROG_MAKE_SET
 
 #Checks for "pkg-config" utility
 AC_MSG_CHECKING([pkg-config m4 macros])
-if test m4_ifdef([PKG_CHECK_MODULES], [yes], [no]) == yes; then
+if test m4_ifdef([PKG_CHECK_MODULES], [yes], [no]) = yes; then
        AC_MSG_RESULT([yes]);
 else
        AC_MSG_RESULT([no]);
```

What do you think? If you think that works for you as well, I can make a PR and we can land this one.

**Comment by utkarsh2102** [comment]
Also, when doing the standard linux compilation, I get:

`./configure: line 7381: test: syntax error: `-larchive' unexpected`

on running `./configure`. Hm, is that expected?

**Comment by prateekmedia** [comment]
I will check it this weekend.

**Comment by utkarsh2102** [comment]
> I will check it this weekend.

Hey, have you had time to take a quick look at this?

**Comment by prateekmedia** [comment]
@utkarsh2102 can you create a PR for this patch, I will take a look.

**Comment by prateekmedia** [comment]
Also If you can change the backticks to $() syntax then please go ahead.

**Comment by prateekmedia** [comment]
@utkarsh2102 I have created a PR #1572 for the same, can you check.
