### ISSUE TITLE
How to even build the whole software from the repo

### ISSUE THREAD

**Issue by supuram** [CCExtractor/ccextractor#1569]
Hey community members,
I have been trying to run the software using this repo. The idea is to compile this repo so that the software gets build and i can extract the subtitles using that. Also if i make any change to the codebase i can clearly see the different way the software has compiled and will be able to see it when the software runs. But i cannot do anything. I am using Windows11 and Visual Studio as an IDE. I have read the full documentation and did everything that is there - installed vcpkg, cmake, tried to build with Visual studio, but to no avail. Any help with this regard will be helpful.

**Comment by cfsmp3** [comment]
Please don't use github issues for support questions. They are for bugs and feature requests.
Please reach out on slack instead, thanks.
