### ISSUE TITLE
[BUG] segmentation fault on 608 decode

### ISSUE THREAD

**Issue by robclemamzn** [CCExtractor/ccextractor#1644]
CCExtractor detailed version info
	Version: 0.94
	Git commit: Unknown
	Compilation date: 2021-12-15
	CEA-708 decoder: C

command line used:

 ccextractor -stdout ./TOS_1080x800_2x_embeddedCaptions.mp4
 
public source file has 608 and 708 tracks: 
---> https://dxl5rnnj43ic4.cloudfront.net/TOS/MP4/TOS_1080x800_2x_embeddedCaptions.mp4

-debug flag shows some decode taking place before seg fault.

**Comment by cfsmp3** [comment]
Please try with a current version (compile from source).  
The problem is likely fixed already.
