### ISSUE TITLE
alternate subtitles missing on UK freeview .TS files

### ISSUE THREAD

**Issue by rodnmatt** [CCExtractor/ccextractor#172]
Input 
https://www.dropbox.com/s/nvi4j0amowkthjy/Harry%20Potter%20Chamber%20of%20Secrets_20150530_14401740.ts?dl=0
Output
https://www.dropbox.com/s/a7w3suf4n1ke7cn/Harry%20Potter%20Chamber%20of%20Secrets_20150530_14401740.srt?dl=0

several files tried with same result command line and GUI produce same results 
using default options only

**Comment by wforums** [comment]
What commands are you using, and what do you actually expect as output? Would be helpful for us to debug the issue... I can see that the srt contains some output, but without further explanation it's a bit hard to know what you want (still downloading the ts) ...

**Comment by rodnmatt** [comment]
I used defaults on both the GUI and the Command line option. Once you get the TS file try viewing with VLC and you will see that alternate subtitles  are missing.

**Comment by wforums** [comment]
Hey,

It looks like you're right.

There are entire lines missing, as well as the first line of multi-line sections.

**Comment by beneix** [comment]
I have the same issue, using SD ts stream from UK Freeview DVB broadcast as input. Every other text line is captured, every other one is lost. Is this bug being worked on?

**Comment by anshul1912** [comment]
are you using git version, share file too, I have fixed similar issue last month

**Comment by canihavesomecoffee** [comment]
@rodnmatt @beneix 

Hello, to come back to this bug: Could you try it again? I seem to be getting correct results when using the GUI on Windows (0.80 version).

**Comment by cfsmp3** [comment]
Closing since the links don't work anymore and the original poster is ignoring questions
