### ISSUE TITLE
Line Breaks: %%--PP

### ISSUE THREAD

**Issue by slifty** [CCExtractor/ccextractor#190]
I'm exploring the idea of creating a new "network" output type which could send the output to a TCP as opposed to stdout or a file.

When the output type is txt, I'm noticing that new lines are being sent as 0x25 0x25 0xAD 0xAD 0xD0 0xD0 which, when parsed as ASCII, amounts to %%--PP.

```
00:00:06:673   0   FC:%:25    <>   ..   ..
00:00:06:706   0   FC:%:25    <>   ..   ..
00:00:06:740   0   FC:-:AD    <>   ..   ..
00:00:06:773   0   FC:-:AD    <>   ..   ..
00:00:06:806   0   FC:P:D0    <>   ..   ..
00:00:06:840   0   FC:P:D0    <>   ..   ..
00:00:06:873   0   FC:I':A7    I'   ..   ..
00:00:06:906   0   FC:M :20    M    ..   ..
00:00:06:940   0   FC:NO:4F    NO   ..   ..
00:00:06:973   0   FC:T :20    T    ..   ..
```

I've spent a very long time scouring the code base to better understand why this might be, and more specifically, why this does NOT render as %%--PP when writing to stdout, but I think I have to give up in the name of my sanity.

Does anyone know the answer to this riddle?

**Comment by cfsmp3** [comment]
slifty what's the current status?

**Comment by cfsmp3** [comment]
Closing since original poster doesn't reply.
