### ISSUE TITLE
GSOC - Wordwide repository

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#2]
Building on the "Real time uploading" task, it makes sense to aggregate all available caption data. 

A problem with captioning is of course that you need to be able to receive the TV signal, which makes it impossible for any individual entity to capture data from all TV channels in the world. We want to allow everyone with the required hardware to be able to contribute to a global effort; the task is to build an scalable system that is able to receive data for a large number of providers. Google's App Engine would be a good option to start building.

**Comment by gvishal** [comment]
I played around with ccextractor-server given above.

Now as I understand we want to use Google App Engine to employ this server which receives data from various sources and also provide a User Interface to view this data.

The server currently has two components:
1. A C implementation to which anyone can connect and stream data, server writes data to DB.
2. A PHP based web server which can be used to view live data and also query past data.

Then, if we use google app engine, then the second component can be easily done in either PHP or Python. But,
1. A C implementation of server given above will not work there, and
2. Google app engine doesn't allow listening sockets.
I was thinking of ways to do this using Google App Engine. Any ideas? Also, which language is preferred PHP vs Python for this project?

Are there any particular sample exercises that I need to do for this particular project?

Currently ccextractor uses only TCP to send data in BIN format to server. What other protocols need to be implemented as part of "Real time uploading"?
