### ISSUE TITLE
CEA-708 Korean

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#205]
We have a couple of Korean samples with CEA-708 captions. They are in the Korean708D directory in videos-repository.

Some info here:

http://www.tta.or.kr/English/new/standardization/eng_ttastddesc.jsp?stdno=TTAK.KO-08.0022/R1

You can download PDF file which describe CEA-708-D specification in Korean and partially English above.

Assigned to Oleg since he's in charge of completing 708 during GSOC.

**Comment by unicode45** [comment]
I've uploaded several Korean CC embeded TS files. Please check URL below.

https://drive.google.com/folderview?id=0B8AjqtxcLQDxflFNNnU2VnUxa0FucWMzZmFXSURtWFgwcEMwSUFCMDlMNHZ0bG5oOUZCeWc&usp=sharing

**Comment by unicode45** [comment]
Just added mp4 files with '_CC' suffix. You can check how CEA-708-D works with Korean CC.

**Comment by HaneolLee** [comment]
Hello.
HaneolLee of Korea

MBC broadcasting tests in Korea to CCextractor.

Test environment:
  1) Program: Brazil Capture Station
      http://www.redhenlab.org/home/the-cognitive-core-research-topics-in-red-hen/the-barnyard/brazilian-capture-station
  2) set up : 
     http://ccextractor.canihavesome.coffee/reports/119/Report__DTVCC_2015-10-12_220904.html


The test results of the attached file is a TS:
 - mbc_1. ts - OK (mbc_1.p1.svc01.txt)
 - mbc_2..ts - None extraction. 
   mbc_2. ts is used between the VANC No.7 ~ 14 times.

I would like to get the character extracting method of mbc_2.ts file.

Best wishes,

<download link>
(mbc_1.p1.svc01.txt)
https://drive.google.com/file/d/0B-hNVHLD60x1cFdFQTlUanVFcUk/view?usp=sharing

(mbc_1.ts)
https://drive.google.com/file/d/0B-hNVHLD60x1dHhrNzNVY1pJTjg/view?usp=sharing

(mbc_1.txt)
https://drive.google.com/file/d/0B-hNVHLD60x1Nkxkcm44Rk5iT0E/view?usp=sharing

(mbc_2.ts)
https://drive.google.com/file/d/0B-hNVHLD60x1TGdCQVhMLVo5TU0/view?usp=sharing

(mbc_2.txt)
https://drive.google.com/file/d/0B-hNVHLD60x1YnVadGJZSDhnMTQ/view?usp=sharing

**Comment by anshul1912** [comment]
File Does not exist any more

**Comment by HaneolLee** [comment]
check URL below.
(mbc_1.p1.svc01.txt)
https://drive.google.com/file/d/0BxFzM3fSXVOiWHpNT0dJR1RDU1U/view?usp=sharing

(mbc_1.ts)
https://drive.google.com/file/d/0BxFzM3fSXVOiV2FfelJGaTZkOFU/view?usp=sharing

(mbc_1.txt)
https://drive.google.com/file/d/0BxFzM3fSXVOiQk9CYnlYSi00SjA/view?usp=sharing

(mbc_2.ts)
https://drive.google.com/file/d/0BxFzM3fSXVOiRGRZSlcyUkxzUkE/view?usp=sharing

(mbc_2.txt)
https://drive.google.com/file/d/0BxFzM3fSXVOiRU44WU4xTE5IQ1E/view?usp=sharing

**Comment by HaneolLee** [comment]
I'm sorry. Upload again.

**Comment by HaneolLee** [comment]
I'm sorry. Upload again.

(mbc_1.p1.svc01.txt)
https://drive.google.com/file/d/0BxFzM3fSXVOiWHpNT0dJR1RDU1U/view?usp=sharing

(mbc_1.ts)
https://drive.google.com/file/d/0BxFzM3fSXVOiV2FfelJGaTZkOFU/view?usp=sharing

(mbc_1.txt)
https://drive.google.com/file/d/0BxFzM3fSXVOiQk9CYnlYSi00SjA/view?usp=sharing

(mbc_2.ts)
https://drive.google.com/file/d/0BxFzM3fSXVOiRGRZSlcyUkxzUkE/view?usp=sharing

(mbc_2.txt)
https://drive.google.com/file/d/0BxFzM3fSXVOiRU44WU4xTE5IQ1E/view?usp=sharing

**Comment by HaneolLee** [comment]
I'm sorry. Upload again.

(mbc_1.p1.svc01.txt)
https://drive.google.com/file/d/0BxFzM3fSXVOiWHpNT0dJR1RDU1U/view?usp=sharing

(mbc_1.ts)
https://drive.google.com/file/d/0BxFzM3fSXVOiV2FfelJGaTZkOFU/view?usp=sharing

(mbc_1.txt)
https://drive.google.com/file/d/0BxFzM3fSXVOiQk9CYnlYSi00SjA/view?usp=sharing

(mbc_2.ts)
https://drive.google.com/file/d/0BxFzM3fSXVOiRGRZSlcyUkxzUkE/view?usp=sharing

(mbc_2.txt)
https://drive.google.com/file/d/0BxFzM3fSXVOiRU44WU4xTE5IQ1E/view?usp=sharing

2016-01-07 19:07 GMT+09:00 Anshul Maheshwari <notifications@github.com>:

**Comment by bigharshrag** [comment]
Please check the files as they do not exist anymore. 
Can you please also elaborate on what problem you are facing during extraction?

**Comment by cfsmp3** [comment]
@HaneolLee Can you reply to @bigharshrag comment? We have a window to look into this now, but if we don't get some info (and files) in the next couple of weeks we'll close the ticket.

**Comment by unicode45** [comment]
It seems characters code is wrong in Korean subtitle on lastest version 0.85b.
CEA-708 Korean is written in EUC-KR, so you have to convert original EUC-KR to target encoding (except Latin1) before saving.
There’re no problems with opening subtitle with EUC-KR extracted by version 0.78 and 0.79, but something is wrong on ver. 0.85b.

**Comment by cfsmp3** [comment]
Closing this ticket because some files are missing - please create a new ticket with samples.

**Comment by MatejMecka** [comment]
Hi there!
I couldn't reproduce the issue.
Can you please tell me what command you used
Thanks
@unicode45 @bigharshrag @HaneolLee

**Comment by unicode45** [comment]
@MatejMecka 
Hi, 
It was solved by #690.
Thanks!
