### ISSUE TITLE
customtxt error crashes program

### ISSUE THREAD

**Issue by DHLgh** [CCExtractor/ccextractor#209]
I keep encountering an error message, randomly, when using the following options:

ccextractorwin "<input file>" -ttxt -nofc -noru -trim -customtxt 1110110 -o CCtemp.txt

It is the customtxt option that is causing the error - without it, the error does not occur. I would love to supply you with one of the files that is causing the error, however, they are very large in size - they range from 19 to 30 GB. I tried to snip a portion of one of the problem video files and after I did that, the error did not occur on the smaller portion where it originally occurred. Let me know if this is enough info, or if you would like me to place one of the culprit files on an FTP server for you to download.

There are two different errors I have encountered, one is below where the file does not open. This file has been Quick stream fixed with VideoReDo and in fact an MPEG2 TS type file even though it says MP4 below - that is incorrect.

ccextractorwin d:\WBBMHD-1258-1602_[QSF]_2015-08
-05_125800-160201.ts -ttxt -nofc -noru -trim -customtxt 1110110 -o CCtmp.txt
CCExtractor 0.77, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: d:\WBBMHD-1258-1602_[QSF]_2015-08-05_125800-160201.ts
[Extract: 1] [Stream mode: Autodetect]
[Program : 0 ] [Hauppage mode: No] [Use MythTV code: Auto]

[Timing mode: Auto] [Debug: No] [Buffer input: Yes]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .txt] [Encoding: UTF-8] [Delay: 0] [Trim lines: Yes]
[Add font color data: No] [Add font typesetting: Yes]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
Teletext page: [Autodetect]
Start credits text: [None]
Creating CCtmp.txt

-----------------------------------------------------------------

Opening file: d:\WBBMHD-1258-1602_[QSF]_2015-08-05_125800-160201.ts
Detected MP4 box with name: mdat
File seems to be a MP4
Analyzing data with GPAC (MP4 library)
opening 'd:\WBBMHD-1258-1602_[QSF]_2015-08-05_125800-160201.ts': [iso file] Read
 Box "..@." failed (Out Of Memory)
failed to open

Total frames time:        00:00:00:000  (0 frames at 29.97fps)
Done, processing time = 11 seconds
Performance (real length/process time) = 0.00
This is beta software. Report issues to carlos at ccextractor org...

Here is the other error I encounter, where it begins to process a file then crashes.

ccextractorwin d:\WMAQHD-0358-0702_[QSF]_2015-08
-02_035805-070206.ts -ttxt -nofc -noru -trim -customtxt 1110110 -o CCtmp.txt
CCExtractor 0.77, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: d:\WMAQHD-0358-0702_[QSF]_2015-08-02_035805-070206.ts
[Extract: 1] [Stream mode: Autodetect]
[Program : 0 ] [Hauppage mode: No] [Use MythTV code: Auto]

[Timing mode: Auto] [Debug: No] [Buffer input: Yes]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .txt] [Encoding: UTF-8] [Delay: 0] [Trim lines: Yes]
[Add font color data: No] [Add font typesetting: Yes]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
Teletext page: [Autodetect]
Start credits text: [None]
Creating CCtmp.txt

-----------------------------------------------------------------
Opening file: d:\WMAQHD-0358-0702_[QSF]_2015-08-02_035805-070206.ts
File seems to be a transport stream, enabling TS mode
Analyzing data in general mode
Decode captions from program 1 - MPEG-2 video stream [0x02]  -  PID: 81

New video information found
[1920 * 1080] [AR: 03 - 16:9] [FR: 04 - 29.97] [progressive: no]

XDS: ContentAdvisory: US TV Parental Guidelines. Age Rating: TV-G (General Audie
nce)
XDS:
XDS Notice: Program is now Women of Power
  4%  |  07:12

AT THIS POINT THE PROGRAM CRASHES

Here are the details of the error message (probably not very helpful):

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	ccextractorwin.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5585958f
  Fault Module Name:	ccextractorwin.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	5585958f
  Exception Code:	c0000005
  Exception Offset:	00013643
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Here is the same type of error message when processing a different file on a different computer with the previous version of ccextractorwin.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	ccextractorwin.exe
  Application Version:	0.0.0.0
  Application Timestamp:	54b76c40
  Fault Module Name:	ccextractorwin.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	54b76c40
  Exception Code:	c0000005
  Exception Offset:	00013413
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by canihavesomecoffee** [comment]
Hey @DHLgh, bandwidth/file size is no issue... Could you please upload a sample and let me know where I can obtain it?

**Comment by cfsmp3** [comment]
Closing due to lack of sample. Please reopen when a sample is made available.
