### ISSUE TITLE
MAXBFRAMES undeclared,  I can't build for Linux 

### ISSUE THREAD

**Issue by scramatte** [CCExtractor/ccextractor#221]
```
../src/lib_ccx/avc_functions.c: In function ‘slice_header’:
../src/lib_ccx/avc_functions.c:1097:23: error: ‘MAXBFRAMES’ undeclared (first use in this function)
   if (abs(curridx) >= MAXBFRAMES) {
                       ^
../src/lib_ccx/avc_functions.c:1097:23: note: each undeclared identifier is reported only once for each function it appears in
make: *** [objs/avc_functions.o] Error 1
```

**Comment by canihavesomecoffee** [comment]
Hello,

is this happening with the current github or with a certain CCExtractor version obtained through Sourceforge?

**Comment by anshul1912** [comment]
MAXBFRAME is defined in ccx_decoders_structs.h
avc_functions.c includes lib_ccx.h
lib_ccx.h includes ccx_decoders_608.h
ccx_decoders_608.h includes ccx_decoders_structs.h

and just now mainstream of git is broken, @scramatte  please download newer git version by tomorrow :)

**Comment by cfsmp3** [comment]
Forgot to push the last PR.

All OK now?
