### ISSUE TITLE
Endless loop in a .mov file (GPAC related)

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#225]
It's been reported that this file (video-samples repo):
EndLess\ Loop/dvcprohd_fw_capture.mov
Causes CCExtractor to go into an endless loop.

**Comment by anshul1912** [comment]
Testing file on local machine

**Comment by anshul1912** [comment]
I received seg fault with that sample,  trak->Media->information->sampleTable->SampleDescription is NULL 
Program received signal SIGSEGV, Segmentation fault.
0x0000000000499f27 in gf_isom_check_sample_desc (trak=0x7b5620) at ../src/gpacmp4/box_code_base.c:6162
6162            while ((a = (GF_UnknownBox*)gf_list_enum(trak->Media->information->sampleTable->SampleDescription->boxList, &i))) {

**Comment by anshul1912** [comment]
can be closed, avoided  endless loop and seg-fault but correct solution can only be implemented by upgrading for new gpac or modifying gpac code

**Comment by cfsmp3** [comment]
Let's keep it open just as a reminder that we should upgrade gpac :-)

**Comment by cfsmp3** [comment]
Direct link:
https://drive.google.com/open?id=0B_61ywKPmI0Tckc0RUUxZjcwVjA
