### ISSUE TITLE
-s option fails to keep updating on .wtv file (on Windows)

### ISSUE THREAD

**Issue by alastaircoote** [CCExtractor/ccextractor#236]
I'm trying to pipe Windows Media Center recordings through ccextractor to get the subtitles out in near-realtime. It's finding the subtitles and extracting them just fine, but the `-s` option doesn't appear to be working - it grabs all the subtitles up until a certain point then stops. If I add a number afterwards (i.e. `-s 10` it will close after 10 seconds, as if it has no new data - but the recording is definitely still going, and the file keeps growing. If I run it again, it'll grab new subtitles since the last time it was run, then freeze again.

I'm honestly not sure where to even start debugging here but any tips would be appreciated!

**Comment by anshul1912** [comment]
1. Can you elaborate your problem?
2. Are you working on linux or windows?
3. In your report at one moment you say that you are using pipe `I'm trying to pipe` at other moment you say that you are using file `file keeps growing`,

**Comment by alastaircoote** [comment]
It turns out that I am an idiot. What I didn't notice was that Windows Media Center actually preallocates ~500MB to the recording file as soon as it starts - then growing it in 500MB increments as required. This means that the streaming mode of ccextractor fails, as it immediately parses the whole file, then waits for it to grow beyond 500MB.

I have a rudimentary script set up that is watching the .wtv file and copying segments as they are changed - it's not too reliable, but ccextractor seems to work with it. So, not ccextractor's fault, but maybe it was worth creating this issue just in case someone else runs into the same issue in the future.
