### ISSUE TITLE
Danish subtitles

### ISSUE THREAD

**Issue by 33ms** [CCExtractor/ccextractor#242]
How to extract subtitles from files recorded with Hauppauge WinTV 8. I use CCExtractor GUI 0.77.?

File: https://www.dropbox.com/s/4su7f8qitq2qcd3/Byen_set_indefra.zip?dl=0

**Comment by 33ms** [comment]
I will try later

**Comment by anshul1912** [comment]
Sorry for too late reply, but if you had elaborated your question and Issue you could have attracted much more support.
how to extract does not tell what you have tried so far and where you are stuck.
