### ISSUE TITLE
CCExtractor produces only "Illegal XDS Data", VLC shows proper subtitles.

### ISSUE THREAD

**Issue by arantius** [CCExtractor/ccextractor#244]
The file linked below is the first 20 MB of a TS MPEG captured via TiVo.  When running CCExtractor (0.77) I only get:

    ...
    Note: Illegal XDS data
    Note: Illegal XDS data
    Note: Illegal XDS dataPremature end of file!

(and a zero byte SRT) But playing the same file with VLC successfully decodes and displays the captions.

https://drive.google.com/file/d/0B3bPKNXgZu0-b1ZXTlU4b3Y3d1U/view

**Comment by anshul1912** [comment]
Yes, I checked it also works with FFMpeg with this command: ffmpeg -f lavfi -i "movie=/home/kiran/Videos/test.mpg[out0+subcc]" a.srt

**Comment by anshul1912** [comment]
subtitles are there in channel 2, so -2 option works. but lot of garbage with actual data

**Comment by cfsmp3** [comment]
I suspect our Tivo support is just broken. It worked a long time ago but
probably Tivo has changed things.

**Comment by anshul1912** [comment]
if we this hack in store_hdcc function, this video produce correct output

 27     if(cc_data[0] == 0x05)
 28         return;

Now I am looking, why this incorrect data is like coming from mpeg user data

**Comment by anshul1912** [comment]
Looking at difference between user_data function of ccextrcator and mpeg_decode_user_data
