### ISSUE TITLE
ccextractor --help

### ISSUE THREAD

**Issue by Liontooth** [CCExtractor/ccextractor#246]
This is a feature request. Currently, you get the full help screen if you leave out any parameters, ending with the message "Error: (This help screen was shown because there were no input files)."

That's fine, but please add the standard ways to access the help screen:

```
# ccextractor --help
Error: Error: Parameter --help not understood.

# ccextractor -h
Error: Error: Parameter -h not understood.
```

It would also be extremely useful if you could add a man page, even if it's just the same content initially.

Cheers,
David

**Comment by anshul1912** [comment]
Added -h and --help optios, can be closed now
