### ISSUE TITLE
> saved as &gt; in teletext-subs saved with color-information

### ISSUE THREAD

**Issue by hurda** [CCExtractor/ccextractor#248]
CCExtractor 0.77 and git-677fee4 
File: http://www.mediafire.com/download/uryjrncc88747mr/great-than-sign.7z (30MB)

Without color-information
```
1
00:00:01,080 --> 00:00:02,720
>Überhaupt nicht.

2
00:00:02,880 --> 00:00:04,200
Warum?
```

With color information:
```
1
00:00:01,080 --> 00:00:02,720
&gt;Überhaupt nicht.

2
00:00:02,880 --> 00:00:04,200
<font color="#ffff00">Warum?</font>
```

Probably due to https://github.com/CCExtractor/ccextractor/blob/763972ca4b541a4890304130f03e1616c0ea661a/src/lib_ccx/telxcc.c#L173

I'm reporting this as e.g. MPC-HC and WDTV Media Player set-topbox are showing `&gt;` as-is and not as `>`.

**Comment by canihavesomecoffee** [comment]
Yeah, you're right that it's most likely caused by that conversion table. The question is however, in how far this is posing an issue... Looks like it's been in there since the initial git, so maybe @cfsmp3 can give some insight why it's in there :)

**Comment by hurda** [comment]
Unfortunately petrkutalek removed the original repo, and thus the commit-history.

But I hunted down a fork of the original repo, and I found the reason for this conversion: searchengine-mode.
https://github.com/pude/telxcc/commit/d69494053759b93e20979d4b59d74a63b023884e

Is that relevant when the subtitle-files aren't being indexed and only used with mediaplayers?

**Comment by cfsmp3** [comment]
Probably we should make the escaping optional, in general. But not for
0.78, maybe as a 0.79 goal :-)

**Comment by anshul1912** [comment]
just now excapting unsafe characters is only there for teletext, I think we should make it for every input, and optional for every input.

by every Input I mean teletext, dvbsub, 608, 708, ISDB

**Comment by anshul1912** [comment]
Added --nohtmlescape option which dont allow to convert > to &gt and other characters like &lt &amp
