### ISSUE TITLE
Time Adjust BUG when creating a NEGATIVE value for timecode offset

### ISSUE THREAD

**Issue by MediaMan2000** [CCExtractor/ccextractor#250]
However using both the command line or GUI the timke adjust does not seem to
> work when using "-" a negative value. For example. adding 4000ms works fine.
> The timecode adjusts accordingly. However adding -4000...the timecode has a
> bug and the time adjust incorrectly actually adding time.
>
> In any case it seems this feature does not work for anything beyond say
> -1000ms

We are in fact working with SCC files. The extractor works great and extracts this data as normal. We export the RAW data offered in your system, and then convert using SCC tools command line to an SCC file. But the need to offset is becoming a requirement as well. So if we could work with you in any way to assist or resolve this please let us know. If it could shift -4000ms as well as it shifts forward 4000ms then we would be set !

![negative_adjust_4sec_error](https://cloud.githubusercontent.com/assets/15917348/11259861/95d9a50c-8eb9-11e5-94ea-a4c0d657c4e7.PNG)
![original_extract](https://cloud.githubusercontent.com/assets/15917348/11259860/95d8a918-8eb9-11e5-945c-08195ce73404.PNG)

**Comment by MediaMan2000** [comment]
If this is in any way a moderate to minor bug fix, please let us know how we can help. Is there a release coming up perhaps that this could be bundle in with ?  Thanks

**Comment by MediaMan2000** [comment]
Also can we confirm if this works with exporting a .RAW file ?   Many thanks !

**Comment by MediaMan2000** [comment]
Time adjust seems to work in the latest version of the command code. However the RAW does not support adding a negative value. This may be extra data from the original file. For instance this file had a PAINT ON 9429 command and CLEAR SELECTION 942c  command. This adds 00:00:00:00 timecode at the head. And the offset cannot understand   -0

**Comment by anshul1912** [comment]
can you share your video file, and output of ccextractor

**Comment by MediaMan2000** [comment]
It's any file. Carlos explained that padding is added to the start of a RAW file because there is no TC reference as it uses blocks of code. It works for SRT which is fine. We have come up with another solution using the tool. So all good.
