### ISSUE TITLE
Extract raw file getting different results per file 

### ISSUE THREAD

**Issue by MediaMan2000** [CCExtractor/ccextractor#253]
Extracting .raw 608 data from captioned file. getting mixed results from media. Given the files are from different providers but the raw data does not seem right.

Files attached. Raw2 is just a visual indication of the file that works. 
Raw2 is a file which does in fact extract captioning data. However when the file is converted to SCC and attached to the media, the captions display back to back within seconds. In short all the timing is messed up.

Just curious why the timing would be affected. 

Also note we are using a START time via cc extractor. Again this works perfectly for some files and with others the captions just spit out one after the other and the timing is wrong.

![raw2](https://cloud.githubusercontent.com/assets/15917348/11415538/6ab1a2ae-9458-11e5-8df3-c60947822b32.JPG)
![raw1](https://cloud.githubusercontent.com/assets/15917348/11415537/6aaf8d34-9458-11e5-83a5-7df4827cb188.JPG)

![raw2](https://cloud.githubusercontent.com/assets/15917348/11415532/5d6f1450-9458-11e5-8445-472062a59acf.JPG)
![raw1](https://cloud.githubusercontent.com/assets/15917348/11415531/5d6f00dc-9458-11e5-8157-57e6eb10fba0.JPG)

**Comment by canihavesomecoffee** [comment]
@MediaMan2000 Does this still occur with 0.80? If so, could you provide us with some samples please?

**Comment by cfsmp3** [comment]
Closing since original poster doesn't reply. @MediaMan2000 feel free to reopen if needed.
