### ISSUE TITLE
SRT convert to SCC unable to handle the MUSIC symbol and fails 

### ISSUE THREAD

**Issue by MediaMan2000** [CCExtractor/ccextractor#254]
The SRT extract is great. However whenever we get a file with one of those stupid MUSIC symbols we are unable to convert SRT to SCC. SCC does not recognize it and comes up with an error. Unrecognized symbol. 

To be honest this tool works perfect for every file. Except when it has the music symbol or character that does not quite fall under standard alphanumeric. I know this is because we are converting to SCC which has a specific limited character set. 

Is there anyway in the world to remove or filter out unwanted characters. Namely removing the music symbol etc.

**Comment by cfsmp3** [comment]
This isn't a CCExtractor bug I'm afraid. Post processing should be done by a separate tool.
