### ISSUE TITLE
Move ccextractor out of sourceforge

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#256]
Looks like sourceforge is starting to do bad things to installers...

**Comment by grave-w-grave** [comment]
Github (probably) has a releases function that should let you put up the downloads you currently have on sourceforge.

**Comment by MatejMecka** [comment]
@cfsmp3 I did the migration but sadly you rejected it #455

**Comment by canihavesomecoffee** [comment]
With an empty pull request?

**Comment by cfsmp3** [comment]
#455 contains nothing :-)

**Comment by gautamchitnis** [comment]
Valid for GSoC points? If so, how many points?

**Comment by cfsmp3** [comment]
Missing here:
- Redirect from sourceforge to github (edit sourceforge page)
- Remove all links to sourceforge from everywhere

**Comment by MatejMecka** [comment]
@cfsmp3 since I can't modify the pages directly to ccextractor.org but I found the pages containing sourceforge.

https://www.ccextractor.org/public:general:http:sourceforge.net_donate_index.php
https://www.ccextractor.org/public:general:downloads
https://www.ccextractor.org/public:gsoc:translating_captions?s[]=sourceforge

**Comment by MatejMecka** [comment]
To redirect to sourceforge you can probably attach a php or html block that does the job.

```
<?php
/* Redirect browser */
header("Location: https://github.com/ccextractor/ccextractor");
/* Make sure that code below does not get executed when we redirect. */
exit;
?>
```

or

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
    <head>
    <title>Redirect</title>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <!--Redirect browser, 1 indicates number of seconds before redirect-->
    <meta http-equiv="refresh" content="1;URL=https://github.com/ccextractor/ccextractor">
    </head>
    <body>
        <p>Redirecting to: <a href="http://example.com">https://github.com/ccextractor/ccextractor</a></p>
    </body>
</html>
```

**Comment by cfsmp3** [comment]
Closing, I think this is done already completely.
