### ISSUE TITLE
Fail to build missing enc_ctx declaration

### ISSUE THREAD

**Issue by marillat** [CCExtractor/ccextractor#258]
Hi,

0.78 fail to build under Linux (Debian unstable) build with ENABLE_FFMPEG=yes ENABLE_OCR=yes

```
../src/ccextractor.c: In function ‘main’:
../src/ccextractor.c:107:30: error: ‘struct lib_ccx_ctx’ has no member named ‘buffer’
     unsigned char *bptr = ctx->buffer;
                              ^
../src/ccextractor.c:129:17: error: ‘enc_ctx’ undeclared (first use in this function)
      encode_sub(enc_ctx, &dec_ctx->dec_sub);
```

**Comment by anshul1912** [comment]
Its  look like it is because of ffmpeg, which version of ffmpeg are you using

**Comment by marillat** [comment]
2.8.3 from Debian unstable

**Comment by anshul1912** [comment]
Thanks i will test it

**Comment by canihavesomecoffee** [comment]
@marillat Could you test again with the current 0.80 version and report back if this is solved for you?

**Comment by marillat** [comment]
Build fine ffmpeg 3.0.2
Thanks.
