### ISSUE TITLE
Caption Data Not Found

### ISSUE THREAD

**Issue by pvcflyer** [CCExtractor/ccextractor#259]
I have put together a small dropbox folder of video files that ccextractor cannot extract the closed captions from, but are displayed in quicktime.  Included in the folder is a file that ccextractor was successful with that ran through the same process for comparison.

https://www.dropbox.com/sh/btpispaw5p4t75p/AABQvS85bTxxys8BR4AlWnRRa?lst

Hopefully, there is a solution to this issue.

Also, please let me know if there is a better way to get you these files for reference.

Thanks in advance for your time,

PC

**Comment by rkuchumov** [comment]
@pvcflyer Sorry for late reply. Could you please update dropbox folder? I get 404.

**Comment by pvcflyer** [comment]
Reshared the dropbox folder:

https://www.dropbox.com/sh/jisb5q0r3h8m7mn/AABo9rIPH9VjJviGwhdxZHqBa?dl=0

PC
