### ISSUE TITLE
<CEA-708 CEA-708>  I need help.

### ISSUE THREAD

**Issue by HaneolLee** [CCExtractor/ccextractor#268]
Test environment:
-ccextractor 0.79 GUI

Test conducted under the caption in Korea.
The event of two issues.
1st. Captions will not be extracted
2nd . Caption, repeats itself.

1.st
mbc_1.ts  - success
-mbc_1.ts file
https://drive.google.com/file/d/0BxFzM3fSXVOiV2FfelJGaTZkOFU/view?usp=sharing

-activity
https://drive.google.com/file/d/0BxFzM3fSXVOiU1U3Y2tCYWZxQjQ/view?usp=sharing
https://drive.google.com/file/d/0BxFzM3fSXVOiN3Btam10RXExZ1k/view?usp=sharing

mbc_2.ts  - Failed
-mbc_2.ts file
https://drive.google.com/file/d/0BxFzM3fSXVOiRGRZSlcyUkxzUkE/view?usp=sharing

-activity
https://drive.google.com/file/d/0BxFzM3fSXVOiNmZwQ2VEX1dhek0/view?usp=sharing
https://drive.google.com/file/d/0BxFzM3fSXVOidk9KRDhDeDBWcTQ/view?usp=sharing

Why am I failed to know whether mbc_2.ts files.
A test, please.

2nd
Same thing is be repeated.

-G1.ts file
https://drive.google.com/file/d/0BxFzM3fSXVOiTU5PUjFjM1pyb0k/view?usp=sharing

-ccextractor 0.79 GUI - setting 
https://drive.google.com/file/d/0BxFzM3fSXVOiWGVGZFZyd2g1LVk/view?usp=sharing
https://drive.google.com/file/d/0BxFzM3fSXVOiNEplYXVLemJNUms/view?usp=sharing
https://drive.google.com/file/d/0BxFzM3fSXVOiRGI4cVgtM2RzMDA/view?usp=sharing
https://drive.google.com/file/d/0BxFzM3fSXVOibEMtcFRxSWxmUXc/view?usp=sharing
https://drive.google.com/file/d/0BxFzM3fSXVOiOWJzZ2Z2N3NiYVk/view?usp=sharing

-Result
https://drive.google.com/file/d/0BxFzM3fSXVOiMTY5Q3BWSTdRWE0/view?usp=sharing

What is the result with handwriting is be repeated.
I wonder if there's a way done.
Thank you.

**Comment by canihavesomecoffee** [comment]
Hello,

could you try it again without the rollup captions enabled? This should most likely be what's causing the duplication...

**Comment by HaneolLee** [comment]
I had to changes of options for to rollup.
Result is link. below.

-Output(2)_1
https://drive.google.com/file/d/0BxFzM3fSXVOiTXBhRVNJREIyTWc/view?usp=sharing
https://drive.google.com/file/d/0BxFzM3fSXVOibVhTZDFNcnpJbWs/view?usp=sharing

-Output(2)_2
https://drive.google.com/file/d/0BxFzM3fSXVOiZ0Fuei0wOWl6Y2c/view?usp=sharing
https://drive.google.com/file/d/0BxFzM3fSXVOiaUYyaWZYWTMtWHM/view?usp=sharing

-Output(2)_3
https://drive.google.com/file/d/0BxFzM3fSXVOiZUtTeUY0bmRPVVE/view?usp=sharing
https://drive.google.com/file/d/0BxFzM3fSXVOicG00ZU1UdGJHYmM/view?usp=sharing

Result
A little different but repeated unchanged.

**Comment by canihavesomecoffee** [comment]
Hello,

I've spent a bit of time, and I can confirm both bugs. Could you open up a new issue for the file which is not generating (and rename this one to "CEA-708 duplicate lines")? It's easier to keep track of one issue at a time :)

Now, concerning the line duplication:

I've noticed both samples are from a news broadcast. Is roll-up being used (live captioning)? Would it be possible to test on captions from another program to see if the duplication occurs there too, or if it's limited to the news broadcasts only?

**Comment by cfsmp3** [comment]
@HaneolLee can you reply to @canihavesomecoffee comment? We have a window to work on this but we need updated info - otherwise we'll close the ticket in a 2 weeks.

**Comment by cfsmp3** [comment]
Closed due to inactivity. OP feel free to reopen when/if you are available for follow up.
