### ISSUE TITLE
Garbaled Output with with dsc.ts

### ISSUE THREAD

**Issue by anshul1912** [CCExtractor/ccextractor#269]
There was regression failure with dsc.ts.
Willem nailed the commit https://github.com/CCExtractor/ccextractor/commit/169a39eb3edeed72952850d956b4ee247ade24b7

**Comment by abhishek-vinjamoori** [comment]
Could you please elaborate on the issue and point out where dcs.ts is ?

**Comment by canihavesomecoffee** [comment]
dcs.ts is file nr. 22 in the General test file. See slack for a download link :)

**Comment by vinayakathavale** [comment]
File works fine for me [output](http://pastebin.com/xgfc2m0S)

**Comment by abhishek-vinjamoori** [comment]
Yes. It works for me well too on Linux. But there is bad spacing in the output and there are a couple of" PTS DELAYS " during processing.
