### ISSUE TITLE
MPEG2 Transport streams no longer processed

### ISSUE THREAD

**Issue by workflowsguy** [CCExtractor/ccextractor#270]
When trying to open MPEG2 Transport stream files, ccextractor now fails with "Unable to open" & error code 6.

By comparison, telxcc has no problem extracting teletext subtitles from such a file.

CCExtractor 0.78 CLI installed on OS X through Homebrew.

**Comment by canihavesomecoffee** [comment]
Hello,

could you try running .80, which is the latest version released a week ago?

**Comment by workflowsguy** [comment]
I do not know how to build ccextractor, so I will have to wait until the version becomes available through Homebrew on the Mac. Then I can try it out.

**Comment by canihavesomecoffee** [comment]
I don't own a mac myself, but from what I see in the [mac](https://github.com/CCExtractor/ccextractor/tree/master/mac) folder of the repository, all you need to do is perform these steps: 

* install the [Apple Developer Tools](http://developer.apple.com/technologies/tools/)
* download the latest [0.79 source files](http://sourceforge.net/projects/ccextractor/files/ccextractor/0.79/ccextractor.src.0.79.zip/download) from SourceForge
* extract the zip
* open the terminal
* navigate to the mac folder of the extracted folder (e.g. ``cd ~/Downloads/ccextractor0.79/mac``)
* run the command which should compile ccextractor for you (``./build.command``)

If all goes well and there are no errors, you should have a ccextractor executable in the same folder. If an error occurs, it would be nice if you could open a new issue for this, so we can update the mac build command (as @cfsmp3 noted, none of us contributors owns a mac, so we can't test it every time we release unfortunately).

If you don't want to do this, would it be possible to make a small sample available, so we can test it on Linux with the current version (and with 0.78 as well) to confirm the issue?

**Comment by workflowsguy** [comment]
Thanks for the instructions,

unfortunately it fails to build on my Mac, so I have created a new issue as per your suggestion.

**Comment by workflowsguy** [comment]
I have tested this with a build of 0.79. However, it still produces the error message

```
Unable to open 


Error: Failed to determine total file size.

6

```

**Comment by cfsmp3** [comment]
That means it can't find or open the input file.

**Comment by workflowsguy** [comment]
Sorry, this was caused by an error in my extraction script.

However, it would be great if in the case of such an error the name of the file were listed.
I mistakenly thought that CCExtractor could not open the video file; instead the path to the srt file to be created was incorrect.
With a more verbose error message, I would have spotted my error immediately.

**Comment by cfsmp3** [comment]
Solved in current github, please reopen if a new sample that fails proper detection appears
