### ISSUE TITLE
CCExtractor 0.79 fails to build on OS X

### ISSUE THREAD

**Issue by workflowsguy** [CCExtractor/ccextractor#271]
When trying to build CCextractor from Source, besides issuing several warnings, it fails with

```
ld: library not found for -liconv
clang: error: linker command failed with exit code 1 (use -v to see invocation)
: command not foundne 2: 
```

Building on OS X 10.9.5 with Xcode 6 Command line tools (Apple LLVM version 6.0 (clang-600.0.57)

**Comment by canihavesomecoffee** [comment]
Hello,

could you verify if liconv is installed? Please post the output of ``mdfind -name libiconv | sort`` here, so we can help you further.

The warnings are quite normal, they appear almost every time.

**Comment by workflowsguy** [comment]
Here is the output from mdfind:

```
/usr/include/php/ext/iconv/php_have_libiconv.h
/usr/include/php/ext/iconv/php_iconv_aliased_libiconv.h
/usr/lib/libiconv.2.dylib
/usr/local/Cellar/pdftk/2.02/lib/libiconv.2.dylib

```

**Comment by canihavesomecoffee** [comment]
Could you try to add this to the end of the gcc command inside the .command file? ``-L/usr/lib``

Then you'd get this:

```
gcc -std=gnu99 -Wno-write-strings -DGPAC_CONFIG_DARWIN -D_FILE_OFFSET_BITS=64 -Dfopen64=fopen -Dopen64=open -Dlseek64=lseek -I ../src/gpacmp4 -I ../src/lib_ccx -I ../src/libpng -I ../src/zlib -o ccextractor $(find ../src/ -name '*.cpp' \! -name 'win_*') $(find ../src/ -name '*.c' \! -name 'win_*') -liconv -L/usr/lib
```

**Comment by workflowsguy** [comment]
OK,

with the modified command line, a ccextractor binary is built, albeit with the following warning:

`'d: warning: directory not found for option '-L/usr/lib
: command not foundne 2: 
`

**Comment by iha** [comment]
I got a lot of warnings, but ccextractor was builded in El Capitan.

**Comment by cfsmp3** [comment]
Are there warnings that don't relate to code itself? (such as the
-L/usr/lib one)
If yes we should solve those and have a clean build if at all possible.

**Comment by iha** [comment]
There are many implicit conversions like char * to unsigned char * for example, and comparisons always true or false. 

Follows the  gcc output warnings.

[gcc.log.zip](https://github.com/CCExtractor/ccextractor/files/164855/gcc.log.zip)

**Comment by cfsmp3** [comment]
Some of them are quite useful.

On Wed, Mar 9, 2016 at 10:42 AM, Vitor Massaru Iha <notifications@github.com

**Comment by barun511** [comment]
The build seems to work fine for me. I did have a libiconv issue, but that was due to conflicting macports and mac installations...removing macports and switching to homebrew fixed it for me, and the compilation went through smoothly.

**Comment by cfsmp3** [comment]
Current github confirmed working, reopen if/when it breaks again
