### ISSUE TITLE
Output broken in -ucla 

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#282]
The second column of timestamps is wrong:

20160211030008.556|20620323060011.657|CC1|>>> THAT DOES IT FOR US.
20160211030009.724|20620323060012.792|CC1|THANKS FOR WATCHING.
20160211030010.858|20620323060014.794|CC1|WE'LL SEE YOU TOMORROW NIGHT AT
20160211030012.860|20620323060015.227|CC1|8:00.
20160211030013.294|20620323060016.529|CC1|AND RIGHT AFTER THE DEMOCRATIC
20160211030014.595|20620323060017.863|CC1|DEBATE IN MILWAUKEE WITH THE
20160211030015.930|20620323060020.633|CC1|BEST CONVERSATION IN POLITICS.

Here's 0.74:

20160211030008.506|20160211030009.607|CC1|>>> THAT DOES IT FOR US.
20160211030009.674|20160211030010.742|CC1|THANKS FOR WATCHING.
20160211030010.808|20160211030012.744|CC1|WE'LL SEE YOU TOMORROW NIGHT AT
20160211030012.810|20160211030013.177|CC1|8:00.
20160211030013.244|20160211030014.479|CC1|AND RIGHT AFTER THE DEMOCRATIC
20160211030014.545|20160211030015.813|CC1|DEBATE IN MILWAUKEE WITH THE
20160211030015.880|20160211030018.583|CC1|BEST CONVERSATION IN POLITICS.

**Comment by littleredhen** [comment]
The wrong dates (2062-03-23 06:00:11 instead of 2016-02-11 03:00:09) is produced by github master 2016-02-10. In unix seconds, that's 2910319211 instead of 1455159609, or off by 1455159602, which is Thu Feb 11 03:00:02 UTC 2016, the start of the recording.

It looks like the second column of timestamps is just adding the base time twice.

**Comment by Abhinav95** [comment]
Pull request #332 

The command I am running is:-
$ ccextractor -out=ttxt -delay 1423621560000 2015-02-11_0226_US_CNN_TEST.mpg -ucla
The delay is the UNIX timestamp of the time of recording of the file.

The old output looks like:-

20150211022600.600|20600323045202.802|CC1|RU2|YOUR ENEMIES CLOSER.
20150211022602.869|20600323045205.672|CC1|RU2|>> PATRICK AND GINA KEPT
20150211022605.739|20600323045206.506|CC1|RU2|DIGGING.
20150211022606.573|20600323045207.941|CC1|RU2|BUT FOR THE SAN DIEGO SHERIFF'S
20150211022608.008|20600323045210.677|CC1|RU2|DEPARTMENT, THE CASE HAD GONE
20150211022610.744|20600323045210.877|CC1|RU2|COLD.
20150211022610.944|20600323045211.945|CC1|RU2|>> IT'S ALMOST IMPOSSIBLE TO
20150211022612.012|20600323045214.347|CC1|RU2|WORK A CASE WITHOUT INFORMATION
20150211022614.414|20600323045215.315|CC1|RU2|FLOWING IN.
20150211022615.382|20600323045217.984|CC1|RU2|>> NO LEADS, NO ANSWERS TO WHAT
20150211022618.051|20600323045220.320|CC1|RU2|HAPPENED TO THIS LOVING, HAPPY
20150211022620.387|20600323045227.394|CC1|RU2|FAMILY OF FOUR.
20150211022627.460|20600323045230.964|CC1|RU2|BUT THAT CHANGED ON NOVEMBER 11,
20150211022631.031|20600323045231.264|CC1|RU2|2013.
<snipped for brevity>

The newer(correct) output looks like:-

20150211022600.600|20150211022602.802|CC1|RU2|YOUR ENEMIES CLOSER.
20150211022602.869|20150211022605.672|CC1|RU2|>> PATRICK AND GINA KEPT
20150211022605.739|20150211022606.506|CC1|RU2|DIGGING.
20150211022606.573|20150211022607.941|CC1|RU2|BUT FOR THE SAN DIEGO SHERIFF'S
20150211022608.008|20150211022610.677|CC1|RU2|DEPARTMENT, THE CASE HAD GONE
20150211022610.744|20150211022610.877|CC1|RU2|COLD.
20150211022610.944|20150211022611.945|CC1|RU2|>> IT'S ALMOST IMPOSSIBLE TO
20150211022612.012|20150211022614.347|CC1|RU2|WORK A CASE WITHOUT INFORMATION
20150211022614.414|20150211022615.315|CC1|RU2|FLOWING IN.
20150211022615.382|20150211022617.984|CC1|RU2|>> NO LEADS, NO ANSWERS TO WHAT
20150211022618.051|20150211022620.320|CC1|RU2|HAPPENED TO THIS LOVING, HAPPY
20150211022620.387|20150211022627.394|CC1|RU2|FAMILY OF FOUR.
20150211022627.460|20150211022630.964|CC1|RU2|BUT THAT CHANGED ON NOVEMBER 11,
20150211022631.031|20150211022631.264|CC1|RU2|2013.
<snipped for brevity>

I have shown the output for the file http://babylon.library.ucla.edu/redhen/GSoC/sample-1min-raw/2015-02-11_0226_US_CNN_TEST.mpg

**Comment by cfsmp3** [comment]
Seems solved
