### ISSUE TITLE
Cyrilic support. Missing or broken.

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#283]
When processing a Russian TV capture we're getting Western characters instead of Cyrillic. I see we need Cyrillic G0 Primary Set - Option 2 - Russian/Bulgarian -- how does that get turned on?

The first test file is available here:

http://vrnewsscape.ucla.edu/dropbox/2016-02-09_1800_RU_TVC_Test.mpg
http://vrnewsscape.ucla.edu/dropbox/2016-02-09_1800_RU_TVC_Test.txt

VLC plays the teletext just fine
![cyrilic1](https://cloud.githubusercontent.com/assets/5949913/13196200/03c11a94-d7c8-11e5-8a76-0c0273281e34.png)
![cyrilic2](https://cloud.githubusercontent.com/assets/5949913/13196201/0a7470a2-d7c8-11e5-9d3a-28b82e075bde.png)

**Comment by bigharshrag** [comment]
There is no support yet for Greek, Arabic, and Hebrew as well as for accented character sets (G2 character sets) for languages other than Latin bases ones.
I'd be willing to add the support but I do not have any test files for the same.

**Comment by bigharshrag** [comment]
There is no support yet for Greek, Arabic, and Hebrew as well as for accented character sets (G2 character sets) for languages other than Latin based ones.
I'd be willing to add the support but I do not have any test files for the same.

**Comment by cfsmp3** [comment]
I don't think have any of those either, but we'll try to find some.

Are you applying to GSoC?

**Comment by bigharshrag** [comment]
Yes, I am indeed applying for GSoC.
Do I go ahead and try and add the above mentioned support for character sets without the files to test on?

**Comment by cfsmp3** [comment]
Sure, it's better to have theoretical implementations than nothing :-) That
way when we actually get samples we'll have a good starting point.

**Comment by littleredhen** [comment]
The patch looks like it's working perfectly for Russian TVC -- I'm just waiting to get that confirmed by a native speaker. The other russian channel we sampled is 1TV, and we're still getting Latin1. Please see http://vrnewsscape.ucla.edu/dropbox/2016-02-09_1900_RU_1TV_Test.mpg

**Comment by bigharshrag** [comment]
@littleredhen Could you please tell me if a video player like VLC produces the correct subtitles? I could not get VLC to do so.

**Comment by abhishek-vinjamoori** [comment]
@bigharshrag . Please check my comment for your PR.

**Comment by littleredhen** [comment]
I haven't had a chance to play this file in VLC, but I can confirm that CCExtractor is able to extract text from the file. However, this text is still in a Latin character set. Are you not able to get text out with CCExtractor?

**Comment by abhishek-vinjamoori** [comment]
@littleredhen, this issue has been updated today again with bug fixes. Please check if latest code is being used.

**Comment by bigharshrag** [comment]
@littleredhen I can confirm that CCExtractor does extract subtitles for the file and they are indeed using Latin character set. I have looked into the file provided and I found that it does not actually send the packet that would tell CCExtractor what character set to use for the file(the X/28 or M/29 packet). Hence CCExtractor resorts to default character set of Latin (as specified by the ETS 300 706 documentation as the default character set in such a scenario). The TVC file provided earlier had this data. 

Hence I was wondering if you could in fact get any video player to display correct subtitle files in Cyrillic script. 

Also the new bug fixes don't fix this problem.
