### ISSUE TITLE
ccextractor segfaults when decoding CC using -sc when a blank line is encountered

### ISSUE THREAD

**Issue by jimmyoh** [CCExtractor/ccextractor#288]
Hello,

I am using ccextractor to decode Closed caption from live TV streams.
US ATSC live TV.
When I use -sc (Sentence Capitalisation)
ccextractor segfaults with code 139 
if it encounters a blank line in the closed captioning.

**decoded with -sc**
330
00:17:26,880 --> 00:17:29,113
                        Uh...   

331
00:17:29,182 --> 00:17:32,116
                    (<i>mumbling</i>)  

332
00:17:33,453 --> 00:17:35,386
                    Oh.         

333
00:17:48,101 --> 00:17:50,168

**Decoded Without -sc

**

331
00:17:29,182 --> 00:17:32,116
                    (<i>mumbling</i>)  

332
00:17:33,453 --> 00:17:35,386
                    OH.         

333
00:17:48,101 --> 00:17:50,168
        .                       

334
00:17:50,236 --> 00:17:54,705
UH, DR. MARK SLOAN              
FROM COMMUNITY GENERAL HPITAL.

**Comment by anshul1912** [comment]
can you share dumped video, with which ccextractor crashes. It will help
developers to reproduce the issue.

Thanks
Anshul Maheshwari

On Sat, Feb 27, 2016 at 12:20 AM, jimmyoh <notifications@github.com> wrote:

> Hello,
>
> I am using ccextractor to decode Closed caption from live TV streams.
> US ATSC live TV.
> When I use -sc (Sentence Capitalisation)
> ccextractor segfaults with code 139
> if it encounters a blank line in the closed captioning.
>
> *decoded with -sc*
> 330
> 00:17:26,880 --> 00:17:29,113
> Uh...
>
> 331
> 00:17:29,182 --> 00:17:32,116
> (*mumbling*)
>
> 332
> 00:17:33,453 --> 00:17:35,386
> Oh.
>
> 333
> 00:17:48,101 --> 00:17:50,168
>
> **Decoded Without -sc
>
> **
>
> 331
> 00:17:29,182 --> 00:17:32,116
> (*mumbling*)
>
> 332
> 00:17:33,453 --> 00:17:35,386
> OH.
>
> 333
> 00:17:48,101 --> 00:17:50,168
> .
>
> 334
> 00:17:50,236 --> 00:17:54,705
> UH, DR. MARK SLOAN
>
> FROM COMMUNITY GENERAL HPITAL.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CCExtractor/ccextractor/issues/288>.
>



-- 
with regards
Anshul
:)

**Comment by jimmyoh** [comment]
Http://jimmyoh.is-a-guru.com:88/ccextractor_sample.ts

About 36m and a playable sample.

Jim
can you share dumped video, with which ccextractor crashes. It will help
developers to reproduce the issue.

Thanks
Anshul Maheshwari

On Sat, Feb 27, 2016 at 12:20 AM, jimmyoh <notifications@github.com> wrote:

> Hello,
>
> I am using ccextractor to decode Closed caption from live TV streams.
> US ATSC live TV.
> When I use -sc (Sentence Capitalisation)
> ccextractor segfaults with code 139
> if it encounters a blank line in the closed captioning.
>
> *decoded with -sc*
> 330
> 00:17:26,880 --> 00:17:29,113
> Uh...
>
> 331
> 00:17:29,182 --> 00:17:32,116
> (*mumbling*)
>
> 332
> 00:17:33,453 --> 00:17:35,386
> Oh.
>
> 333
> 00:17:48,101 --> 00:17:50,168
>
> **Decoded Without -sc
>
> **
>
> 331
> 00:17:29,182 --> 00:17:32,116
> (*mumbling*)
>
> 332
> 00:17:33,453 --> 00:17:35,386
> OH.
>
> 333
> 00:17:48,101 --> 00:17:50,168
> .
>
> 334
> 00:17:50,236 --> 00:17:54,705
> UH, DR. MARK SLOAN
>
> FROM COMMUNITY GENERAL HPITAL.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CCExtractor/ccextractor/issues/288>.
>



-- 
with regards
Anshul
:)

—
Reply to this email directly or view it on GitHub
<https://github.com/CCExtractor/ccextractor/issues/288#issuecomment-192900607>
.

**Comment by abhibansal530** [comment]
Can you please provide any other link,as i am unable to download file from given link.

**Comment by jimmyoh** [comment]
Ok,

It should have worked ....

Just goto http://jimmyoh.is-a-guru.com:88

The :88 is Important

and the link is at the bottom of the page ....

This is a dynamic IP address (DynDNS)
and occasionally changes IP.... Usually at the worst possible time.

 Jim

**Comment by cfsmp3** [comment]
Verified working with that sample in current github version

**Comment by jimmyoh** [comment]
Excellent,

I will grab and test

Jim

**Comment by jimmyoh** [comment]
Hello,

I tested your fix against about 100 video files and it worked Perfect.

Thank you
Jim
