### ISSUE TITLE
error while  building ccextractor

### ISSUE THREAD

**Issue by vinayakathavale** [CCExtractor/ccextractor#290]
There is an error while executing make [link](http://pastebin.com/ZwGBTNYk) 
there seems to be an error while importing file "zvbi_decoder.h"
output of cmake [link](http://pastebin.com/qDXursHc)
I am using cmake version 3.3.2

**Comment by anshul1912** [comment]
I think better solution would be to change makefile instead of source code, that change makes the position of file fix,

**Comment by vinayakathavale** [comment]
I made [this](https://github.com/DrImpossible/ccextractor/commit/5517bd8363006799b68735f82835d3a2ccbed102) change but it does not fix the issue make still [fails](http://pastebin.com/QTjgMWQZ)

**Comment by vinayakathavale** [comment]
issue resolved  [by](https://github.com/CCExtractor/ccextractor/pull/296) pull request #296
