### ISSUE TITLE
GSOC - Finish CEA-708 support

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#3]
EIA-708 is the "new" standard for closed captioning. While the specification has been around for some years and support for it is mandatory in the US for both TV receivers and stations, until very recently almost all stations have just converted their CEA-608 data to 708; this means that none of the 708 features have actually been used, and you still see many captions in all uppercase (to mention just one thing). This is starting to change though, so it makes sense for CCExtractor to fully implement a 708 decoder. Some work was done already, and you can actually see 708 output in CCExtractor in debug mode. But it needs to be completed by adding the actual export features.

**Comment by cfsmp3** [comment]
Assigned to bigharshrag since he's the 708 man this GSoC :-) kisselef is mentoring.

**Comment by cfsmp3** [comment]
Additional info (pasted from a separate issue, I'm going to merge 708 stuff here).

Someone just sent a number of useful samples. They're available in /repository/Cristiano708

MPEG-PS containing both CEA608 and CEA708 captions
(On version 0.76, 608 extraction works, but 708 does not)
captions_test.mpg

MPEG-TS containing both CEA608 and CEA708 captions
(On version 0.76, 608 extraction works, but 708 does not)
captions_test_ts.mpg

CEA608 TTML file generated by Adobe Premiere (CEA608 track)
(the great thing about this version is that it contains the correct positions)
captions-test_608.xml

CEA708 TTML file (slightly different from the CEA608 TTML):
(the great thing about this version is that it contains the correct positions)
captions-test_708.xml

SCC File (CEA608)
captions-test_608.scc

MCC File (CEA708)
captions-test_708.mcc

**Comment by cfsmp3** [comment]
Additional: https://github.com/CCExtractor/ccextractor/issues/178

**Comment by NilsIrl** [comment]
> you still see many captions in all uppercase

Doesn't CEA-608 case?

**Comment by cfsmp3** [comment]
> > you still see many captions in all uppercase
> 
> Doesn't CEA-608 support case?

In theory yes (check the character set here: https://en.wikipedia.org/wiki/EIA-608#Characters )

But if I recall correctly the very first decoders were uppercase only (I can't find the technical reference to support this claim though) but:

https://audio-accessibility.com/news/2018/10/all-caps-vs-mixed-case-type-for-captions/

 Also, this:

https://www.vitac.com/all-caps-captioning/

**Comment by cfsmp3** [comment]
Standard here: https://shop.cta.tech/products/line-21-data-services

I'm assigning this to @PunitLodha since he's going to be working on it during GSoC 2021.

**Comment by cfsmp3** [comment]
I'm closing this since 708 is now in reasonably good shape now that @PunitLodha killed the known bugs :-)
