### ISSUE TITLE
Add --forceflush (-ff) as parameter

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#306]
An easy one for GSoC applicants:

We need to add a parameter --forceflush (short -ff) that if used will cause the file buffers to be flushed as soon as content is written.

Actually the functionality itself is already there 
(file ccx_encoders_common.c, check the call to fsync)

but currently it's forced. The required change implies is that only if forceflush is used fysnc is to be called.

**Comment by phanindra707** [comment]
Added forceflush option #311 [https://github.com/phanindra707/ccextractor/commit/980a0b244143568d993b80610de1c9eab23bbd86]
