### ISSUE TITLE
Ability to rotate output files

### ISSUE THREAD

**Issue by lloydpick** [CCExtractor/ccextractor#345]
Using version 0.79...

`ccextractor -stdin -s -o feed.srt -out=srt`

I'm consuming a TS stream from a pipe, pretty much everything is working correctly. However I have no ability to rotate the `feed.srt` output file. No matter what I try...

`truncate -s 0 feed.srt` or `> feed.srt`

The file goes back to it's original size upon the next write.

Also if the `feed.srt` file exists and I start ccextractor, it refuses to write to the file. It must not exist upon starting.

**Comment by abhishek-vinjamoori** [comment]
The first issue is being worked upon. 
Regarding the second one where you stated "if the feed.srt file exists and I start ccextractor, it refuses to write to the file. It must not exist upon starting", could you please elaborate what you meant ?
FYI:By default CCExtractor overwrites the existing output files.
