### ISSUE TITLE
High Memory Consumption - 180 MB

### ISSUE THREAD

**Issue by josecasillas** [CCExtractor/ccextractor#353]
Shelling out ccextractor instances on Linux from an app to process parallel streams.  Feeding low-bit-rate video via stdin, using stream mode, disabled input buffering, captions going into stdout.  Seems each instance occupies a fixed amount of ~180 MB of RAM, severely limiting what we can accomplish on each box.

Is it possible to configure the size of internal buffers more modestly?  Any insight into the 180 MB RAM footprint?

Thank you!
Jose

**Comment by Abhinav95** [comment]
I can confirm this issue. Every instance of ccextractor, (both Windows and Linux), occupies an amount of memory that ranges around 160-200 MB, depending on the parameters passed.

**Comment by cfsmp3** [comment]
So where does all this memory go? :-)

**Comment by Abhinav95** [comment]
I am using valgrind to analyze memory allocation as the program runs.
The major problem is that 187477304 bytes (179.79 MB) of memory is allocated to `ctx` in the `init_libraries()` call at the beginning of the program from `main`.
`sizeof(struct lib_ccx_ctx)` returns 187477304.

**Comment by Abhinav95** [comment]
#373 fixes this issue.

@josecasillas You should expect a memory usage of atmost 25 MB per instance from now on, except for when passing the '-xmltv' parameter which will give memory usage around 200 MB(which I don't think you are using because you described just caption output to stdout). Good luck for your application :)

**Comment by josecasillas** [comment]
I can't thank you enough.  Great job on this, and fast turn around.  Thank you my friend!

**Comment by josecasillas** [comment]
Tested today with the new build and I'm seeing < 5 MB per instance! Memory no longer the limiting factor.  Thanks again!

**Comment by cfsmp3** [comment]
Great job Abhinav !
