### ISSUE TITLE
Premature end of file (2)

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#356]
Another sample that causes it is in the user-accessible repository, directory /Tajemnica, file data0001.ts

CCExtractor 0.80, Carlos Fernandez Sanz, Volker Quetschke.
## Teletext portions taken from Petr Kutalek's telxcc

Input: C:\Users\Dell\Desktop\Ripping\TVP1 HD-04242016-2023.pvr\data0001.ts
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: Auto] [Debug: No] [Buffer input: Yes]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .srt] [Encoding: Latin-1] [Delay: 0] [Trim lines: No]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: Autodetect]
## [Start credits text: None]

Opening file: C:\Users\Dell\Desktop\Ripping\TVP1 HD-04242016-2023.pvr\data0001.ts

File seems to be a transport stream, enabling TS mode

Analyzing data in general mode
Premature end of file!

**Comment by cfsmp3** [comment]
Direct download link:
https://drive.google.com/open?id=0B_61ywKPmI0TdkotdUhvRDdYTjQ

**Comment by cfsmp3** [comment]
GSoC qualification: This issues gives 2 points.

**Comment by Diptanshu8** [comment]
@cfsmp3 I tried extracting the subtitles and the generated srt could be found at https://drive.google.com/uc?export=download&id=0BxtyBcewAlIwN3ZGNW1PeE16VzQ .

**Comment by cfsmp3** [comment]
I don't get that error any more (just tested), so closing.
