### ISSUE TITLE
DVD files that work OK in 0.69 fail in 0.80

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#358]
We have a report for a home burned DVD that works fine in 0.69 but fails in 0.80 (of course the issue may be introduced in any version in between).

It can be found in the semi-public directory in the directory Cindy.Koch

Willem can you find out where we broke this, then we'll assign to someone else?

**Comment by canihavesomecoffee** [comment]
@cfsmp3 It seems to be running on the official release of .79... Could you ask the user if they can confirm this? In the mean time I'll see if I can pinpoint the exact commit

```-autoprogram  -out=srt -bom -latin1 VTS_01_1.VOB``` was the command I used, and I was able to extract them with .79

**Comment by canihavesomecoffee** [comment]
Looked into it a bit more, with 0.80 (on Win & Lin), the subs generate just fine apart from a +- 0.5sec shift in timing... Is it possible to confirm this?

**Comment by cfsmp3** [comment]
Code-in task created.

**Comment by cfsmp3** [comment]
Direct link:
https://drive.google.com/open?id=0B_61ywKPmI0Tby1hc08xSW1pMWs

**Comment by anukul** [comment]
@canihavesomecoffee Yes, I checked it on 0.69 and 0.80
The output of `diff old.srt new.srt` is here: http://pastebin.com/2TGwFvb7

**Comment by cfsmp3** [comment]
GSoC qualification: This issues gives 2 points.

**Comment by cfsmp3** [comment]
Tested in 0.86, works OK - subtitles are in sync (watched a bit of the movie with VLC + our subs).
