### ISSUE TITLE
Teletext page number dropped in -UCLA switch

### ISSUE THREAD

**Issue by Liontooth** [CCExtractor/ccextractor#359]
In the latest github version of CCExtractor the teletext page number is no longer listed in the third field:
```
20160219101902.280|20160219101905.360|TLT|-Может быть, вы забыли, я занимаюсь полковником Лыковым.
```
The github version from mid-March shows the teletext page number and the string TLT:
```
20160219101902.280|20160219101905.360|888TLT|-Может быть, вы забыли, я занимаюсь полковником Лыковым.
```
What we actually want is the teletext number with no TLT string:
```
20160219101902.280|20160219101905.360|888|-Может быть, вы забыли, я занимаюсь полковником Лыковым.
```
So the wrong part of the output was removed in a recent change. The teletext page number is useful information and we'd like to keep it.

Command:
```
$ ccextractor -debug -608 -datets -ttxt -autoprogram -tpage 888 -UCLA -noru -utf8 --nofontcolor -parsepat -parsepmt -unixts $BTIM -o $FIL.ccx.out $FIL.mpg
```
Sample file:

- http://vrnewsscape.ucla.edu/dropbox/2016-02-19_1019_RU_TVC_News.mpg

On the other hand, the mid-March github version would typically fail to use Cyrillic for the very last line; this bug (not reported) has disappeared in the current version.

Cheers,
David

**Comment by Abhinav95** [comment]
Hi David.

I have introduced this undesirable change inadvertently while fixing another issue with the -ucla switch, and will try and fix this for you.

Could you confirm that you need only the teletext page number in the third field, while for other types of subtitles it should contain their mode (for instance ...|...|ISDB|... for ISDB subtitles)?

I will set it accordingly.

**Comment by bigharshrag** [comment]
Hi David,
I would also like to add that I had noticed the bug in which Cyrillic would not be used for the last line and it was subsequently fixed (via #335).

**Comment by Abhinav95** [comment]
#360 should fix this

Sample output is now:-

`20160519190355.280|20160519190358.360|888|-Может быть, вы забыли, я занимаюсь полковником Лыковым.`

**Comment by Liontooth** [comment]
@Abhinav95 -- great, that's exactly right. I'll test it.
@bigharshrag -- thank you for noticing!

**Comment by Liontooth** [comment]
I can confirm #360 fixes this issue; thanks!
