### ISSUE TITLE
Question on CC extraction options

### ISSUE THREAD

**Issue by lelegard** [CCExtractor/ccextractor#376]
Hello,

This is a question, not a bug report. Please let me know if there is a more appropriate place to fill that kind of request.

Following `-out=report`, an application (QtlMovie) collects the various CC streams and let a user select the one to burn in the video. According to the user's choice, a ccextractor command is generated to extract the SRT. I would like to confirm the extract options to use, depending on the selection.

My understanding is the following:

`EIA-608: Yes/No`
`XDS: Yes/No ==> ?`
`CC1: Yes/No ==> Option: -1`
`CC2: Yes/No ==> Option: -2`
`CC3: Yes/No ==> Option: -cc2 -1`
`CC4: Yes/No ==> Option: -cc2 -2`
`CEA-708: Yes/No`
`Services: 1 ==> Option: -svc 1`

Am I correct? Or what should I use?

Additional questions:

- What is XDS?
- What would be `-out=report` output in case of multiple CEA-708 streams ? "`Services: 1,2`" or two lines "`Services: 1`" and "`Services: 2`"?
- May I suggest to make the "help" output of ccextractor a bit more clear on the CC numbering?

Thanks in advance for your help
Thierry

**Comment by canihavesomecoffee** [comment]
- [XDS](https://en.wikipedia.org/wiki/Extended_Data_Services) provides information about the current running program (in CEA608), station etc. This information is only printed if enabled with the ```-xds``` parameter and if the output is transcript
- CC1/CC3 don't need the ```-1``` as that is set by default, but you can enter it anyway if you wish
- ```-svc``` are the ones for CEA708 data;
- From what I see from the source it will print ```Services: 1 2 500``` in case there are multiple ones. The argument you need to pass to ```-svc``` in this case would be as follows: ```-svc 1,2,500``` (or if you know more details (e.g. the character set), you can define the charset between brackets: ```-svc 1[EUC-KR],3```

Hope this answers your questions :)

**Comment by lelegard** [comment]
Yes, definitely, thanks a lot.
