### ISSUE TITLE
Compatibility with Adobe Premiere

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#380]
Someone who wanted to remain anonymous sent a patch for Adobe Premiere compatibility in SMPTE-TT .

Fundamentally the change is about the headers, but there's a few to-do items to do it really well (basically, fill some fields based on actual data). 

Attached is the original patch that was submitted. It should be quite straight forward. I haven't merged it because it's incomplete, but it should take less than one day to complete it.

Assigned to Willem because testing properly will require the regression test platform.
[smptett-changes.zip](https://github.com/CCExtractor/ccextractor/files/292481/smptett-changes.zip)

**Comment by cfsmp3** [comment]
Code-in task created.

**Comment by saurabhshri** [comment]
@cfsmp3 Do we have sample in our collection which has italics or bold data in them? I am working on this fix, and now I need to do proper tts styling for Premiere Pro compatibility. Any such sample will be of HUGE help.

**Comment by cfsmp3** [comment]
Probably yes (at least italics, since they are common), but we don't know
which ones specifically :-(

**Comment by saurabhshri** [comment]
@cfsmp3 My bandwidth is too slow to download all and check each of them. :( Will look for something.
