### ISSUE TITLE
Premature end of file - UK DVB-T2 .ts file

### ISSUE THREAD

**Issue by aaronstevens** [CCExtractor/ccextractor#388]
I pulled a decrypted .ts video of a 30 minute show from my Humax HDR-Fox T2 and trying to extract the subtitles so I can use it in Handbrake

This is the command used and the output - I also used Mediainfo to find out the PID for the subtitle stream, and also tried without but it outputs the same error:

C:\Users\Aaron\Desktop\ccextractor\ccextractorwin.exe  --gui_mode_reports  -datapid 0x19CD -autoprogram  -out=srt -bom -latin1 [+input files]

CCExtractor 0.80, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: D:\1126.TS
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: Auto] [Debug: No] [Buffer input: Yes]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .srt] [Encoding: Latin-1] [Delay: 0] [Trim lines: No]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]

-----------------------------------------------------------------

Opening file: D:\1126.TS

File seems to be a transport stream, enabling TS mode

Analyzing data in general mode
Premature end of file!

ATTENTION!!!!!!
In switch_to_next_file(): Processing of D:\1126.TS 0 ended prematurely 3 < 965599360, please send bug report.

Done, processing time = 0 seconds
This is beta software. Report issues to carlos at ccextractor org...

**Comment by canihavesomecoffee** [comment]
Hello,

Is this a version you compiled yourself from git? If so, could you please retry with the latest git commits included?

**Comment by aaronstevens** [comment]
Hi,

It was a portable binary from https://sourceforge.net/projects/ccextractor/files/ccextractor/0.80/

**Comment by canihavesomecoffee** [comment]
Ok, I was asking because it was located on the desktop instead of the default install folder :+1: 

Is it possible to share the file for a short period (Uploading it to dropbox, google drive or so)?

**Comment by aaronstevens** [comment]
Here you go! https://dl.dropboxusercontent.com/u/12843960/1126.TS

**Comment by canihavesomecoffee** [comment]
I've ran the file through the current github repo version, and there's some additional information that gets output:

"Premature end of file (incomplete TS packer header, expected 4 byes, got 3)."

I'll ask in the team to see if there's a way to solve that.

**Comment by aaronstevens** [comment]
Yeah it plays with subs in VLC but .ts files are very crash-prone.

Ok, thanks :+1:

**Comment by cfsmp3** [comment]
This is really really strange - I'm assigning this to Anshul since this is DVB.

**Comment by Vindictor** [comment]
Was this ever solved?

I've just started using CCExtractor, and when I give it a .ts file from my Humax HDR-Fox T2 I get

Analyzing data in general mode
Premature end of file (incomplete TS packer header, expected 4 bytes, got 3).




ATTENTION!!!!!!
In switch_to_next_file(): Processing of Y:\Test.ts 0 ended prematurely 3 < 2316304384, please send bug report.


Done, processing time = 0 seconds
This is beta software. Report issues to carlos at ccextractor org...


I've tried changing some of the input and advanced input options to see if I could get it to work, such as enabling "File was captured with a Hauppauge card" but I still get various errors and no actual subtitle extraction.

Sorry if I'm hijacking the OP, it just appeared we were having the exact same issue, from the same hardware recorder.
Subs play fine on the PVR, or in MPC-HC.

**Comment by cfsmp3** [comment]
Check 

https://github.com/CCExtractor/ccextractor/issues/424

for a Windows binary that solves the problem.
