### ISSUE TITLE
Tesseract fail cause spngpng to fail

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#391]
This command:

ccextractor -out=spupng -parsePMT -parsePAT -codec dvbsub  "C:\DeletableTempStuff\UK Samples\chan52_GOOD.ts"

fails with the error "tessaract cannot find any language!" for me. I understand the issue is that I'm missing some tesseract files, but the output is spupng so I should get output anyway.

In fact, if I compile without OCR support, it works fine (as expected).

**Comment by anshul1912** [comment]
need complete logs, MSG ""tessaract cannot find any language!" comes from inside tesseract, full logs would help me to get traces.
