### ISSUE TITLE
DVB: Incorrect Y offset

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#395]
In spunpng, all the offset in the XML file in spupng have a Y offset:

<spu start="195.340" end="195.440" image="C:\DeletableTempStuff\UK Samples\BBC_ONE_2016-06-21.d/sub0576.png" xoffset="35" yoffset="0">
</spu>

<spu start="195.440" end="195.580" image="C:\DeletableTempStuff\UK Samples\BBC_ONE_2016-06-21.d/sub0577.png" xoffset="35" yoffset="0">
</spu>
<!--
their defence,

**Comment by anshul1912** [comment]
can be closed.
