### ISSUE TITLE
01-BBC1.EastEnders.ts: Incorrect progress display

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#397]
In 01-BBC1.EastEnders.ts (using this file but I assume it's a general problem) the first time progress is reported it prints this:

 0%  |  202:07

That timestamp is calculated here:

	LLONG t=get_fts(dec_ctx->timing, dec_ctx->current_field);
	if (!t && ctx->demux_ctx->global_timestamp_inited)
	t=ctx->demux_ctx->global_timestamp - ctx->demux_ctx->min_global_timestamp;
	int cur_sec = (int) (t / 1000);
	activity_progress(progress, cur_sec/60, cur_sec%60);

With  ctx->demux_ctx->min_global_timestamp==0

Anyway, the timing variables are fixed by the next pass (of course something is broken here already) and the correct time start. But that the 7 to the right is left there forever because the new lines only use 2 characters for the hour.

Of course no, it's not a solution to write an extra space :-)

**Comment by anshul1912** [comment]
payload.pcr is coming 0 in between the video, which makes the min_global_timestamp as 0,
and when we calculate it comes out to be random value.

Another thing is that when fts is 0, we calculate timestamp from PCR, in rest of place we rely on timestamp from PES, both have different timing which makes a rondom second when fts is 0
