### ISSUE TITLE
Missig file capi.h when installing

### ISSUE THREAD

**Issue by soura97** [CCExtractor/ccextractor#420]
I was trying to install ccextractor by downloading the zip from github. I unzipped it using **unzip ccextractor-master** then performed **cd linux** and **./build** when following messages were given and installation terminated.

./build: line 11: protobuf-c: command not found
Obtaining Git commit
Git command not present, trying folder approach
Storing variables in file
Commit: Unknown
Date: 2016-09-08
Stored all in compile.h
Done.
../src/lib_ccx/ocr.c:4:18: fatal error: capi.h: No such file or directory
compilation terminated.

**Comment by canihavesomecoffee** [comment]
Do you have OCR installed? By default OCR is enabled nowadays, and the libraries are thus required.

**Comment by soura97** [comment]
I installed Tesseract and Leptonica but still showing the same error. Any idea?

**Comment by cfsmp3** [comment]
@soura97 You need the development packages.  

This is what I use for Ubuntu 16.04

libleptonica-dev 
libtesseract-dev 
libtesseract3 
tesseract-ocr-dev 
tesseract-ocr-eng

**Comment by maxkoryukov** [comment]
@cfsmp3, It is really helpful comment. May be it is worth to add its content to the `linux/readme.md` ??

**Comment by cfsmp3** [comment]
It would probably make more sense to have ./build check for capi.h, or in
case of compilation failure write an explanation with the likely causes. Or
do both :-) Or not fail and just build without OCR support.

What I will do is create a task for code-in so someone does one of these
thinks :-)
