### ISSUE TITLE
VideoRedo output, can't extract subs

### ISSUE THREAD

**Issue by Vindictor** [CCExtractor/ccextractor#423]
Hi there.
I've been using VideoRedo to edit my HD .ts files for some time.  (current version 5.1.3.741)

In a recent update they added the option that DVB Subtitles are saved, when saving in an mkv container.
These are then playable in MPC-HC.

A friend recently recommended CCExtractor so that I may extract the subs properly as .srt files, which are then more compatible with other players.

Unfortunately, when adding one of these MKV files to CCExtractor the process appears to run, but creates a 0 byte .srt file with the following info

CCExtractor 0.82, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: E:\temp\VideoRedo Temp\Test.mkv
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: Auto] [Debug: No] [Buffer input: Yes]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .srt] [Encoding: Latin-1] [Delay: 0] [Trim lines: No]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]

-----------------------------------------------------------------

Opening file: E:\temp\VideoRedo Temp\Test.mkv

File seems to be an elementary stream, enabling ES mode

Analyzing data in general mode
Creating E:\temp\VideoRedo Temp\Test.srt

Skip forward to the next Sequence or GOP start.

Skip forward to the next Sequence or GOP start.

Skip forward to the next Sequence or GOP start.

Skip forward to the next Sequence or GOP start.

Number of NAL_type_7: 0
Number of VCL_HRD: 0
Number of NAL HRD: 0
Number of jump-in-frames: 0
Number of num_unexpected_sei_length: 0

Total frames time:	  00:00:00:000  (0 frames at 29.97fps)

Min PTS:				00:17:28:468
Max PTS:				00:17:28:468
Length:				 00:00:00:000

Initial GOP time:	   00:17:28:468
Final GOP time:		 00:17:28:468 +0F
Diff. GOP length:	   00:00:00:000 +0F	(00:00:00:000)

Done, processing time = 1 seconds
This is beta software. Report issues to carlos at ccextractor org...

I then had the idea to use VideoRedo to remux the file back into a .ts container.
When I do this the dvb subtitles are still intact, and are still playable in MPC-HC.
I get this output from CCExtractor.

CCExtractor 0.82, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: E:\temp\VideoRedo Temp\Test.ts
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: Auto] [Debug: No] [Buffer input: Yes]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .srt] [Encoding: Latin-1] [Delay: 0] [Trim lines: No]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]

-----------------------------------------------------------------

Opening file: E:\temp\VideoRedo Temp\Test.ts

File seems to be a transport stream, enabling TS mode

Analyzing data in general mode
DVB subtitles detected, OCR subsystem not present. Use -out=spupng for graphic output
Creating E:\temp\VideoRedo Temp\Test.srt
Changed fps using NAL to: 25.000000

Number of NAL_type_7: 3686
Number of VCL_HRD: 0
Number of NAL HRD: 0
Number of jump-in-frames: 1
Number of num_unexpected_sei_length: 0

Total frames time:	  00:58:11:920  (87298 frames at 25.00fps)

Min PTS:				00:00:00:320
Max PTS:				00:58:12:240
Length:				 00:58:11:920

Done, processing time = 3 seconds
This is beta software. Report issues to carlos at ccextractor org...

I have also tried remuxing the file with mkvtoolnix / MKVmerge and giving that output to CCExtractor but it still won't work.

The DVB-Subtitles are in the MKV container and players can play them.
They further survive the conversion back to .ts
Yet CCExtractor can't extract them.

I was hoping for some help with this.

I've just cut out a random 5 minute section for anyone to test, if required.
I noticed the first subtitle appears late, but the rest are in time.  Ignore this, it could be because of where I edited it.  It's fine after this, and this isn't the issue.

Here is the mkv container version with dvb subtitles
https://drive.google.com/file/d/0B0DIrRkpdn12Zkp1RkZaejlDakk/view?usp=sharing

Here is the .ts container version with dvb subtitles
https://drive.google.com/file/d/0B0DIrRkpdn12Z0tkZHlDc01TZEU/view?usp=sharing

(I've never tried Google Drive for sharing, so I hope you have access)

This is what I see on the .ts file in CCExtractor for this 5 minute .ts file

CCExtractor 0.82, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: E:\temp\VideoRedo Temp\CCCExtractor.ts
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: Auto] [Debug: No] [Buffer input: Yes]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .srt] [Encoding: Latin-1] [Delay: 0] [Trim lines: No]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]

-----------------------------------------------------------------

Opening file: E:\temp\VideoRedo Temp\CCCExtractor.ts

File seems to be a transport stream, enabling TS mode

Analyzing data in general mode
DVB subtitles detected, OCR subsystem not present. Use -out=spupng for graphic output
Creating E:\temp\VideoRedo Temp\CCCExtractor.srt
Changed fps using NAL to: 25.000000

Number of NAL_type_7: 344
Number of VCL_HRD: 0
Number of NAL HRD: 0
Number of jump-in-frames: 1
Number of num_unexpected_sei_length: 0

Total frames time:	  00:05:27:520  (8188 frames at 25.00fps)

Min PTS:				00:00:00:480
Max PTS:				00:05:28:040
Length:				 00:05:27:560

Done, processing time = 0 seconds
This is beta software. Report issues to carlos at ccextractor org...

**Comment by cfsmp3** [comment]
mkv is not supported. CCExtractor needs to read the original recording (usually a TS), not a processed file. 

You can extract the DVB subtitles first (from the .ts) with CCExtractor (convert to .srt) and then inject them into the .mkv if you want.

**Comment by Vindictor** [comment]
OK! Thank you for your response. 

I've already begun using CCExtractor on the .ts file before converting to mkv.... in fact I can edit the ts in videoredo, save the edit as a ts, use ccextractor on that, and then simply remux the edited ts and new srt file into an mkv. That works fine. 

The problem I have are the many recordings that have already been saved as mkv before I started using CCExtractor. 
I had hoped that converting them back to .ts would work, as players can still see the subs and play them. 

If you say it's not possible, then it's not possible. 
I just wanted to ask if there was a way. 
Thank you for your time.

**Comment by cfsmp3** [comment]
If there's a program that converts from MKV to TS keeping the DVB subtitles
you can use it. But in general subtitles are destroyed by most processing
tools. VideoRedo is the only one program that know that does a real effort
to respect subtitles.

It doesn't always do it right :-) But they definitely want to and they
improve support with each version.

**Comment by Vindictor** [comment]
I'm sorry if I didn't explain it right, or that my post was too long to read. 

Videoredo will allow you to edit the .ts and save as mkv, retaining subs. 

Videoredo will also allow me to load the mkv and save as .ts, and the subs survive

This ts file is what CCExtractor can't extract from. 
This is the example I put in my original post. 
There are two small files available for you to test. 
One is the mkv file with subs

The other is the mkv converted back to ts. 
The subs are intact, players can play them, CCExtractor says DVB subtitles detected, but won't extract. 

My apologies for the confusing first post.

**Comment by cfsmp3** [comment]
Sorry, I misunderstood. I took a quick look at the same. There's definitely a problem with the detection code. I'm assigning this to Willem since I remember he did the last work on it.

Willem: Adding -in=ts makes it process the file while not adding this cause it to report that it's found a MP4 box but still detects it as a TS (this would be correct) but then exits immediately on short read (definitely wrong).

Anyway after forcing the format to TS (which seems to work, it reports that it's multiprogram etc) I get lots of DVB processing messages. Could be or not related to the format stuff so I guess we should first take care of one thing, then the other.

**Comment by Vindictor** [comment]
Thank you for your help. 
It's very much appreciated.

**Comment by esieens** [comment]
I'm running into a similar issue and what intrigued me is the message:
"DVB subtitles detected, OCR subsystem not present."

Adding the in=ts flag did not make any difference for me.

Is the "OCR subsystem not present" not an issue?

Thanks

Analyzing data in general mode

This TS file has more than one program. These are the program numbers found: 
17472
17540
17604
17664
17920
18112
20352
DVB subtitles detected, OCR subsystem not present. Use -out=spupng for graphic output
Creating /Users/dperrault/Desktop/20150530225148-BBC_ONE_HD_-_Match_of_the_Day__FA_Cup_Final___.srt
  0%  |  00:00Changed fps using NAL to: 25.000000

Found large gap(3879740) in PTS! Trying to recover ...

Found large gap(3879732) in PTS! Trying to recover ...

Found large gap(3879728) in PTS! Trying to recover ...

Found large gap(3879726) in PTS! Trying to recover ...

Found large gap(3879730) in PTS! Trying to recover ...

Found large gap(3879736) in PTS! Trying to recover ...

Found large gap(3879734) in PTS! Trying to recover ...

Found large gap(3879738) in PTS! Trying to recover ...
  1%  |  00:21Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
  3%  |  01:15Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
  4%  |  01:34Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
  5%  |  01:49Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
  6%  |  02:03Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
  7%  |  02:15Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
  9%  |  03:03Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
 10%  |  03:30Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
 11%  |  03:52Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
 12%  |  04:12Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
 13%  |  04:29Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000

[....]

Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
Changed fps using NAL to: 25.000000
 95%  |  31:07Changed fps using NAL to: 25.000000
 96%  |  31:35Changed fps using NAL to: 25.000000
 99%  |  32:53Premature end of file - Transport Stream packet is incomplete (expected 188 bytes, got 140).
100%  |  33:12
Number of NAL_type_7: 2098
Number of VCL_HRD: 0
Number of NAL HRD: 0
Number of jump-in-frames: 282
Number of num_unexpected_sei_length: 0

Total frames time:	  00:33:12:200  (49805 frames at 25.00fps)

Min PTS:				21:33:13:885
Max PTS:				22:06:26:805
Length:				 00:33:12:920
Done, processing time = 15 seconds
This is beta software. Report issues to carlos at ccextractor org...
