### ISSUE TITLE
CEA-708 sentence capitalization

### ISSUE THREAD

**Issue by cactusGit** [CCExtractor/ccextractor#429]
It's missing. Looks like `clever_capitalize` and `correct_case_with_dictionary` used only for other subs. I can make pull request with mostly copy-pasted code, but you could make it more architecturally correct.

**Comment by cfsmp3** [comment]
Pending for now. In theory subtitles from 708 should be proper cased unless someone is really lazy.

I prefer to wait until 708 is stable (meaning subs extraction is good and we get to the point in which we prefer 708 over 608 every time) before adding features/bloat that makes code harder to debug.

**Comment by cfsmp3** [comment]
Closing, since it's not going to happen - it just doesn't seem needed for 708, I've been looking at lots of samples lately.
