### ISSUE TITLE
Time offset -unixts ignored when extracting from metadata dump

### ISSUE THREAD

**Issue by Liontooth** [CCExtractor/ccextractor#430]
On ccextractor from github master 16 July 2016, the -unixts switch works when extracting teletext directly from the mpg file:

> ccextractor -pn 1100 -tpage 888 -datets -ttxt -UCLA -noru -utf8 --nofontcolor -parsepat -parsepmt -unixts 1475082001 -o /tv/2016/2016-09/2016-09-28/2016-09-28_1700_RU_ТВЦ_Право_голоса.ccx.out /tv/2016/2016-09/2016-09-28/2016-09-28_1700_RU_ТВЦ_Право_голоса.mpg
> 
> 20160928170005.360|20160928170010.120|888|Киев сегодня получил от израильского посольства ноту протеста в связи с пропагандой ксенофобии
> 20160928170010.160|20160928170016.400|888|и антисемитизма в эфире одной из национальных телерадиокомпаний.
> 20160928170016.440|20160928170020.080|888|Итоги выборов в Государственную думу стали темой заседания подмосковного штаба общероссийского
> 20160928170020.120|20160928170021.520|888|народного фронта.

But it is ignored when extracting the same text from the metadata dump:

> ccextractor -in=bin -pn 1100 -tpage 888 -datets -ttxt -UCLA -noru -utf8 --nofontcolor -parsepat -parsepmt -unixts 1475082001 -o 2016-09-28_1700_RU_ТВЦ_Право_голоса.ccx.out 2016-09-28_1700_RU_ТВЦ_Право_голоса.bin
> 
> 19700101000004.360|19700101000009.120|CC?||Киев сегодня получил от израильского посольства ноту протеста в связи с пропагандой ксенофобии
> 19700101000009.160|19700101000015.400|CC?||и антисемитизма в эфире одной из национальных телерадиокомпаний.
> 19700101000015.440|19700101000019.080|CC?||Итоги выборов в Государственную думу стали темой заседания подмосковного штаба общероссийского
> 19700101000019.120|19700101000020.520|CC?||народного фронта.

**Comment by xvkdev** [comment]
Can you submit .bin file?
Also, does this happen in current master?

**Comment by cfsmp3** [comment]
Fix merged.
