### ISSUE TITLE
Can't build Mac version

### ISSUE THREAD

**Issue by mackworth** [CCExtractor/ccextractor#432]
The github version does not compile; it complains about missing protobuf. I tried adding ` -I../src/` to the BLD_INCLUDE, and `SRC_PROTOBUF="$(find ../src/protobuf-c -name '*.c')"` to the BLD-SOURCES line, which avoids the error, but then it has the rather odd symptom of not producing an executable.

The 0.82 version downloaded from [the original ccextractor site](https://sourceforge.net/projects/ccextractor/?source=typ_redirect) does compile and does work, but it seems to be behind the github version.

**Comment by cfsmp3** [comment]
Post the complete output from build so we can take a look.

**Comment by mackworth** [comment]
First is output without any changes:
[ccextractor Build1.txt](https://github.com/CCExtractor/ccextractor/files/520031/ccextractor.Build1.txt)

Then I changed build.command to:
[build2.command.txt](https://github.com/CCExtractor/ccextractor/files/520032/build2.command.txt)

 and got essentially the same results without the protobuf errors:
[ccextractor build2.txt](https://github.com/CCExtractor/ccextractor/files/520037/ccextractor.build2.txt)

I should mention that many of the warning messages from clang should probably be looked into. It looks like several checks are not doing what they look like they're doing due to type issues.

**Comment by cfsmp3** [comment]
Most likely you also have to add curl to the list of libraries.

**Comment by mackworth** [comment]
Figured this one out; I missed an error message for `utf8proc` buried in all the warnings. I'll do a pull request for the revised build command that incorporates protobuf and utf8proc in the process.

**Comment by mackworth** [comment]
fixed in PR #435
