### ISSUE TITLE
suffix "+", didn't work well with DVB files, and no longer works with new versions

### ISSUE THREAD

**Issue by edumj** [CCExtractor/ccextractor#440]
If I try to extract Teletext subs from this 2 files:
[000.ts](https://mega.nz/#!6V8gRaLZ!RQSBy7HY_R3reTRQbygPbK3KNd98Th6lI3cHWd7VfgU)
[001.ts](https://mega.nz/#!Pdk3lJxR!tgVdInKWYb7GN2VnonoGABGf2VtZksz9dX8QKh78ltY)
The result is a srt file with all the subtitules (from both .ts files), but bad timing from the second .ts:

...
432
00:30:19,160 --> 00:30:22,640
y por eso he hecho lo que he hecho,
como dictan las normas.

433
00:30:22,720 --> 09:59:27,640
Gracias de todos modos.

434
**09:59:39,600 --> 09:59:40,960**
Radio, aquí Control.

435
09:59:41,040 --> 09:59:44,560
Señor Zimmer, vuelva a recuperar
la comunicación y hágalo ya.
...
First file lats 30:24 and second 5:19, but time from second one starts form 9h59m39s!!

I don't know the number of this version, but it's from 2015.

I'he tried with new versions (0.79 and 0.82) but suffix "+" seems to no longer work with DVB files!?
With 0.79 says ERROR, and with 0.82 just hangs.

**Comment by cfsmp3** [comment]
What's the complete command line you are using?

**Comment by edumj** [comment]
I've tried with:

"ccextractorwin.exe" "000.ts+" -autoprogram --nofontcolor 			 						 -tpage 888	-out=srt -o	"'000.ts+'.srt"

"ccextractorwin.exe" "000.ts+" -autoprogram --nofontcolor 			 		--fixpadding -tpage 888	-out=srt -o	"'000.ts+' --fixpadding.srt"

"ccextractorwin.exe" "000.ts+" -autoprogram --nofontcolor --goptime 		--fixpadding -tpage 888	-out=srt -o	"'000.ts+' --fixpadding --goptime.srt"

"ccextractorwin.exe" "000.ts+" -autoprogram --nofontcolor --videoedited	--fixpadding -tpage 888 	-out=srt -o	"'000.ts+' --fixpadding --videoedited.srt"

**Comment by edumj** [comment]
Well, with new versions seems to work, but truncates file and hungs if I add "--videoedited" option.

But I don't understand why I have to add that TESSDATA_PREFIX environmnet variable with new versions, but later it seems not no te be needed anymore, because now it works without it.

**Comment by cfsmp3** [comment]
Code-in task created.

**Comment by edumj** [comment]
Sorry?

Also, new versions don't work with XP? I'm testing in XP and t says it's not a valid Win32 app.

**Comment by cfsmp3** [comment]
Reason to use a discontinued OS?

**Comment by edumj** [comment]
There are still many people using XP, and I'm trying to make a script compatible also with them. Where do you says it's not compatible with XP?

Anyway, I foung another bug: Line 433 is the last subtitle of 000.ts, and it stays 30 seconds on screen! until the next subtitle from 001.ts appears:

...
433
00:30:22,720 --> 00:30:53,520
Gracias de todos modos.

434
00:30:53,560 --> 00:30:55,600
Todo el sistema está averiado.
...

**Comment by grave-w-grave** [comment]
"ccextractorwin.exe" "000.ts+" -autoprogram --nofontcolor -tpage 888 -out=srt -o "'000.ts+'.srt" 
and 
"ccextractorwin.exe" "000.ts+" -autoprogram --nofontcolor --goptime --fixpadding -tpage 888 -out=srt -o "'000.ts+' --fixpadding --goptime.srt"
and
"ccextractorwin.exe" "000.ts+" -autoprogram --nofontcolor --fixpadding -tpage 888 -out=srt -o "'000.ts+' --fixpadding.srt"
all have the the 5 missing lines error, but no timing error.

"ccextractorwin.exe" "000.ts+" -autoprogram --nofontcolor --videoedited --fixpadding -tpage 888 -out=srt -o "'000.ts+' --fixpadding --videoedited.srt" crashes at line 432

Using windows 10 and Version 0.82

**Comment by cfsmp3** [comment]
@edumj I'm going over this. You said:

But, in fact, there are 5 missing lines! This is the .srt file using ffmpeg.zvbi:
...
433
00:28:25,480 --> 00:28:55,480
Gracias de todos modos.

434
00:28:39,600 --> 00:29:09,600
Radio, aquí Control.

What I see there is 
1) ffmpeg.zvbi also exports 30 seconds for that line 433, so same behavior as CCExtractor
2) The timing for line 433 overlaps 433, which is not valid. So looks like CCExtractor is doing the best it can - ignore overlapping lines.

Looks like a problem with the input stream, but if this is still happening with other files please reopen the ticket.
