### ISSUE TITLE
Error in fopenWriteStream: stream not opened

### ISSUE THREAD

**Issue by Ivan2309** [CCExtractor/ccextractor#454]
I'm not sure what information is required, sorry.

I compiled ccextractor in the build directory with the command
sudo make ENABLE_OCR=yes ENABLE_FFMPEG=yes

Then I changed to the linux directory and executed

sudo make ENABLE_HARDSUBX=yes

And then to start ccextractor, here's the command and some of the output - the same error continues until the end of the file and there is no output file created.

ivan@ivan-Aspire-V5-571:~/Desktop/Vietnamese/Learning Vietnamese$ ccextractor -hardsubx 1000\ Vietnamese\ common\ words\ -\ Learn\ Vietnamese\ 1000\ words\ \[Low\,\ 360p\].mp4 
CCExtractor 0.82, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
HardsubX (Hard Subtitle Extractor) - Burned-in subtitle extraction subsystem
Input : 1000 Vietnamese common words - Learn Vietnamese 1000 words [Low, 360p].mp4
Subtitle Color : White
OCR Mode : Frame-wise (simple)
OCR Confidence Threshold : 0.00 (Default)
OCR Luminance Threshold : 95.00 (Default)
OCR Italic Detection : Off
Minimum subtitle duration : 0.5 seconds (Default)
FFMpeg Media Information:-
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '1000 Vietnamese common words - Learn Vietnamese 1000 words [Low, 360p].mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2016-02-11 07:32:40
  Duration: 01:43:50.19, start: 0.000000, bitrate: 187 kb/s
    Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 640x360 [SAR 1:1 DAR 16:9], 88 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 95 kb/s (default)
    Metadata:
      creation_time   : 2016-02-11 07:32:48
      handler_name    : IsoMedia File Produced by Google, 5-11-2011
Creating 1000 Vietnamese common words - Learn Vietnamese 1000 words [Low, 360p].srt
Beginning burned-in subtitle detection...
Error in fopenWriteStream: stream not opened
Error in pixWrite: stream not opened
  0%  |  00:00Error in fopenWriteStream: stream not opened
Error in pixWrite: stream not opened
  0%  |  00:01Error in fopenWriteStream: stream not opened
Error in pixWrite: stream not opened
  0%  |  00:02Error in fopenWriteStream: stream not opened
Error in pixWrite: stream not opened
  0%  |  00:03Error in fopenWriteStream: stream not opened

Regards,

Ivan.

**Comment by cfsmp3** [comment]
Looks like a permissions problem... it should just fail and terminate instead of doing the operation many times.
Does the problem happen if you try it in a different directory?
What if the input file is renamed to test.mp4?

**Comment by Ivan2309** [comment]
Hi, thanks for the response.

Same problem occurs if I change directory or file name.

From the Leptonica FAQ:
If you see this error, than you have a problem with your leptonica installation - e.g. there is missing support for your image format. Usually this means the relevant image library was not installed properly during leptonica build or there is some configure problem within leptonica.

I've got just about every possible image library inistalled so I'm doubtful that this is the problem. I will carry on checking this side of things though.

Thanks for your assistance.

Ivan.
