### ISSUE TITLE
Here's a quandary: 608 captions in Korean (redux)

### ISSUE THREAD

**Issue by SWalkerTTU** [CCExtractor/ccextractor#477]
Since the last issue [https://github.com/CCExtractor/ccextractor/issues/409](url) was closed (I've been a bit busy lately) the comment asked for the TS file and not the BIN file. I'll attach Dropbox links to the TS file as well as the BIN file. I don't believe the problem is with the extractor, but with the 608 decoder, as legible caption data was extracted, but not converted to SRT.

BIN: [https://www.dropbox.com/s/g72aaw3txzmto8a/DancingQueen.bin?dl=0](url)
TS: [https://www.dropbox.com/s/xvq99nyhj4rymlp/DancingQueen.ts?dl=0](url)

**Comment by SWalkerTTU** [comment]
Correction: these are 708 captions. Still not producing an output, though.

**Comment by Izaron** [comment]
Can you please re-upload your video file?

**Comment by saurabhshri** [comment]
@Izaron Don't click the link, just copy and paste them in the address bar. Those dropbox links are still working. No idea why they redirect to Github 404 page.

https://www.dropbox.com/s/xvq99nyhj4rymlp/DancingQueen.ts?dl=0

**Comment by grave-w-grave** [comment]
Hey, just confirming this is still a thing in 0.84. Going to try to do something hopefully.

**Comment by Izaron** [comment]
Launch ccextractor as `DancingQueen.ts -svc all` and you will get 2 files - first is empty `DancingQueen.srt`, second file contains English words and unrecognized characters from CEA-708 [DancingQueen.p2.svc01.srt](https://gist.github.com/Izaron/34136a8ec8216469c3c3828acdfbe53e) Maybe Korean characters? We are working on CEA-708 complete support

**Comment by SWalkerTTU** [comment]
I did a little work over the weekend on a bespoke Java program just for this file. SBS's (the broadcaster's) encoding is a little strange (and it may not just be SBS — I'd need KBS and MBC raw streams to confirm it): two-byte encoding is based on EUC-KR, but Latin characters in both the 708 and EUC-KR standards only require one byte (ASCII, of course). SBS's encoder pads Latin characters with a null high-order byte. Also, apparently the encoder does not properly set the window.

Edit:

I feel like a total idiot now; I ran the program with -svc "all[EUC-KR]" and got a completely serviceable set of SRT subtitles. I actually did find somewhere that Korean TV uses EUC-KR encoding. I can't remember where now, though, but it is confirmed with these captions from both ccextractor (0.81) and my own little program. As Emily Litella might say, never mind.

**Comment by SWalkerTTU** [comment]
I found it again: the Wikipedia article on EIA-608 mentioned the Norpak extension calling for KS C 5601 encoding (now KS X 1001), one variant of which is EUC-KR. The section on the Norpak extension goes some way to explain the odd encoding: in 608 captions, the entire character system is replaced, and even ASCII characters take two bytes, likely so as to avoid reusing control codes.
