### ISSUE TITLE
TS extract - no subtitles, just teletext 

### ISSUE THREAD

**Issue by mtawheed** [CCExtractor/ccextractor#481]
Hi
I use ccextractor 0.82 ...
I am using the default settings.. I need to extract subtitles from a video recorded from a receiver. 
but unfortunately it could not extract subtitles. 
it produces an srt file with the teletext only. 

I managed to extract the subtitles correctly  for some videos with no errors, 
but with other videos recorded from the same channel, it shows only the teletext instead of the subtitles.

**Comment by mtawheed** [comment]
I uploaded part of the video on the following link:
https://drive.google.com/file/d/0B37yAXh4uCwNd1pRZmR0NkFwd2c/view?usp=sharing

**Comment by cfsmp3** [comment]
Use -tpage to specify the page you want. Not a bug.

**Comment by rboy1** [comment]
Does ccextractor support Teletext in a WTV file? How does one find the page number?

**Comment by rboy1** [comment]
@cfsmp3 Does ccextractor support Teletext in a WTV file? How does one find the page number?

**Comment by cfsmp3** [comment]
Most likely not - only TS streams, I don't think anyone has hooked up the
teletext code with the WTV code. I didn't know WTV was still around to be
honest.
