### ISSUE TITLE
GSOC - Create a OSX GUI

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#5]
CCExtractor is a console program, which is very convenient for a number of things, particularly those involving anything automatic. It also makes it harder to use by regular users in their desktops. For Windows we just have a nice GUI that calls the console program. We'd like to have a GUI written for OSX as well.

**Comment by belwariars** [comment]
I would like to work on this project. Any further guidelines ?

**Comment by canihavesomecoffee** [comment]
I believe this was handled last summer by @kisselef, but I'm not sure if it was finished. Maybe he can give some more information :)
