### ISSUE TITLE
[question] Badly corrupted .SRT file from TiVo units

### ISSUE THREAD

**Issue by dwhe** [CCExtractor/ccextractor#53]
I hope this question here is permissible - I am having trouble with subtitles generated by ccextractor (although I have determined that ccextractor is likely NOT the cause) and could use some guidance on where to take this for resolution.  

I have been observing badly corrupted subtitles/caption files being generated from recordings downloaded from TiVo lately - I have been using Tivo + ccextractor as part of my workflow for years, and while there were frequently the occasional corrupted line (there are almost always about 4 to 5 dialogue lines corrupted), it has recently become very bad.  

Lately the corruption issues with my TiVo downloads have been so bad that nearly every line (99% percent) is corrupted.  The corruption sometimes appear as if part of one (left) half of the subtitles are somehow overlapping the other (right) half. 

Here is an example of the .SRT output:

```32
00:04:37,077 --> 00:04:38,377
SOUNDS GRE!                     

33
00:04:38,379 --> 00:04:40,545
     AND CAN I PRACTICE         
     MY SPANI.                  

34
00:04:57,797 --> 00:04:59,765
WHAT DO YOU THINK?              

35
00:05:00,566 --> 00:05:03,035
            OF COUE! IRS'D LOVE 
            TO GO TOEXIC MO!    

36
00:05:03,037 --> 00:05:04,403
                    YE       
```

I have determined that the issue is NOT a result of the decoding/encoding/ccextractor process (which was my belief previously) as I have found that the corrupted captions appear this way on the .tivo video file itself.  

I previously surmised, with my limited understanding of ccextractor, that perhaps the problem was related to the analog vs. digital captions on the video and that ccextractor was possibly pulling captions from "the wrong one", however, from my efforts in reading up on this, it appears that this hypothesis is unlikely to be correct. 

I welcome anyone's help in identifying why this is happening and where I should bring this for further resolution.

**Comment by hardikchoudhary12** [comment]
Was the .bin file made available in some other forum?(email) Because the dropbox link still doesn't work?

**Comment by cfsmp3** [comment]
On Mon, Mar 9, 2015 at 10:43 AM, hardikchoudhary12 <notifications@github.com
> wrote:

> Was the .bin file made available in some other forum?(email) Because the
> dropbox link still doesn't work?
>
>
> No. Anyway I think the .bin file is not going to help - it's generated
after sorting has happened so if there's a bug in code the .bin would
suffer from it anyway.

**Comment by cfsmp3** [comment]
Closing due to lack of sample - please reopen when a sample is made available.
