### ISSUE TITLE
0.83 Cannot find dll

### ISSUE THREAD

**Issue by captmorn** [CCExtractor/ccextractor#543]
I downloaded and installed version 0.83 onto Windows 10.  When attempting to execute program receive error message that cannot start because libtesseract304d.dll and MSVCR120D.dll are missing from my computer.  Are these needed to run the released version?

**Comment by canihavesomecoffee** [comment]
Hi,

The .83 release didn't fully go as planned, resulting in the above issue.

@cfsmp3 is working on verifying a fix, and will release .84 if the fix proves to be working (most likely by the end of this day, or tomorrow).

**Comment by cfsmp3** [comment]
0.84 released. Please reopen this ticket if you still have problems.
