### ISSUE TITLE
Installer file for 0.84 has an invalid signature

### ISSUE THREAD

**Issue by grave-w-grave** [CCExtractor/ccextractor#583]
Simple. When I try to download the installer for version 0.84, on MS edge, it gives me an error, saying that it's not a safe file, that it has an invalid signature or something, and prevents me from downloading it. I have to override the MS edge security settings to get it to download and run.

http://imgur.com/a/bvRhf

Not yet tested with other browsers, I believe only MS edge gives this error right now.

**Comment by saurabhshri** [comment]
@grave-w-grave Confirmed . 

![sign](https://cloud.githubusercontent.com/assets/12415700/21566235/4992474a-cec7-11e6-938f-07e89b680fa9.PNG)

![sign2](https://cloud.githubusercontent.com/assets/12415700/21566243/61454130-cec7-11e6-8eb1-977455bb392d.PNG)

PS Chrome doesn't perform certificate check while downloading and thus it doesn't appear in Chrome, while Edge does.

**Comment by cfsmp3** [comment]
Looks like the signature is expired (says valid to 04-09-2016), but it's
issued to "Microsoft Corporation". I honestly have no idea what they expect
me to do :-)

**Comment by cfsmp3** [comment]
http://stackoverflow.com/questions/35391691/vs2015-installer-projects-adds-invalid-microsoft-signature-to-msis

Looks like Microsoft doesn't really care about .msi files anymore.

**Comment by cfsmp3** [comment]
GSoC qualification: This issues gives 3 points.

**Comment by himanshu-dixit** [comment]
@cfsmp3 can i take this issue?

**Comment by cfsmp3** [comment]
Sure

**Comment by cfsmp3** [comment]
Created a new install project using InstallShield since clearly Microsoft doesn't want to support the old VS extension to create MSI installers.

https://sourceforge.net/projects/ccextractor/files/ccextractor/0.85/CCExtractorSetup.exe/download
