### ISSUE TITLE
Latest official Windows Binary GUI don't work in clean Windows XP

### ISSUE THREAD

**Issue by Izaron** [CCExtractor/ccextractor#593]
I downloaded 0.82-0.83 binaries in clean Windows XP and I saw that this don't even run
We may need to change something in the Windows Forms project settings

![virtualbox_xp_01_01_2017_22_17_50](https://cloud.githubusercontent.com/assets/5406399/21582624/e86fc5fe-d070-11e6-913c-5f5f29df2a10.png)

**Comment by ManveerBasra** [comment]
You get this error code when you try running an application that requires the ".NET Framework" when your system doesn't have the ".NET Framework" installed.

**Comment by Izaron** [comment]
We have to install .NET only on XP, on newer Windows we have not
