### ISSUE TITLE
linux static build?

### ISSUE THREAD

**Issue by traceypooh** [CCExtractor/ccextractor#597]
hi carlos and crew!

We (archive.org) have been using your great tool more and more these days, and I've been playing around with ffmpeg and  DVB imagery (with attempts to "de-duplicate") and output to tesseract OCR (sound familiar? 8-)
So we've been experimenting with ccextractor as the solution, too.
As such, I've made a static 64-bit compiled version (to avoid various vintages of ubuntu potential issues on our end with .so versions, etc.)
I used Docker and Alpine linux as the making tools to create the binary.
Any interest in this and/or having me/y'all refine it?

[ccextractor-README.txt](https://github.com/CCExtractor/ccextractor/files/681349/ccextractor-README.txt)

**Comment by cfsmp3** [comment]
Hey Tracey,

Seems like a great thing to have, so we're definitely interested in
integrating it when you think it's ready.

About DVB, ffmpeg, and tesseract, we're working a lot on it these
days. Evgeny got tesseract 4.0 working and Alex fixed the DVB timing.
We also have ffmpeg integration to OCR burned-in subtitles. We're
working on a new release - but we want it to be really good so we're
trying to get rid of a few quirks that have been around for some time,
even if some are just corner cases.

Carlos

**Comment by cfsmp3** [comment]
Merged current version (as linux/build-static.sh)
