### ISSUE TITLE
GSOC - Create a Linux GUI

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#6]
OSX GUI	CCExtractor is a console program, which is very convenient for a number of things, particularly those involving anything automatic. It also makes it harder to use by regular users in their desktops. For Windows we just have a nice GUI that calls the console program. We'd like to have a GUI written for Linux as well.

**Comment by belwariars** [comment]
If this issue is now also open, I would like to work in the project of making GUI for Linux.

**Comment by canihavesomecoffee** [comment]
I believe this was handled last summer by @kisselef, but I'm not sure if it was finished. Maybe he can give some more information :)

**Comment by belwariars** [comment]
can anyone guide me on which to work ? I am new and interested in GSoC 2016
