### ISSUE TITLE
Missing return statement.

### ISSUE THREAD

**Issue by sidgairo18** [CCExtractor/ccextractor#607]
No return statement in function -  int write_xtimestamp_header(struct encoder_ctx *context);
in file ccx_encoders_webvtt.c

**Comment by sounak98** [comment]
I want to take this up.

**Comment by cfsmp3** [comment]
This function doesn't exist, maybe it was renamed?

**Comment by sidgairo18** [comment]
izaron changed the function name.

**Comment by cfsmp3** [comment]
To what? Can't fix if can't find it :-)
