### ISSUE TITLE
Bad Memset

### ISSUE THREAD

**Issue by sidgairo18** [CCExtractor/ccextractor#613]
Was it intended to use '0' i.e. asci value 48 or should it be just 0 - the decimal number ?

bad_memset: "memset" with fill value "'0'" (the zero character) in `memset(filename + m, 48, strlen(num) - strlen(temp))`

**Comment by cfsmp3** [comment]
Seems to be left padding a string with '0' so it's probably correct but what file is it?

**Comment by sidgairo18** [comment]
File src/lib_ccx/params.c line 159.

**Comment by cfsmp3** [comment]
This is what I have: 
memset (filename+m,'0',strlen (num)-strlen (temp));

It's correct - we want '0', not 0.
