### ISSUE TITLE
Probably memory leaks

### ISSUE THREAD

**Issue by maxkoryukov** [CCExtractor/ccextractor#639]
I think, there are memory leaks here:

https://github.com/CCExtractor/ccextractor/blob/6c733e96c9aaeb0a76c935da7e11d362afca36f4/src/lib_ccx/dvb_subtitle_decoder.c#L1657-1658

`memcpy` on line 1657 causes overwrites of pointers to the allocated memory:

1. `enc_ctx->prev->buffer`
2. `enc_ctx->prev->subline`
3. `enc_ctx->prev->sbs_buffer`

This memory is allocated in the function `ccx_encoders_common.c::init_encoder`

**Comment by cfsmp3** [comment]
Agreed... we need to have one (or several) clone_contexts functions, such as clone_encoder_context() that creates a copy of allocated memory, etc. With memcpy() we end up with two contexts pointing to the same thing which is going to be a problem, too.

@AlexBratosin2001 this would be yours to look at when possible.

**Comment by maxkoryukov** [comment]
in the mentioned commit (d73b1d11438ec372fb3143edea86926b8cd35f96) I've fixed only the part, related to Sentence Buffer (split to sentences). So, label **fix** should be replaced with **see**, because it is just a workaround for SBS and this bug
