### ISSUE TITLE
Version 0.85 became much slower

### ISSUE THREAD

**Issue by maxkoryukov** [CCExtractor/ccextractor#650]
As a result of latest few commits the current version (in master branch) works much slower ( x10 ):
```
...
Min PTS:         19:04:12:762
Max PTS:         19:14:14:004
Length:          00:10:01:242
Done, processing time = 227 seconds
Issues? Open a ticket here
https://github.com/CCExtractor/ccextractor/issues
```

this is a result of handling `BBC_NEWS_2016-06-21.ts` from sample-videos. Previously it took about 0:57 (about one minute) for this file.

PS: I have disabled my **sbs** feature for this speed test.

**Comment by maxkoryukov** [comment]
I see, that CCE output now contains `<font>` tags for most subtitles. This is the only one difference I see, being a consumer of CCE))))

**Comment by cfsmp3** [comment]
What happens with -nodvbcolor ?

**Comment by maxkoryukov** [comment]
@cfsmp3 , `-nodvbcolor` works as expected (I think so), ccextractor with this option gives pure subs, without `<font>` (I use this for SBS // sentence-split feature), **but** even with `-nodvbcolor` ccextrator 0.8.5 works at the same speed - 10 minutes for 10 minute movie

I have tested only on my laptop, I didn't run/build ccextractor on other hosts.

**Comment by cfsmp3** [comment]
dvdcolor being the default is correct, but of course if sbs doesn't support
colors you can just turn colors off automatically with -sbs.
About speed, is this a windows or linux build?
In windows we now have tesseract 4 which seems a lot slower than 3...

**Comment by maxkoryukov** [comment]
I am on linux. 
I've downloaded the latest commits from master branch, and build it with `/linux/build` script.

**Comment by cfsmp3** [comment]
Seems like it's tesseract. @izaron is in charge of that - for now we'll
revert back to t3 as default.

**Comment by Izaron** [comment]
Yes I saw that Tess 4.0 is slower because of new algorithm, and I'll solve it (change accuracy settings/downgrade to old .lib files and waiting for stable 4.0) But it's for Windows. @maxkoryukov can you check your tesseract version? As far I know, current `tesseract-ocr-dev` from Debian/Ubuntu have version `3.0.4` or `3.0.5`. Or you installed library from sources?

**Comment by maxkoryukov** [comment]
@Izaron 

```bash
$ tesseract -v
tesseract 3.03
 leptonica-1.70
  libgif 4.1.6(?) : libjpeg 8d : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8 : webp 0.4.0
```

As I remember, installed with `apt-get`, not from sources.
