### ISSUE TITLE
Add support of MKV video files

### ISSUE THREAD

**Issue by Izaron** [CCExtractor/ccextractor#656]
Yes, there no TV streams what using .mkv files, but still very many users need to get subtitles from .mkv file, so I suggest adding MKV files support.
It should not be hard. We can get subs from **ffmpeg** library (already in-project) or from **libmatroska** (official for MKV). From linux terminal we can get subtitles from "mkvextract" program, but it is quite uncomfortable and no available for Windows users.

**Comment by canihavesomecoffee** [comment]
*cough* https://mkvtoolnix.download/index.html *cough* works for windows *cough*

**Comment by claunia** [comment]
I think it is a good idea for ccextractor to explore in-stream avc subtitles (I can't remember the name), instead of just extracting subtitles from mkv streams.

In a nutshell:
1.- Support for dvb subtitles interlaced in avc stream inside of matroska files
2.- Support for dvb and/or subtitles as streams inside of matroska files

Currently ccextractor support both subtitle formats outside of matroska files (in PS/TS/ES streams)

**Comment by Izaron** [comment]
I see, there's another program that takes subtitles from .mkv
Is it makes sense to do the same thing in our program for subtitles only? If yes, it should not be difficult :smile:

**Comment by cfsmp3** [comment]
I don't know... can we do anything that is not already done by the official
mkv tools?

**Comment by Izaron** [comment]
(Accidentally closed)
No, as far I checked. Only automation of taking subs, but seems it's not worth it, if we want not to reinventing bycicle.

**Comment by Izaron** [comment]
In general, there are other programs that also take captions fron certain types of files. But I think we must have some limit, after which we can tell the user: "No, it is not advisable to add it in the program, when this is already there in other app, so please use something other". I'm not sure where we have this limit.

**Comment by claunia** [comment]
@Izaron afaik, for the in-video subtitle stream (ceasomething? sorry I can't remember) ccextractor is the only software I've found able to extract them. And if that stream is inside a mkv it requires the prestep of demuxing the video track just for that.

I think that pretty much should be part of ccextractor, just adding a demuxer for an already supported subtitle format, is inside the scope of this project.

Setting a limit like you suggest, is in my opinion, something that should be done only for far far away requests. Adding support for anything subtitle related, is near, making ccextrator be a video editing application is far far away.
Nonetheless you can always use the "interesting, but I won't spend time on it, do it yourself if you wish" telling.

But that's just my opinion.

**Comment by cfsmp3** [comment]
This is matter of "is there any software that can do it already" or not :-)
If not, then we should do it - and by "we" I don't mean Izaron specifically
or myself, but rather, anyone who feels like it. Same as any other feature
:-)
If there's a real use case I don't have any objections to add .mkv support.
I didn't know there existed .mkv files in with the closed captions are not
a separate subtitle track.

On Sun, Jan 22, 2017 at 12:54 PM, Natalia Portillo <notifications@github.com

**Comment by claunia** [comment]
@cfsmp3 "is there any software that can do it already" afaik, no

I didn't know either but I can imagine there is a lot of people that just don't even know this was possible. I didn't. I saw a strange line getting information from the mkv with ffmpeg in the video stream, and it ended being a CEA subtitle.

**Comment by Izaron** [comment]
@claunia Do you have any sample .mkv videos with closed captions what mkvtoolnix can't take? I have not met with such.
Generally, such a file is theoretically possible, but practically? Can we met such files not specially, in real Internet videos?

**Comment by claunia** [comment]
@Izaron sorry, I convert all videos to .mp4 and I've only encountered it once

**Comment by Izaron** [comment]
Imported self-written Matroska decoder https://github.com/CCExtractor/ccextractor/pull/704
