### ISSUE TITLE
Windows and multicast

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#668]
We're hitting exactly this problem:

http://stackoverflow.com/questions/6140734/cannot-bind-to-multicast-address-windows

Suppose this real scenario: We have a number of multicast streams. They are in different addresses, for example 

239.168.100.1:5000
239.168.100.2:5000

This means that we cannot just bind to any interface (0.0.0.0) on port 5000, because then we get things mixed up.

The obvious solution is to bind to the complete IP+port. In linux this works fine, but Windows says "IP address not available", i.e. you cannot bind the socket to the multicast IP address.

For now (because I needed to get it working) I've done the following:

```
#if _WIN32
	// Doesn't seem correct, if there's more than one multicast stream with the same
	// port number we get corruption - IP address needs to be specified, but 
	// in Windows we get an error 10049 (cannot bind).
	// http ://stackoverflow.com/questions/6140734/cannot-bind-to-multicast-address-windows
	servaddr.sin_addr.s_addr = htonl(IN_MULTICAST(addr) ? INADDR_ANY : addr);
#else
	servaddr.sin_addr.s_addr = htonl(addr);
#endif
```
Which solves the problem in linux and leaves Windows behaving as before.

It's definitely not the right solution.
http://stackoverflow.com/questions/10692956/what-does-it-mean-to-bind-a-multicast-udp-socket

I'm assigning this to @Izaron since he did the last network changes if I recall correctly.

**Comment by cfsmp3** [comment]
GSoC: This issue gives 2 qualification points.

**Comment by sagark123** [comment]
Having more than 1 interfaces in windows is a problem as windows tends to pick up the wrong address.We can get all the interfaces by using getifaddrs() and selecting the required interface

'struct ifaddrs *addrs,*tmp;

getifaddrs(&addrs);
tmp = addrs;

while (tmp)
{
    if (tmp->ifa_addr && tmp->ifa_addr->sa_family == AF_PACKET)
        printf("%s\n", tmp->ifa_name);

    tmp = tmp->ifa_next;
}

freeifaddrs(addrs);`
