### ISSUE TITLE
ccextractor doesn't work on .ts file in 708 mode

### ISSUE THREAD

**Issue by barun511** [CCExtractor/ccextractor#674]
When I run ./ccextractor against a .ts file, with default options, I get the following error messages.
[ccextractoroutput.txt](https://github.com/CCExtractor/ccextractor/files/737255/ccextractoroutput.txt)

If I run with the -608 option I get the same error messages, but the subtitles are 'somewhat' extracted. Here's a copy of the new output.
[ccextractoroutput.txt](https://github.com/CCExtractor/ccextractor/files/737329/ccextractoroutput.txt)

I'm running Linux Mint Cinnamon 18, if that helps.

**Comment by cfsmp3** [comment]
-608 (and -708) enable *debug* output. The actual output is written to disk.
If you want it on console use -stdout.
