### ISSUE TITLE
GSoC qualification: Make CCExtractor more linux standard compliant

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#678]
This task gives you enough points to qualify (but remember that your proposal still needs to be good, etc).

CCExtractor is written in pure C, it uses external hard-linked libraries and it is designed to be portable to different platforms. Because of that we have multiple building scripts which somebody should maintain. The task is to create

    Autoconf scripts
    Man pages
    .tgz, .deb, .rpm, .tar.xz (archlinux) installation packages

**Comment by Izaron** [comment]
We just need to build package from built binary from linux/build-static.sh
.deb - just rewrite outdated https://github.com/CCExtractor/ccextractor/blob/master/package_creators/debian.sh remove REQUIRES and so on
.rpm - http://meinit.nl/creating-rpm-some-binary, but we can also build .rmp from **Debian/Ubuntu**

**Comment by Izaron** [comment]
Would you like to have official packages for the most popular linux distros?
I mean, if everybody will be able to launch Linix distro, write in terminal line as `sudo apt-get install ccextractor` and get binary? :)

**Comment by Izaron** [comment]
https://www.linux.com/learn/easy-package-creation-checkinstall
Can be helpful

**Comment by alexandrumc** [comment]
I'm starting to do it.

**Comment by pranavsid98** [comment]
I am interested in this issue. I would like to work on this.

Pranav

**Comment by techfreakworm** [comment]
I am working on autoconf scripts for ccextractor and I have a slight problem. In Makefile.am (with non-recursive approach) I have set, "AM_LDFLAGS = -lm -zmuldefs -ltesseract -llept". But still the build crashes with "/usr/bin/ld: src/gpacmp4/av_parsers.o: undefined reference to symbol 'trunc@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line"
Any idea where I might be wrong?

**Comment by xvkdev** [comment]
To make it clear - we don't want to pregenerated packages, man, etc: We want scripts that generate them automatically, otherwise we'd been stuck with old versions really quickly.

**Comment by cfsmp3** [comment]
To make it clear - we don't want to pregenerated packages, man, etc: We want scripts that generate them automatically, otherwise we'd been stuck with old versions really quickly.

**Comment by fandango-** [comment]
Just wanted to add that Arch already has a package for ccextractor in the AUR. So, users of Arch and Arch-based distributions can install it using yaourt. Link: https://aur.archlinux.org/packages/ccextractor/
In fact, I'd be surprised if it didn't actually - I can't remember the last time I didn't do
$ yaourt -S \<package-name\>
to install packages I use.
However, just to be clear, an official .pkg.tar.xz / .pkg.tar.gz would still be useful if, for some reason, the user doesn't have yaourt installed and only uses pacman. It would also be useful in the case that the AUR package stops being maintained or is removed (this is very rare, but a possibility).

**Comment by shucon** [comment]
Is this issue still open?

**Comment by cfsmp3** [comment]
@shucon Not sure if the work was completed. Take a look and let us know :-)

**Comment by shucon** [comment]
I think the .deb file is broken @cfsmp3 should I go ahead with it?

**Comment by cfsmp3** [comment]
broken how?

**Comment by shucon** [comment]
When I run the .deb file it doesn't complete the installation and exits after showing some errors.

**Comment by cfsmp3** [comment]
Which errors? :-) Full output.
