### ISSUE TITLE
Can't build CMake project with additional libs

### ISSUE THREAD

**Issue by Izaron** [CCExtractor/ccextractor#692]
CLion uses CMake, and I can't build it, for example, with OCR
I have installed tesseract and leptonica developer libraries
```
option (WITH_OCR "Build with OCR (Optical Character Recognition) feature" OFF)
```
When I trying to change "OFF" to "ON" and clean cmake and cmake folder, I get an errors
```
<...>
compilation terminated.
/bin/sh: -I/usr/include/leptonica: No such file or directory
lib_ccx/CMakeFiles/ccx.dir/build.make:62: recipe for target 'lib_ccx/CMakeFiles/ccx.dir/__/zvbi/decoder.c.o' failed
gmake[3]: *** [lib_ccx/CMakeFiles/ccx.dir/__/zvbi/decoder.c.o] Error 127
/bin/sh: -I/usr/include/leptonica: No such file or directory
gmake[3]: *** Waiting for unfinished jobs....
<...>
```

I tried change code in this part:

```
#if (WITH_OCR)
  find_package(PkgConfig)

  pkg_check_modules (TESSERACT REQUIRED tesseract)
  pkg_check_modules (LEPTONICA REQUIRED lept)

  set (EXTRA_LIBS ${EXTRA_LIBS} ${TESSERACT_LIBRARIES})
  set (EXTRA_LIBS ${EXTRA_LIBS} ${LEPTONICA_LIBRARIES})
  include_directories (${TESSERACT_INCLUDE_DIRS} ${LEPTONICA_INCLUDE_DIRS})
  set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DENABLE_OCR")
#endif (WITH_OCR)
```
But got very strange behavior - this includies and define `ENABLE_OCR` is available only in ccextractor.c file.
Can anyone fix it? I would be very glad.

**Comment by Izaron** [comment]
linux/build and linux/builddebug works very well with all additional libraries.

**Comment by cfsmp3** [comment]
GSoC qualification: 2 points

**Comment by Izaron** [comment]
@cfsmp3 and others who have any serious experience in CMake
Can you see this diff and check commit by commit? https://github.com/CCExtractor/ccextractor/compare/master...Izaron:cmake-ocr?expand=1 (have not requested pull yet)
There was one missed library, using of static libraries and more small bugs as seems to me

https://github.com/CCExtractor/ccextractor/blob/master/docs/using_cmake_build.txt - see screenshot of current master CMake
![screenshot from 2017-02-22 16-25-38](https://cloud.githubusercontent.com/assets/5406399/23214062/d61a152e-f926-11e6-85aa-b12fcaaba4f3.png)

With my changes it builds OK...

**Comment by Izaron** [comment]
If we will create .deb/.rpm package from binary built my branch, will it require tesseract, ffmpeg and other deps? Since I erased "STATIC" from libraries.

**Comment by Izaron** [comment]
Also, still can't get out what "STATIC" in linker mean.
As I understand, with static libs we should get working binary without any dependencies? But with both STATIC and non-static I get in virtual machine:
```
./ccextractor: error while loading shared libraries: libpng16.so.16: cannot open shared object file: No such file or directory
./ccextractor: error while loading shared libraries: libtesseract.so.3: cannot open shared object file: No such file or directory
```
Can you help me?

**Comment by cfsmp3** [comment]
I've never used CMake, this was Anshul's work I think.
