### ISSUE TITLE
Timing issues from teletext with bogus PTS (regressed in 0.85)

### ISSUE THREAD

**Issue by hurda** [CCExtractor/ccextractor#695]
Between 0.84 and 0.85 something changed regarding processing teletext which has dodgy PTS-values and creating the subtitle-timestamps.

Sample: http://www.mediafire.com/file/j4ej0akioqyklxv/teletext_timing_wrong_pts_cce0.85.zip

0.84 (good):
```
1
00:00:02,040 --> 00:00:04,480
Oh, ich dachte, Sie wären schon weg.

2
00:00:04,560 --> 00:00:06,360
<font color="#ffff00">Und ich gehe jetzt auch.</font>

3
00:00:10,720 --> 00:00:11,880
Hey, Jackie.

4
00:00:11,960 --> 00:00:12,960
Ich ... ich habe was für dich.
```

0.85 (bad):
```
1
07:09:30,010 --> 07:09:32,449
Oh, ich dachte, Sie wären schon weg.

2
07:09:32,530 --> 07:09:34,329
<font color="#ffff00">Und ich gehe jetzt auch.</font>

3
07:09:38,690 --> 07:09:39,849
Hey, Jackie.

4
07:09:39,930 --> 07:09:40,929
Ich ... ich habe was für dich.
```

The difference of the timestamps of 0.85 compared to 0.84 can be between some seconds and several hours.

**Comment by cfsmp3** [comment]
I think @AlexBratosin2001 did some work on the teletext timing.

**Comment by hurda** [comment]
Thanks, fixed.
