### ISSUE TITLE
Few lines missing from output of .bin file [sample attached]

### ISSUE THREAD

**Issue by saurabhshri** [CCExtractor/ccextractor#699]
While working on another issue, I created a .bin file from a sample (https://sampleplatform.ccextractor.org/sample/67). 

When extracting subs from .bin file, the ending few lines are missing, while they are perfectly extracted from original file.

Original :

```
12
00:00:52,140 --> 00:00:54,279
Mogu, your bag!

13
00:00:54,380 --> 00:00:56,679
<font color="#00ffff">(Strains)</font>

14
00:00:56,780 --> 00:00:58,979
<font color="#00ffff">It's strong!</font>

```

From .bin of above sample (http://gsocdev3.ccextractor.org/~saurabhshri/67.bin) : 

```
12
00:00:52,140 --> 00:00:54,279
Mogu, your bag!

```

I created bin using : `ccextractor -ts -pn 578 -out=bin -o 67.bin 67` where 67 was the name of sample.

EDIT : Corrected the .bin file. Previous file had incorrect timings.

**Comment by cfsmp3** [comment]
2 GSoC points.

**Comment by saurabhshri** [comment]
Closing through #725 . The issue appears to be resolved with attached file.
Note : Timing is off by few milliseconds (but they may be for good, maybe someone can check on it).
