### ISSUE TITLE
Levenshtein-parameters missing from Usage-section

### ISSUE THREAD

**Issue by hurda** [CCExtractor/ccextractor#701]
Parameters: https://github.com/CCExtractor/ccextractor/blob/dbad5f4cda15303af784a06788e039dd81834229/docs/CHANGES.TXT#L360

params.c: https://github.com/CCExtractor/ccextractor/blob/e79506b303d7b250518aaadf65addb7a859c7b5b/src/lib_ccx/params.c#L1740

**Comment by cfsmp3** [comment]
Fixed. 
1 GSoC point awarded to kapilkd13.
