### ISSUE TITLE
[QUESTION] Two Korean DTV TS files recorded using same PVR. CCExtract is working with only one of them. 

### ISSUE THREAD

**Issue by rokatri** [CCExtractor/ccextractor#713]
CCExtractor version (using the --version parameter preferably) : 0.85

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X ] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X ] I have checked that the issue I'm posting isn't already reported.
- [X ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [X ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [X ] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [X] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [X] NO | [ ] YES 
- What platform did you use? [X] Windows - [ ] Linux - [ ] Mac
- What where the used arguments? -noru -nomyth -noteletext -out=txt -svc all[EUC-KR]`

**Video links**
This is the one I can extract caption. ("AVC Video stream as defined in ITU-T Rec. H.264 |ISO/IEC 14496-10 Video".)
https://drive.google.com/file/d/0B0olGw-GHirhQkJvR042bVpVczg/view?usp=sharing

This is the one I can not extract caption. ("ITU-T Rec.H.262|ISO/IED 13818-2 Viideo or ISO/IEC 11172-2 constrained parameter video stream")
https://drive.google.com/file/d/0B0olGw-GHirhNlZUbG42R2tuNDQ/view?usp=sharing

I have two Korea DTV recording I took recently. Both contains closed caption. I can extract the closed caption from one file, but I can't from the other file.

**Comment by cfsmp3** [comment]
GSoC qualification: 3 points

**Comment by harrynull** [comment]
Some info that may be helpful:
The one that cannot be extracted is identified as MPEG2 with no PAT/PMT info.
I've used Avidemux to generate PAT/PMT but the issue still presents.
Neither VLC nor Potplayer can show subtitles in neither videos, but it could be a bug of video player because CCExtractor can extract the first video correctly.
Mediainfo says it has CEA-708 stream, but in function `do_cb`, `cc_type` is 0 or 1 (which is CEA-608 I think). As a result, the program never enters CEA-708.

**Comment by cfsmp3** [comment]
Keep in mind that CEA-608 and CEA-708, in transport streams, are bundled
together - so you will see CEA-608 data first, then CEA-708. So you have to
check out the complete block, not just the first two bytes.

**Comment by cfsmp3** [comment]
Closing since seems to be the same as this one:
https://github.com/CCExtractor/ccextractor/issues/805
