### ISSUE TITLE
BUG: Does not extract forced and non-forced tracks for same language

### ISSUE THREAD

**Issue by SteveMak** [CCExtractor/ccextractor#718]
[BUG]
CCExtractor version : 0.85
[X] I absolutely love CCExtractor, but have not contributed previously.
(extensive user!)

- Is this a regression (did it work before)? [X] NO | [ ] YES
- What platform did you use? [X] Windows - [ ] Linux - [ ] Mac
- What where the used arguments?  --gui_mode_reports  -autoprogram  -out=srt -ru2 -bom -utf8 --nofontcolor -trim -autodash --norollup --notypesetting [+input files]

When a video file has both a forced and non-forced subtitle (or CC) tracks, CC extractor does not extract both. This is the ideal state. In the sample video file, when viewed by VLC Media Player, there are 2 CC tracks:
(1) Subtitle Track 1 [English] is actually forced English subtitles. Go to 2m:40s and you'll see Italian audio appear as forced English subtitles.
(2) Subtitle Track 8 [] is English for the entire movie.

Note: In my example, Track 8 is not named.

Suggestion: If the user's language is English, then...
(1) Extract all English tracks (could be multiple tracks with English as the name)
(2) Extract all tracks that don't have a name (such as my Track 8 example)

**Comment by Izaron** [comment]
Can you run CCExtractor twice with different arguments for getting both files?
Can you give link to the video file?

**Comment by SteveMak** [comment]
I have not been able to figure out how to extract the other track.

 

Also, it is not practical for me to do so. I am in the midst of processing several hundred files, so I do not process each one individually. I throw a large batch at CCExtractor, and hope that it does the right thing. In almost all cases it does. Having to manually check each file would take a considerably longer time to work through a batch. I’d be looking for another tool to avoid that.

 

Carlos has a copy of the file. It’s copyrighted, so he’s being careful about keeping it restricted to those who need to work with it.

 

-Steve

**Comment by cfsmp3** [comment]
GSoC qualification: 4 points
Link to file mentioned in slack (#general)

**Comment by mahalwal** [comment]
@SteveMak @cfsmp3 Can you please provide the link to sample file?

**Comment by SteveMak** [comment]
It’s been so long since I reported this, I don’t know which file it is, or whether I still have it.

 

-Steve

**Comment by cfsmp3** [comment]
Closing this issue then.
