### ISSUE TITLE
[PROPOSAL] Drop a folder into the Input Files

### ISSUE THREAD

**Issue by SteveMak** [CCExtractor/ccextractor#719]
[PROPOSAL]
CCExtractor version : 0.85
[X] I absolutely love CCExtractor, but have not contributed previously.
(extensive user!)

Is this a regression (did it work before)? [X] NO
Platform: [X] Windows
Arguments? --gui_mode_reports -autoprogram -out=srt -ru2 -bom -utf8 --nofontcolor -trim -autodash --norollup --notypesetting [+input files]

I sometimes do extensive CC/Subtitle extraction and transcoding for large batches of files. The sources are organized in a hierarchy of folders. It would be helpful if I could just drag and drop the parent folder into the Input Files tab.

Today, I must do the following:
(1) Using the parent folder: Find .mp4 files (finds all *.mp4 files in all subfolders)
(2) Drag them to the Input Files tab
(3) Using the parent folder: Find .m4v files (finds all *.m4v files in all subfolders)
(4) Drag them to the Input Files tab
CCExtractor then does the right thing, extracting the tracks to their correct locations.

**Comment by cfsmp3** [comment]
GSoC qualification: 3 points.
