### ISSUE TITLE
A 0x00 in the middle of a .srt

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#720]
00000000  31 0a 30 30 3a 30 30 3a  34 30 2c 39 34 30 20 2d  |1.00:00:40,940 -|
00000010  2d 3e 20 30 30 3a 30 30  3a 34 33 2c 30 30 38 0a  |-> 00:00:43,008.|
00000020  **00** 0a 4a 55 44 47 45 20  4d 49 4c 49 41 4e 3a 20  |..JUDGE MILIAN: |
00000030  4e 4f 57 2c 20 57 48 41  54 20 49 53 20 59 4f 55  |NOW, WHAT IS YOU|

Obviously causes a bunch of problems. No idea how it got there. 

No input file available, it was a live stream.

**Comment by cfsmp3** [comment]
GSoC qualification: 4 points.

**Comment by gray-v** [comment]
Wait if there's no sample or input file how am I supposed to solve this augh

**Comment by cfsmp3** [comment]
Closing until we see this again. Could be fixed already, can't reproduce.
