### ISSUE TITLE
[PROPOSAL] Add support for .mcc files

### ISSUE THREAD

**Issue by madykstra** [CCExtractor/ccextractor#733]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : **0.85**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X ] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X ] I have checked that the issue I'm posting isn't already reported.
- [X ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [X ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [X ] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used CCExtractor.
- [X ] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [X ] NO | [ ] YES - *please specify the last known working version*
- What platform did you use? [X ] Windows - [X ] Linux - [ ] Mac
- What where the used arguments? `-autoprogram`

**Video links**

Please make the affected input file available for us (no screenshots, those don't help!). Public links to Dropbox, Google Drive, etc, are all fine. If it is not possible to make it available publicly, send us a private invitation (both Dropbox and Google Drive allow that). In this case we will download the file and upload it to the private developer repository.

Do *not* upload your file to any location that will require us to sign up or endure a wait list, slow downloads, etc. If your upload expires make sure you keep it active somehow (replace links if needed). Keep in mind that while we go over all tickets some may take a few days, and it's important we have the file available when we actually need it.

**Additional information**

I saw a single reference to an .mcc file in the GSOC - Finish CEA-708 support #3  issue.
The mcc file format was created by MacCaption, now owned by Telestream, and is supported and used by Adobe Premiere.  In the MacCaption user guide they say this "The MCC format is an open specification and free for any hardware or software manufacturer to use. Please contact Telestream for more information."  I submitted a support request at:
http://www.telestream.net/telestream-support/captioning/contact-support.htm
and they sent me the white paper right away.  I did not know if it would be proper for me to drop their document here without permission, so I've included the link to request it yourself.
The rationale for the .mcc file format was to support the added functionality of CEA-708 captions, since other file formats only supported 608.  Since finishing CEA-708 support is a major push for the CCExtractor project, I figured this file format could be integral in this implementation.  In its simplest form, an mcc file is made up of lines of timecode, each followed by a VANC line 9 CDP packet.  As such, it contains both 708 and 608 information.  It seems to suggest that it is not required to be able to decode the 708 data, just extract it and place it.  I think the CCExtractor .bin file already stores raw CDP packet data, so hopefully this is not too far of a divergence.  Its use in Adobe Premiere should offer a wide variety of testing and examples.

PS: Make sure you set an alert in GitHub so you get notifications about your ticket. We may need to ask questions and we do everything inside GitHub's system.

**Comment by cfsmp3** [comment]
Closing since this was already merged
