### ISSUE TITLE
[PROPOSAL] Provide plugin for ffmpeg?

### ISSUE THREAD

**Issue by qacollective** [CCExtractor/ccextractor#736]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : **X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X ] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X ] I have checked that the issue I'm posting isn't already reported.
- [X ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [X ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [X ] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [X ] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [ ] NO | [ ] YES - *please specify the last known working version*
- What platform did you use? [ ] Windows - [ ] Linux - [ ] Mac
- What where the used arguments? `-autoprogram`

**Video links**

Please make the affected input file available for us (no screenshots, those don't help!). Public links to Dropbox, Google Drive, etc, are all fine. If it is not possible to make it available publicly, send us a private invitation (both Dropbox and Google Drive allow that). In this case we will download the file and upload it to the private developer repository.

Do *not* upload your file to any location that will require us to sign up or endure a wait list, slow downloads, etc. If your upload expires make sure you keep it active somehow (replace links if needed). Keep in mind that while we go over all tickets some may take a few days, and it's important we have the file available when we actually need it.

**Additional information**

Love CCEXTRACTOR - hands down is the best tool for the job.  While using it and ffmpeg intensively over the past few days, I pondered why ffmpeg's subtitle support was so average (or badly documented?) and how much both ffmpeg and CCEXTRACTOR might benefit from ffmpeg being able to use CCEXTRACTOR code - probably as a subtitle codec.  ffmpeg users would benefit from having just one more amazing feature already installed with standard ffmpeg installation.  CCEXTRACTOR may benefit from having so many other possible users and therefore contributors to their efforts. 

PS: Make sure you set an alert in GitHub so you get notifications about your ticket. We may need to ask questions and we do everything inside GitHub's system.

**Comment by cfsmp3** [comment]
FFmpeg is welcome to take our code and integrate, as routinely happens with open source :-) 

We won't do it ourselves though, last time we tried to get something merged into FFmpeg it was a lot of work and in the end we had to give it.
