### ISSUE TITLE
[BUG] building in Ubuntu

### ISSUE THREAD

**Issue by rriobs** [CCExtractor/ccextractor#749]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : **X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [ ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [ ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used CCExtractor.
- [x] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [x] NO | [ ] YES - *please specify the last known working version*
- What platform did you use? [ ] Windows - [x] Linux - [ ] Mac
- What where the used arguments? `-autoprogram`

**Video links**

Please make the affected input file available for us (no screenshots, those don't help!). Public links to Dropbox, Google Drive, etc, are all fine. If it is not possible to make it available publicly, send us a private invitation (both Dropbox and Google Drive allow that). In this case we will download the file and upload it to the private developer repository.

Do *not* upload your file to any location that will require us to sign up or endure a wait list, slow downloads, etc. If your upload expires make sure you keep it active somehow (replace links if needed). Keep in mind that while we go over all tickets some may take a few days, and it's important we have the file available when we actually need it.

**Additional information**

{issue content here, replace this line with your issue content}

PS: Make sure you set an alert in GitHub so you get notifications about your ticket. We may need to ask questions and we do everything inside GitHub's system.

**Comment by rriobs** [comment]
Trying to tun ./autogen and ./configure.Works well on fedora but i get the following error in ubuntu: 
configure: error: Package requirements (lept) were not met:

No package 'lept' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables lept_CFLAGS
and lept_LIBS to avoid the need to call pkg-config.

**Comment by saurabhshri** [comment]
Hello @rriobs ! Please make sure you've met all the dependencies listed here : https://github.com/CCExtractor/ccextractor#compiling (specifically leptonica, as per the error message).

If you already have them installed, please make sure the environment variables are set so that CCExtractor can find them.

You may also use `build.sh` in the `/linux` directory to build CCExtractor as well.

**Comment by rriobs** [comment]
Hi.am really stuck here.could you please provide an example instance of hoe to set up the environment variable? Am trying export lept_LIBS="/usr/lib/" but it is not working.I will appreciate your help.thank you

**Comment by saurabhshri** [comment]
@rriobs Have you tried doing `sudo apt-get install -y libleptonica-dev` ?

**Comment by rriobs** [comment]
yes libleptonica-dev is installed.

**Comment by rriobs** [comment]
it worked well in frdora...it is ubuntu whichh has issues.Am using 14.04

**Comment by anshul1912** [comment]
In older Ubuntu this problem was there, because pkg-config of leptonica was
not correct.

Can you try uninstalling leptonica given by apt-get and manually installing
though tar file given on leptonica site.

Thanks
Anshul Maheshwari

**Comment by rriobs** [comment]
Hi Anshul
I had to to compile both leptonica and tesseract from source for the compilation to work.Thank you very much for your assistance.
