### ISSUE TITLE
[BUG] Can't extract WEBVTT Closed Captions

### ISSUE THREAD

**Issue by jordiNavines** [CCExtractor/ccextractor#753]
Please prefix your issue with one of the following: BUG.

CCExtractor version (using the --version parameter preferably) : 0.85

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [X] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X]):**

- [] I have never used CCExtractor.
- [X] I have used CCExtractor just a couple of times.
- [X] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [ ] NO | [X] YES - I've tried in older version and I works in versions 0.80 and 0.81
- What platform did you use? [ ] Windows - [ ] Linux - [X] Mac
- What where the used arguments? `-out=webvtt`

**Video links**
You can find and download the video here: https://dwo3ckksxlb0v.cloudfront.net/test/jordi/video.mp4

Please make the affected input file available for us (no screenshots, those don't help!). Public links to Dropbox, Google Drive, etc, are all fine. If it is not possible to make it available publicly, send us a private invitation (both Dropbox and Google Drive allow that). In this case we will download the file and upload it to the private developer repository.

Do *not* upload your file to any location that will require us to sign up or endure a wait list, slow downloads, etc. If your upload expires make sure you keep it active somehow (replace links if needed). Keep in mind that while we go over all tickets some may take a few days, and it's important we have the file available when we actually need it.

**Additional information**

Hi, 

I am trying to extract the WEBVTT closed captions from a mp4 file. I can successfully extract the closed captions in other formats (srt, smptett, ttxt, txt), but when I try to extract with the VTT format it gives me a Segmentation fault: 11

The command I use to extract the closed captions is: ccextractor video.mp4 -out=webvtt -o test.vtt

And this is what I am getting from ccextractor:
```
CCExtractor 0.85, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: video.mp4
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: Auto] [Debug: No] [Buffer input: No]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .vtt] [Encoding: UTF-8] [Delay: 0] [Trim lines: No]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]

-----------------------------------------------------------------
Opening file: video.mp4
Detected MP4 box with name: ftyp
Detected MP4 box with name: free
Detected MP4 box with name: mdat
File seems to be a MP4
Analyzing data with GPAC (MP4 library)
Creating test.vtt
Opening 'video.mp4': ok
Track 1, type=vide subtype=avc1
Track 2, type=soun subtype=MPEG
MP4: found 2 tracks: 1 avc and 0 cc
XDS: ContentAdvisory: US TV Parental Guidelines. Age Rating: None
XDS: 
XDS: CGMS: One generation of copies can be made
XDS: APS: No APS
XDS: Redistribution Control Descriptor: 0
100%  |  01:32Segmentation fault: 11
```
I've been trying older versions and this used to work with versions 0.80 & 0.81. 
From the version 0.82 I am always getting Segmentation fault.

Is there any known issues with the extraction of the VTT closed captions? Am I doing anything wrong with the command?

Many thanks, 
kind regards

PS: Make sure you set an alert in GitHub so you get notifications about your ticket. We may need to ask questions and we do everything inside GitHub's system.

**Comment by saurabhshri** [comment]
Some notes :

In https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/ccx_encoders_webvtt.c#L243 , it tries to access `timing` variable of type `ccx_common_timing_ctx` belonging to `encoder_ctx`which is uninitialised, resulting in segfault.

**Comment by saurabhshri** [comment]
Hello @jordiNavines ! Thank you for reporting the bug. Please try again with the latest code in the repository. Feel free to re-open the issue if you think it's not resolved or open a new issue if you find one! :)
