### ISSUE TITLE
CCExtractor says no closed captions found in a EIA TS file

### ISSUE THREAD

**Issue by rboy1** [CCExtractor/ccextractor#757]
Using the latest 0.85b build of ccextractor, I tried a sample TS video file with EIA closed captions:

The file can be downloaded from here (sample)
http://streams.videolan.org/streams/ts/Closed%20Caption%20EIA.ts

CCExtractor says no closed captions found

```
C:\cce>ccextractorwinfull.exe "..\Closed Caption EIA.ts"

CCExtractor 0.85, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: ..\Closed Caption EIA.ts
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: Auto] [Debug: No] [Buffer input: Yes]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .srt] [Encoding: UTF-8] [Delay: 0] [Trim lines: No]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]

-----------------------------------------------------------------
Opening file: ..\Closed Caption EIA.ts
File seems to be a transport stream, enabling TS mode
Analyzing data in general mode
Creating ..\Closed Caption EIA.srt

Number of NAL_type_7: 0
Number of VCL_HRD: 0
Number of NAL HRD: 0
Number of jump-in-frames: 0
Number of num_unexpected_sei_length: 0

Total frames time:        00:00:00:000  (0 frames at 29.97fps)
Done, processing time = 1 seconds
Issues? Open a ticket here
https://github.com/CCExtractor/ccextractor/issues
No captions were found in input.
```

**Comment by rboy1** [comment]
Any thoughts?

**Comment by canihavesomecoffee** [comment]
Media info says there's a CC stream, but it has no size:

![image](https://user-images.githubusercontent.com/7365586/28514042-d7d71ec6-7058-11e7-85ea-abe0535e9b49.png)

That might explain why CCExtractor cannot extract anything...

**Comment by saurabhshri** [comment]
VLC on the other hand displays the captions just fine, it detects 4 closed caption streams. This looks similar to : https://github.com/CCExtractor/ccextractor/issues/723#issuecomment-292806654 .

**Comment by iha** [comment]
I don't think this information about stream size from mediainfo makes sense with closed captions, there is another file in vlc samples [0] and the stream size is zero, but ccextractor works. Anyway I'm working in this bug.

[0] http://streams.videolan.org/streams/ts/atsc-cea-708-dtvcc-and-cea-608.ts

**Comment by xvkdev** [comment]
From Ivan at GCI:

************
After some work on ccextractor code I found out that the error comes from general_loop.c
I dowloaded file with 0 stream size from issue in task and found out that ccextractor doesn't extract subtitles from problem file because in this particular file pid != datalist->stream_pid. So the obvious solution is to change:
* Error: int pid = get_best_stream(ctx->demux_ctx); 
* Right output: int pid = datalist->stream_pid;
https://github.com/CCExtractor/ccextractor/blob/be34781a64f7c1343ea4c4a91cba0723fbfb31bb/src/lib_ccx/general_loop.c#L909
*************

I'm assigning this to @anshul1912 I think that was his code... Anshul, can you take a look?

**Comment by MakarovGCI2018** [comment]
After some work on ccextractor code I found out that the error comes from general_loop.c
I dowloaded file with 0 stream size from issue in task and found out that ccextractor doesn't extract subtitles from problem file because in this particular file pid != datalist->stream_pid. So the obvious solution is to change:
* Error: int pid = get_best_stream(ctx->demux_ctx); 
* Right output: int pid = datalist->stream_pid;
https://github.com/CCExtractor/ccextractor/blob/be34781a64f7c1343ea4c4a91cba0723fbfb31bb/src/lib_ccx/general_loop.c#L909

**Comment by cfsmp3** [comment]
@anshul1912 I think this was your code, can you take a look?

**Comment by MakarovGCI2018** [comment]
@cfsmp3 please note that we use get_best_stream function only in the place I described above. So if @anshul1912 verify this changes we can simple delete this function from ccextractor code completely. By the way, my PR is ready and I'm waiting for changes verification.

**Comment by cfsmp3** [comment]
@MakarovGCI2018 if we deleted that function then most streams wouldn't work. A requirement of FIXES is not to break more than your fix :-)

**Comment by anshul1912** [comment]
Let me explain that function.
Get_best_stream keeps the  priority of subtitle when multiple subtitles are present, so removing it will work for you but then you mess with priority, you will always select whichever is on top. So I would say no to remove that function, I would suggest you to find why that function is not working. If some subtitle are wrongly reported then we always have option to pass from cmd line which one is needed for selection


int get_best_stream(struct ccx_demuxer *ctx)

{

	struct cap_info* iter;

	list_for_each_entry(iter, &ctx->cinfo_tree.all_stream, all_stream, struct cap_info)

	{

		if(iter->codec == CCX_CODEC_TELETEXT)

			return iter->pid;

	}

	list_for_each_entry(iter, &ctx->cinfo_tree.all_stream, all_stream, struct cap_info)

	{

		if(iter->codec == CCX_CODEC_DVB)

			return iter->pid;

	}

	list_for_each_entry(iter, &ctx->cinfo_tree.all_stream, all_stream, struct cap_info)

	{

		if(iter->codec == CCX_CODEC_ISDB_CC)

			return iter->pid;

	}

	list_for_each_entry(iter, &ctx->cinfo_tree.all_stream, all_stream, struct cap_info)

	{

		if(iter->codec == CCX_CODEC_ATSC_CC)

			return iter->pid;

	}

	return -1;

}

**Comment by MakarovGCI2018** [comment]
@anshul1912 thank you for the explanation. I will try to find out why this function doesn't work correct :-)

**Comment by rboy1** [comment]
Thanks. As a user how do I know which PID? Isn’t there a way for ccextractor to pick it up automatically like you said if the preferred doesn’t exist but it found another one?

**Comment by MakarovGCI2018** [comment]
@rboy as for now we don't support skipping fake pid. By the way, adding this function will increase get_best_stream method time .
You can get best stream pid with external programs(Take a look on mediaInfo where right pid is ID/String, VLC detected streams where pid is Original ID or ffprobe tool). Also you can get info about possible pids using -parsePMT parameter in ccextractor.

**Comment by xvkdev** [comment]
Parsepmt lists all pids.
A possible solution could be to delay selecting the stream until data has
been found.

**Comment by rboy1** [comment]
Just checking in if this would be something that would be addressed in .89?

**Comment by jshin313** [comment]
Is this still an issue? When I run `windows\Debug\ccextractorwin.exe "..\Closed Caption EIA.ts"` I get the following:

```
CCExtractor 0.88, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: ..\Closed Caption EIA.ts
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: Auto] [Debug: No] [Buffer input: Yes]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .srt] [Encoding: UTF-8] [Delay: 0] [Trim lines: No]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No][Filter profanity: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]
[Quantisation-mode: CCExtractor's internal function]


-----------------------------------------------------------------

Opening file: ..\Closed Caption EIA.ts

File seems to be a transport stream, enabling TS mode

Analyzing data in general mode
  1%  |  00:00
  2%  |  00:00
  3%  |  00:00


New video information found
[704 * 480] [AR: 02 - 4:3] [FR: 04 - 29.97] [progressive: no]

  4%  |  00:01
  5%  |  00:01
  6%  |  00:02
  7%  |  00:02
  8%  |  00:03
  9%  |  00:03
 10%  |  00:04
 11%  |  00:04
 12%  |  00:05
 13%  |  00:05
 14%  |  00:05
 15%  |  00:06
 16%  |  00:06
 17%  |  00:07
 18%  |  00:07
 19%  |  00:08
 20%  |  00:08
 21%  |  00:08
 22%  |  00:09
 23%  |  00:09
 24%  |  00:10
 25%  |  00:10
 26%  |  00:11
 27%  |  00:11
 28%  |  00:12
 29%  |  00:12
 30%  |  00:13
 31%  |  00:13
 32%  |  00:14
 33%  |  00:14
 34%  |  00:15
 35%  |  00:15
 36%  |  00:15
 37%  |  00:16
 38%  |  00:16
 39%  |  00:17
 40%  |  00:17
 41%  |  00:18
 42%  |  00:18
 43%  |  00:19
 44%  |  00:19
 45%  |  00:20
 46%  |  00:20
 47%  |  00:21
 48%  |  00:21
 49%  |  00:22
 50%  |  00:22
 51%  |  00:23
 52%  |  00:23
 53%  |  00:24
 54%  |  00:24
 55%  |  00:24
 56%  |  00:25
 57%  |  00:25
 58%  |  00:26
 59%  |  00:26
 60%  |  00:27
 61%  |  00:27
 62%  |  00:28
 63%  |  00:29
 64%  |  00:29
 65%  |  00:30
 66%  |  00:30
 67%  |  00:31
 68%  |  00:31
 69%  |  00:31
 70%  |  00:32
 71%  |  00:32
 72%  |  00:33
 73%  |  00:33
 74%  |  00:34
 75%  |  00:34
 76%  |  00:35
 77%  |  00:35
 78%  |  00:36
 79%  |  00:36
 80%  |  00:37
 81%  |  00:37
 82%  |  00:38
 83%  |  00:38
 84%  |  00:39
 85%  |  00:39
 86%  |  00:40
 87%  |  00:40
 88%  |  00:41
 89%  |  00:41
 90%  |  00:42
 91%  |  00:42
 92%  |  00:43
 93%  |  00:43
 94%  |  00:44
 95%  |  00:44
 96%  |  00:45
 97%  |  00:46
 98%  |  00:46
 99%  |  00:47
100%  |  00:47

Number of NAL_type_7: 0
Number of VCL_HRD: 0
Number of NAL HRD: 0
Number of jump-in-frames: 0
Number of num_unexpected_sei_length: 0

Total frames time:	  00:00:46:312  (1388 frames at 29.97fps)

CC type 0: 413 (NTSC line 21 field 1 closed captions)
CC type 1: 3 (NTSC line 21 field 2 closed captions)
CC type 2: 0 (DTVCC Channel Packet Data)
CC type 3: 0 (DTVCC Channel Packet Start)
incl. pulldown frames:  00:00:09:242  (277 frames at 29.97fps)

Min PTS:				00:09:50:316
Max PTS:				00:10:36:679
Length:				 00:00:46:363

Initial GOP time:	   12:45:21:600
Final GOP time:		 12:46:07:900 +1F
Diff. GOP length:	   00:00:46:300 +1F	(00:00:46:333)

Number of key frames: 38
Total user data fields: 1111
HDTV type user data fields: 1111

Done, processing time = 0 seconds
Issues? Open a ticket here
https://github.com/CCExtractor/ccextractor/issues
```

**Comment by NilsIrl** [comment]
works for me

**Comment by rboy1** [comment]
Not working with the latest release
```
C:\ccextractor>ccextractorwinfull.exe "..\Closed Caption EIA.ts"
CCExtractor 0.88, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: ..\Closed Caption EIA.ts
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: Auto] [Debug: No] [Buffer input: Yes]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .srt] [Encoding: UTF-8] [Delay: 0] [Trim lines: No]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]
[Quantisation-mode: CCExtractor's internal function]

-----------------------------------------------------------------
Opening file: ..\Closed Caption EIA.ts
File seems to be a transport stream, enabling TS mode
Analyzing data in general mode
  3%  |  00:00

New video information found
[704 * 480] [AR: 02 - 4:3] [FR: 04 - 29.97] [progressive: no]

100%  |  00:47
Number of NAL_type_7: 0
Number of VCL_HRD: 0
Number of NAL HRD: 0
Number of jump-in-frames: 0
Number of num_unexpected_sei_length: 0

Total frames time:        00:00:46:312  (1388 frames at 29.97fps)
CC type 0: 413 (NTSC line 21 field 1 closed captions)
CC type 1: 3 (NTSC line 21 field 2 closed captions)
CC type 2: 0 (DTVCC Channel Packet Data)
CC type 3: 0 (DTVCC Channel Packet Start)
incl. pulldown frames:  00:00:09:242  (277 frames at 29.97fps)

Min PTS:                                00:09:50:316
Max PTS:                                00:10:36:679
Length:                          00:00:46:363

Initial GOP time:          12:45:21:600
Final GOP time:          12:46:07:900 +1F
Diff. GOP length:          00:00:46:300 +1F     (00:00:46:333)

Number of key frames: 38
Total user data fields: 1111
HDTV type user data fields: 1111
Done, processing time = 1 seconds
Issues? Open a ticket here
https://github.com/CCExtractor/ccextractor/issues
```

**Comment by NilsIrl** [comment]
The output you gave seems to work. It doesn't say "No captions were found in input."

**Comment by rboy1** [comment]
Yes it appears to be working with the latest release, closing the ticket. Any idea when the next release 0.89 is due?

**Comment by cfsmp3** [comment]
Wondering why each of those runs have different values for CC type 0

CC type 0: 413 (NTSC line 21 field 1 closed captions)
That's definitely data :-)
Just to confirm, is there an output .srt file that contains something?

**Comment by NilsIrl** [comment]
@cfsmp3 was planning to do it during the Christmas break but apparently it didn't happen.

**Comment by NilsIrl** [comment]
> Just to confirm, is there an output .srt file that contains something?

yes, It has captions

**Comment by cfsmp3** [comment]
Yes, 0.89 was due two weeks ago :-) I guess we'll do it after GCI is over,
so possibly next weekend.
