### ISSUE TITLE
[BUG] Issue while building ccextractor with cmakefile

### ISSUE THREAD

**Issue by satyammittal** [CCExtractor/ccextractor#762]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : **0.85**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [x] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [ ] NO | [ ] YES - *please specify the last known working version*
- What platform did you use? [] Windows - [X] Linux - [ ] Mac : Ubuntu Gnome
- What where the used arguments? `-autoprogram`
Commands I used:
```
cd src
cmake .
make
```

**Video links**

Please make the affected input file available for us (no screenshots, those don't help!). Public links to Dropbox, Google Drive, etc, are all fine. If it is not possible to make it available publicly, send us a private invitation (both Dropbox and Google Drive allow that). In this case we will download the file and upload it to the private developer repository.

Do *not* upload your file to any location that will require us to sign up or endure a wait list, slow downloads, etc. If your upload expires make sure you keep it active somehow (replace links if needed). Keep in mind that while we go over all tickets some may take a few days, and it's important we have the file available when we actually need it.

**Additional information**
**Error:**
```
make[2]: *** No rule to make target '/win_iconv/iconv.h', needed by 'lib_ccx/CMakeFiles/ccx.dir/hardsubx_classifier.c.o'.  Stop.
CMakeFiles/Makefile2:122: recipe for target 'lib_ccx/CMakeFiles/ccx.dir/all' failed
make[1]: *** [lib_ccx/CMakeFiles/ccx.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```
## **log file**: [https://pastebin.com/E8HyYL6f](https://pastebin.com/E8HyYL6f)
{issue content here, replace this line with your issue content}
I am trying to build using cmake. But facing issue. May be some specific issue for gnome os. Log file link is attached.

PS: Make sure you set an alert in GitHub so you get notifications about your ticket. We may need to ask questions and we do everything inside GitHub's system.

**Comment by saurabhshri** [comment]
From your error log @satyammittal , it's evident that the makefile tries to compile `/win_iconv/iconv.h` even when the platform is Linux. The reason is the set of commands you are issuing.

You are generating makefile from cmake in the same directory where the libraries resides. Please create a separate folder in which you intend to keep the built files so that they don't get mixed with source files. 

Please try the instructions as mentioned in the [compiling section](https://github.com/CCExtractor/ccextractor#compiling) of the readme file and report back, i.e. : 

```
git clone https://github.com/CCExtractor/ccextractor.git
cd ccextractor/
mkdir build
cd build
cmake ../src/
make
./ccaligner
```

**Comment by satyammittal** [comment]
@saurabhshri  Thanks it works. May be some cache issue of cmake. :)
