### ISSUE TITLE
[PROPOSAL] Make UTF-8 the default output encoding

### ISSUE THREAD

**Issue by aaaxx** [CCExtractor/ccextractor#766]
Pretty self-explanatory, I believe.

I can't think of any good reason to keep it Latin-1, especially since even English captions usually use music symbols, which are then replaced with a garbage character.

Actually, might as well go ahead and get rid of other options entirely and always output UTF-8; it's 2017, not 1997. 😎

**Comment by cfsmp3** [comment]
UTF-8 has been the default in CCExtractor for quite a while already. 

options->enc_cfg.encoding = CCX_ENC_UTF_8;

Cannot get rid of the others. Some players and tools (Subrip being one) still assume Latin-1 as default (and may be the only thing they support).

**Comment by aaaxx** [comment]
Hmm, that's odd: a clean install defaults to Latin-1 for me (v0.85).

**Comment by cfsmp3** [comment]
Is this windows or linux?

**Comment by aaaxx** [comment]
Windows.
