### ISSUE TITLE
[BUG] ccextractor HEAD do not link anymore (missing python_extract_g608_grid)

### ISSUE THREAD

**Issue by fredericgermain** [CCExtractor/ccextractor#774]
it seems python_extract_g608_grid is a recent addition

make errors I have on my fedora 25 : 

[100%] Linking C executable ccextractor
lib_ccx/libccx.a(ccx_encoders_python.c.o): In function `pass_cc_buffer_to_python':
/home/fred/workspaces/langues/subtitle_detect/ccextractor/src/lib_ccx/ccx_encoders_python.c:32: undefined reference to `python_extract_g608_grid'
/home/fred/workspaces/langues/subtitle_detect/ccextractor/src/lib_ccx/ccx_encoders_python.c:36: undefined reference to `python_extract_g608_grid'
/home/fred/workspaces/langues/subtitle_detect/ccextractor/src/lib_ccx/ccx_encoders_python.c:39: undefined reference to `python_extract_g608_grid'
/home/fred/workspaces/langues/subtitle_detect/ccextractor/src/lib_ccx/ccx_encoders_python.c:42: undefined reference to `python_extract_g608_grid'
/home/fred/workspaces/langues/subtitle_detect/ccextractor/src/lib_ccx/ccx_encoders_python.c:45: undefined reference to `python_extract_g608_grid'
collect2: error: ld returned 1 exit status
CMakeFiles/ccextractor.dir/build.make:251: recipe for target 'ccextractor' failed

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [X I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X]):**

- [X] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [ ] NO | [X] YES - *please specify the last known working version* : git checkout 21eaa3de^
- What platform did you use? [ ] Windows - [x] Linux - [ ] Mac
- What where the used arguments? `-autoprogram`

**Video links**

Please make the affected input file available for us (no screenshots, those don't help!). Public links to Dropbox, Google Drive, etc, are all fine. If it is not possible to make it available publicly, send us a private invitation (both Dropbox and Google Drive allow that). In this case we will download the file and upload it to the private developer repository.

Do *not* upload your file to any location that will require us to sign up or endure a wait list, slow downloads, etc. If your upload expires make sure you keep it active somehow (replace links if needed). Keep in mind that while we go over all tickets some may take a few days, and it's important we have the file available when we actually need it.

**Additional information**

{issue content here, replace this line with your issue content}

PS: Make sure you set an alert in GitHub so you get notifications about your ticket. We may need to ask questions and we do everything inside GitHub's system.

**Comment by saurabhshri** [comment]
@cfsmp3 fixed through #781 !
