### ISSUE TITLE
Integrate libexplain to provide better error explanations

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#792]
http://libexplain.sourceforge.net/ 

is a library that wraps a number of OS calls and on failure provide useful description of what went wrong. It seems like a good idea to integrate it, and not really a lot of work.

**Comment by MatejMecka** [comment]
Libexplain will only work on Linux and Mac sadly.

Sadly there also external dependencies that will need to be installed using a packet manager which I don't think the End user would want. 

The external dependencies a user would need to install is: libcap
* lsof
* GNU libtool
* bison
* GNU Groff
* GCC

Which would result in a 4 additional depedencies that will only work for Linux and Mac.

**Comment by TheFaR8** [comment]
More information can be seen [here](https://gist.github.com/TheFaR8/0c0971389074746c9052525cbd8908dc)

**Comment by cfsmp3** [comment]
Closing, definitely more work than anticipated. Not going to happen.

**Comment by TheFaR8** [comment]
The only problem is lsof because usually GNU/Linux user has already got their packet installed (the one came from GNU or Linux kernel).
