### ISSUE TITLE
[BUG] ver 0.85b  Option code --sentencecap or -sc   does not work 

### ISSUE THREAD

**Issue by tjmorris11** [CCExtractor/ccextractor#829]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : **X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

-[x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [ ] NO | [x] YES - *please specify the last known working version*
- What platform did you use? [x] Windows - [ ] Linux - [ ] Mac
- What where the used arguments? `-autoprogram`

**Video links**   https://www.dropbox.com/s/omar8vkh6ncgeq1/Judge%20Judy%29.ts?dl=0

Please make the affected input file available for us (no screenshots, those don't help!). Public links to Dropbox, Google Drive, etc, are all fine. If it is not possible to make it available publicly, send us a private invitation (both Dropbox and Google Drive allow that). In this case we will download the file and upload it to the private developer repository.

Do *not* upload your file to any location that will require us to sign up or endure a wait list, slow downloads, etc. If your upload expires make sure you keep it active somehow (replace links if needed). Keep in mind that while we go over all tickets some may take a few days, and it's important we have the file available when we actually need it.

**Additional information**

 OPTION -sc  OR --sentencecap   does Not work .... it should make every thing lowercase ( except first letter in each sentence)  BUT does not work in version .85b .   does not work in CLI  or  ccextractorGUI

PS: Make sure you set an alert in GitHub so you get notifications about your ticket. We may need to ask questions and we do everything inside GitHub's system.

**Comment by tjmorris11** [comment]
Hi  ....   what do I do now ...
      
               I clicked on  #842  
      and found the issue was proving to fail ( on windows  and in
      teletext) 
      -- do I wait for update emails from you          OR               
      do I just follow  #842
      
      thanks Trevor
    
    
    
    On 12/23/2017 9:50 AM, Carlos Fernandez
      Sanz wrote:
    
    
      Closed #829
        via #842.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CCExtractor/ccextractor","title":"CCExtractor/ccextractor","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/CCExtractor/ccextractor"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #829 via #842."}],"action":{"name":"View Issue","url":"https://github.com/CCExtractor/ccextractor/issues/829#event-1400241018"}}}

**Comment by mahalwal** [comment]
Hi
@tjmorris11 Please follow the fix from #842. The windows build is failing due to some other reasons.

--
Manish
