### ISSUE TITLE
[Bug] Python Bindings don't compile with build_library

### ISSUE THREAD

**Issue by MatejMecka** [CCExtractor/ccextractor#879]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : **0.85**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [x] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [x] NO | [ ] YES - *please specify the last known working version*
- What platform did you use? [ ] Windows - [X] Linux - [] Mac
- What where the used arguments? `N/A // python api_testing.py <pathtovideofile>`

**Video links**

Please make the affected input file available for us (no screenshots, those don't help!). Public links to Dropbox, Google Drive, etc, are all fine. If it is not possible to make it available publicly, send us a private invitation (both Dropbox and Google Drive allow that). In this case we will download the file and upload it to the private developer repository.

Do *not* upload your file to any location that will require us to sign up or endure a wait list, slow downloads, etc. If your upload expires make sure you keep it active somehow (replace links if needed). Keep in mind that while we go over all tickets some may take a few days, and it's important we have the file available when we actually need it.

**Additional information**

`ImportError: No module named _ccextractor`

Steps to reproduce:
1. Install bindings via pip
2. Clone repo from github 
3. Go into the API directory and do `./build_api`
4. Run `api_testing.py`
5. Error

PS: Make sure you set an alert in GitHub so you get notifications about your ticket. We may need to ask questions and we do everything inside GitHub's system.

**Comment by cfsmp3** [comment]
Most likely you need to define PYTHON_API now... do it and send a PR :-)

**Comment by thealphadollar** [comment]
@cfsmp3 @MatejMecka I would like to work on this issue. Can you please guide me a bit on how can I fix this bug?

**Comment by thealphadollar** [comment]
@MatejMecka The issue seems to be more than just a problem with build.api

With the latest build, and following the documentation named "python extension module.txt", no new file is being generated in the directory and I'm getting an error, "Error: Invalid option to CCextractor Library"

![See the error](https://user-images.githubusercontent.com/32812320/35485330-2566d9aa-0484-11e8-99ed-979fc3ec38bb.png)

By using the "build_api" the earlier issue is resolved since the file, "_ccextrator.so", which was not ealier created is now created. But the same above issues pops up.

![After using build_api](https://user-images.githubusercontent.com/32812320/35485365-c27dca6e-0484-11e8-8bce-438bf19117fd.png)

I think we should update the issue name, or maybe close the issue since it has been replaced by a new error.

**Comment by lennonwoo** [comment]
@thealphadollar Py bindings now doesn't print detail infomation well if we use if some error happens.

But your problem is missing args, try to add input file? ```python api_testing.py <video filename>```

**Comment by thealphadollar** [comment]
@lennonwoo @MatejMecka @cfsmp3 This error is no more produced, though there is no apparent output produced by running api_testing.py with an argument. Shouldn't this be closed now?

**Comment by cfsmp3** [comment]
Closing, reopen if needed @MatejMecka
