### ISSUE TITLE
[BUG] -out=spupng with EIA608/teletext: tags are rendered as-is. 

### ISSUE THREAD

**Issue by harrynull** [CCExtractor/ccextractor#892]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : 0.86

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [X] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [X] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [ ] NO | [X] YES - *please specify the last known working version* 377dc2a48d7dbe7d94d552a7deb430512b3a2c3b
- What platform did you use? All platforms should have this issue.
- What where the used arguments? `-out=spupng`

**Additional information**

![sub0060](https://user-images.githubusercontent.com/7413706/34649418-d03fbd34-f3e9-11e7-82e2-5e7ab617f644.png)
Example of tag rendered as-is.

The issue is introduced in pr #877 , when changing the old implementation to the new FreeType one. The tags are not parsed and rendered as-is.

You can refer to the old implementation for the parsing part (I didn't look into it so I don't know if the old code can apply): 377dc2a48d7dbe7d94d552a7deb430512b3a2c3b

PS: Make sure you set an alert in GitHub so you get notifications about your ticket. We may need to ask questions and we do everything inside GitHub's system.

**Comment by cfsmp3** [comment]
@harrynull This is your thing now :-) If you found something is now broken, just send a new PR to fix it. No one more qualified than you.

**Comment by harrynull** [comment]
I will try to fix it probably after GCI, when I have a winter break. I am too busy right now.

**Comment by cfsmp3** [comment]
Closing since it's in theory fixed. @harrynull can you confirm and reopen if needed?
