### ISSUE TITLE
GSOC - Multiprogram

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#9]
In the digital world, a number of programs are transmitted simultaneously (multiplexed) in a single channel. The tuner receives all those programs, and then the receiver filters the one the user wants to watch, discarding all the others. CCExtractor does this too - if a stream contains more than one program you have to pick one. The goal is to modify CCExtractor so it's able to process all programs in the stream at the same time, generating the transcript for all of them in one pass.

**Comment by anshul1912** [comment]
Multiprogram support is completed as part of GSOC 15, using ccextractor with -multiprogram option allow user to output caption of multiple programs

**Comment by anshul1912** [comment]
This feature can be tested using /newRepository/TestFiles/General/Closedcaption_atsc_multiprog.ts in our gsoc repository.

using following cmd:
./ccextractor -multirogram  /newRepository/TestFiles/General/Closedcaption_atsc_multiprog.ts

**Comment by cfsmp3** [comment]
I'm assigning this to Willem to validate and make sure our test suite deals OK with multiprogram, if it does I'll close the ticket.

**Comment by cfsmp3** [comment]
Sample TS: https://drive.google.com/drive/folders/0B_61ywKPmI0TQTZEMm5Tajd5RVU

**Comment by cfsmp3** [comment]
Closing - confirmed working.
