### ISSUE TITLE
[PROPOSAL] flag to automatically set delay such that the subtitles start at zero time

### ISSUE THREAD

**Issue by kshepherd2013** [CCExtractor/ccextractor#900]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : **0.85**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [X] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [X] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [X] NO | [ ] YES - *please specify the last known working version*
- What platform did you use? [ ] Windows - [X] Linux - [ ] Mac
- What where the used arguments? -teletext -datapid 5603 -tpage 888 "Horrible Histories_20180113_1123.ts" -o "Horrible Histories_20180113_1123.srt"
second run (to make it work correctly) added -delay -31344625
**Video links**
https://mega.nz/#!AM1QFRQZ!nVz8ZLUjzI4OUK97YqWqGP_ajAsp1PdSxebnF4WNHKc
Please make the affected input file available for us (no screenshots, those don't help!). Public links to Dropbox, Google Drive, etc, are all fine. If it is not possible to make it available publicly, send us a private invitation (both Dropbox and Google Drive allow that). In this case we will download the file and upload it to the private developer repository.

Do *not* upload your file to any location that will require us to sign up or endure a wait list, slow downloads, etc. If your upload expires make sure you keep it active somehow (replace links if needed). Keep in mind that while we go over all tickets some may take a few days, and it's important we have the file available when we actually need it.

**Additional information**

I have been relying on ccextractor v0.77 for a long time to extract srt files from mythtv recorded videos.  I have recently switched to a humax foxsat hdr, and 0.77 could not extract, so I updated to 0.86 (says 0.85 from the command line) which works really well.  My only problem is that there is now a huge offset in the time codes.  I am getting around this by running ccextractor twice.  The first time I parse out the Min PTS:     HH:MM:SS:mmm string, and then use this to work out the millisec offset for a negative "-delay" for the second run.  This is creating exactly what I need, but I wondered if there is a flag to ensure that timecodes start with zero at the beginning of the video file?  I looked through the code and could not see one.   Thank you for a great program!

Output:
CCExtractor 0.85, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: /mnt/foxsat_hdr_video/Horrible Histories/Horrible Histories_20180113_1123.ts
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: Auto] [Debug: No] [Buffer input: No]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .srt] [Encoding: UTF-8] [Delay: -31344625] [Trim lines: No]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: 888]
[Start credits text: None]

-----------------------------------------------------------------
Opening file: /mnt/foxsat_hdr_video/Horrible Histories/Horrible Histories_20180113_1123.ts
File seems to be a transport stream, enabling TS mode
Analyzing data in general mode

This TS file has more than one program. These are the program numbers found: 
6961
6960
6963
6940
6941
6972
6952
6945
6943
VBI/teletext stream ID 5603 (0x15e3) for SID 6952 (0x1b28)
Notice: Teletext page with possible subtitles detected: 888
100%  |  29:01
Teletext decoder: 43550 packets processed 

Number of NAL_type_7: 0
Number of VCL_HRD: 0
Number of NAL HRD: 0
Number of jump-in-frames: 0
Number of num_unexpected_sei_length: 0

Min PTS:                                08:42:24:625
Max PTS:                                09:11:26:585
Length:                          00:29:01:960
Done, processing time = 249 seconds
Issues? Open a ticket here
https://github.com/CCExtractor/ccextractor/issues

PS: Make sure you set an alert in GitHub so you get notifications about your ticket. We may need to ask questions and we do everything inside GitHub's system.

**Comment by cfsmp3** [comment]
We'd need to get a sample file so we can take a look, but that "huge offset" sounds like a bug...

**Comment by kshepherd2013** [comment]
Did you try the one that I provided, above?
https://mega.nz/#!AM1QFRQZ!nVz8ZLUjzI4OUK97YqWqGP_ajAsp1PdSxebnF4WNHKc
Should I change the title to [BUG], do you think?
I was not sure of expected behaviour, because earlier versions of ccextractor do not work on this TS, and I was using mythtv TS files before, which start at 0 PTS.

**Comment by cfsmp3** [comment]
It seems correct to me, this is the start of the generated .srt. Are you
seeing something different?

1
00:00:02,760 --> 00:00:03,759
CRASH!

2
00:00:05,520 --> 00:00:06,519
AWKWARD LAUGH

3
00:00:12,400 --> 00:00:13,639
# Terrible Tudors
<font color="#ffff00"># Gorgeous Georgians</font>

4
00:00:13,680 --> 00:00:14,799
# Slimy Stewarts
<font color="#ffff00"># Vile Victorians</font>

**Comment by cfsmp3** [comment]
@kshepherd2013 video no longer available, please open a new ticket if you still have issues.
