### ISSUE TITLE
[PROPOSAL] Add some Unit Test for CCExtractor

### ISSUE THREAD

**Issue by FlyingTwigs** [CCExtractor/ccextractor#911]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : **X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used CCExtractor.
- [x] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [ ] NO | [ ] YES - *please specify the last known working version*
- What platform did you use? [ ] Windows - [ ] Linux - [ ] Mac
- What where the used arguments? `-autoprogram`

**Video links**

Please make the affected input file available for us (no screenshots, those don't help!). Public links to Dropbox, Google Drive, etc, are all fine. If it is not possible to make it available publicly, send us a private invitation (both Dropbox and Google Drive allow that). In this case we will download the file and upload it to the private developer repository.

Do *not* upload your file to any location that will require us to sign up or endure a wait list, slow downloads, etc. If your upload expires make sure you keep it active somehow (replace links if needed). Keep in mind that while we go over all tickets some may take a few days, and it's important we have the file available when we actually need it.

**Additional information**
We need to add some unit test to CCExtractor to make sure things run properly (as the latest unit test commit is a year ago)

PS: Make sure you set an alert in GitHub so you get notifications about your ticket. We may need to ask questions and we do everything inside GitHub's system.

**Comment by MatejMecka** [comment]
This is part of the ccx_testsuite where it's purpose is to Test CCExtractor. There is already an issue there for writing unit tests.

https://github.com/CCExtractor/ccx_testsuite/issues/7

**Comment by harrynull** [comment]
I think that issue is to write unit tests for ccx_testsuite, instead of CCExtractor.

**Comment by canihavesomecoffee** [comment]
Just to be clear:
- There is an issue open to add unit tests to the Test Suite
- There is an issue open to add unit tests to the Sample Platform
- There's no issue open to add unit tests for CCExtractor.

However, if tests can be added for CCExtractor, why not?

**Comment by cfsmp3** [comment]
> @canihavesomecoffee don't we have CI tests of CCExtractor for pull requests already, so what will make unit tests different from that?

Those are integration tests - end to end. But they don't really test individual parts of the code, so when a commit break something all we know from the CI is that something broke :-)

I don't know however how unit tests would work for us, with the huge amount of spaguetti code we've accumulated over the years. 

I think we should try to have unit tests for Rust code as we port/rewrite, but I wouldn't bother with the C code.
