### ISSUE TITLE
[BUG] outputting as .raw (CC data in McPoodle's broadcast format) crashes ccextractorwin in versions after 0.69

### ISSUE THREAD

**Issue by The-Bart-The** [CCExtractor/ccextractor#915]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : **0.85**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [X] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [X] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [ ] NO | [X] YES - *please specify the last known working version* 0.69
- What platform did you use? [X] Windows - [ ] Linux - [ ] Mac
- What where the used arguments?  -in=ts -out=raw

**Video links**

https://www.dropbox.com/s/4hkkalo43whxcbq/Fresh%20Off%20the%20Boat_2018.01.16_first%20fifteen.ts?dl=1

Please make the affected input file available for us (no screenshots, those don't help!). Public links to Dropbox, Google Drive, etc, are all fine. If it is not possible to make it available publicly, send us a private invitation (both Dropbox and Google Drive allow that). In this case we will download the file and upload it to the private developer repository.

Do *not* upload your file to any location that will require us to sign up or endure a wait list, slow downloads, etc. If your upload expires make sure you keep it active somehow (replace links if needed). Keep in mind that while we go over all tickets some may take a few days, and it's important we have the file available when we actually need it.

**Additional information**

Newer versions of ccextractorwin seem to crash when outputting as *.raw (CC data in McPoodle's broadcast format). This happens whether I'm using Win 7-32 or -64, whether I'm using the installed app or the portable app, and whether I've instantiated from the GUI (CCExtractorGUI) or the command-line.  All the other outputs work fine.

The linked video file is MPEG-2 ATSC (containing cea-608 captions) recorded via an OTA antenna on a Windows 7 32 machine running the latest NextPVR.  It was cut using Avidemux 2.7.0 64-bit, although the same error occurs on an uncut, NextPVR-only file.

Thank you in advance.

PS: Make sure you set an alert in GitHub so you get notifications about your ticket. We may need to ask questions and we do everything inside GitHub's system.

**Comment by cfsmp3** [comment]
Can't reproduce - most likely fixed already.

Give it a try with this binary:
https://drive.google.com/drive/folders/1xBY85iuwUxkuARMu-XVRlXKp3D6ghkZ4?usp=sharing

Reopen the issue if it crashes for you.

**Comment by The-Bart-The** [comment]
cfsmp3, the new binary runs without crashing.  Thank you.

However, running -in=raw -out=srt on the resultant .raw file produces a bad subtitle file; whereas a .raw file created by 0.69 is properly converted in both versions.

But, I suppose that's a separate bug.
