### ISSUE TITLE
[PROPOSAL] Extract subtitles in a Chinese newscast

### ISSUE THREAD

**Issue by Liontooth** [CCExtractor/ccextractor#918]
The following video file was was recorded in mainland China, using Joker-tv with the DTMB television standard. When I watch it, I'm seeing what looks like subtitles / captions. Can CCExtractor see them? I was not able to get it to work. I did not try OCR, which may be what is required.

http://vrnewsscape.ucla.edu/dropbox/2018-01-09_2033_CN_CCTV1_%e6%96%b0%e9%97%bb1+1.mpg

Cheers,
David

**Comment by jimboH** [comment]
I would like to work on this issue.

**Comment by saurabhshri** [comment]
Sure, just go ahead.

**Comment by cfsmp3** [comment]
Assigned to @Abhinav95 which in turn will assign it to the GSoC student(s) he sees fit.

**Comment by fewwwww** [comment]
Just browsing GSoC issues, looking to work on the flutter project but I think I can help out a little bit with this issue.

Here is the document for the global standard of DTMB (GB20600-2006), 130 pages all in Chinese:
     https://www.doc88.com/p-810688531386.html
Here is a patent of a hardware that is able to separate audio and video signals and display subtitles on DTMB equipment:
    https://nxgp.cnki.net/kcms/detail?v=kxaUMs6x7-4I2jr5WTdXti3zQ9F92xu0N5Lim4gHJeVFMNAZBuVUfzvmz2LuJgb7bn8rlgaJH4AQ98pqdK9FqNLQT3L2E_Cs&uniplatform=NZKPT
Here is tons of recordings of DTMB televisions on Bilibili (can be downloaded by tools like you-get):
    https://search.bilibili.com/all?keyword=dtmb&from_source=nav_search_new

Feel free to move on or maybe write proposals with all these vital links. I really like to work on this issue, but for this issue, the solver definitely needs to know two languages: C and Chinese. I happen to know about Chinese but not much C.

**Comment by cfsmp3** [comment]
@fewwwww This is great, thanks! 
Let's hope there's a brave student that knows C and feels like doing this with your help :-)

**Comment by cfsmp3** [comment]
Closing to keep track of our Chinese wishlist here: https://github.com/CCExtractor/ccextractor/issues/224
