### ISSUE TITLE
[GSoC] [PROPOSAL] Add YouTube-TV Captions Support.

### ISSUE THREAD

**Issue by saurabhshri** [CCExtractor/ccextractor#931]
CCExtractor version (using the --version parameter preferably) : **0.87**

**In raising this issue, I confirm the following (please check boxes, eg [X] - and delete unchecked ones):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X] - and delete unchecked ones):**

- [ ] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [x] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [x] NO | [ ] YES - *please specify the last known working version*
- What platform did you use? [x] Windows - [x] Linux - [x] Mac
- What were the used arguments? `-autoprogram`
---

One of the GSoC ideas we're planning is adding support for Live TV over the internet and [YouTube TV](https://tv.youtube.com) is one of them. Read more about the project idea here : [https://www.ccextractor.org/public:gsoc:livetvooverinternet](https://www.ccextractor.org/public:gsoc:livetvooverinternet).

We can use this issue to discuss about the progress and findings since there are no official specification as of yet. 

Here's the summary of research so far : 

1. **Captions of the recorded shows (DVR)** are received by sending a request to `/api/timedtext` by the video player and the response is a XML file containing the timed transcription. These transcriptions can be rolled up normal, which I guess depends on parameters while sending the request.

Here's the sample request (I've removed sensitive information with `@` symbol : 

```
/api/timedtext?xorp=True&key=yttt1&sparams=asr_langs%2Ccaps%2Cv%2Cxorp%2Cexpire&v=@@@@@@&caps=asr&signature=@@@@@@@@@@@@@@@@@@@@@@.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&asr_langs=pt%2Cit%2Cfr%2Cnl%2Ces%2Cru%2Cko%2Cen%2Cde%2Cja&hl=en_GB&expire=1518827803&lang=es&name=CC1&fmt=srv3
```

and here's a sample response snippet : 

```
<?xml version="1.0" encoding="utf-8" ?><timedtext format="3">
<head>
<pen id="1" i="1" fs="3"/>
<ws id="1" ju="0"/>
<wp id="3" ap="0" ah="0" av="0" cc="31"/>
<wp id="5" ap="0" ah="0" av="0" rc="1" cc="31"/>
<wp id="4" ap="0" ah="0" av="0" rc="2" cc="31"/>
<wp id="6" ap="0" ah="0" av="0" rc="3" cc="31"/>
<wp id="9" ap="0" ah="0" av="55" rc="3" cc="31"/>
<wp id="8" ap="0" ah="0" av="60" rc="2" cc="31"/>
<wp id="7" ap="0" ah="0" av="65" cc="31"/>
<wp id="2" ap="0" ah="0" av="65" rc="1" cc="31"/>
<wp id="1" ap="0" ah="0" av="70" cc="31"/>
<wp id="10" ap="0" ah="0" av="70" rc="2" cc="31"/>
</head>
<body>
<w t="16182" d="1869" id="1" wp="1" ws="1"/>
<p t="16182" d="1869" w="1" p="1">&quot;The Walking Dead&quot;...</p>
<w t="18051" d="1034" id="1" wp="2" ws="1"/>
<p t="18051" d="1034" w="1">Th-They were warning shots
above your head.</p>
<w t="19085" d="1735" id="1" wp="2" ws="1"/>
<p t="19085" d="1735" w="1">He wasn&#39;t shooting
at you.</p>
<w t="20820" d="4071" id="1" wp="1" ws="1"/>
<p t="20820" d="4071" w="1"><s>This place</s><s p="1">is</s><s>gonna fall.</s></p>
<w t="24891" d="2102" id="1" wp="2" ws="1"/>
<p t="24891" d="2102" w="1">I am not dying until
I am damn good and ready.</p>
<w t="26993" d="1335" id="1" wp="1" ws="1"/>
<p t="26993" d="1335" w="1">[Tires squeal]</p>
<w t="28328" d="3670" id="1" wp="1" ws="1"/>
<p t="28328" d="3670" w="1">[Walkers snarling]</p>
```

Here's the complete response attached : 
[timedtext.txt](https://github.com/CCExtractor/ccextractor/files/1732266/timedtext.txt).

I manually sniffed the traffic to obtain this, but of course we don't want to have a browser and check traffic manually and making everything automatic maybe hard. [On the related note : we had a GSoC project (created by @abhishek-vinjamoori) two years ago - which scraped/obtained subtitles from online services such as Netflix.]

2. **Captions in live shows** are fetched as the broadcast progresses. I contacted YouTube TV support (who were fantastic and super supportive btw - they did not encounter such request before - but were happy to find out about it and reply) and their response basically was that the broadcast is a single stream, unaltered as received by them (but since it was not the developers I talked to, so we should probably not take the words and do our own research).

The live captions are fetched by sending a request to `/api/manifest/rawcc` and the response is some binary data prefixed by `RCC`.

Here's the sample request (I've removed sensitive information with `@` symbol : 

```
/api/manifest/rawcc?id=@@@@@@@@@&itag=133&source=yt_tv_broadcast&cmbypass=yes&ctier=UL&ei=@@@@@@@@@@@@@&gcr=us&hightc=yes&playlist_type=DVR&ratebypass=yes&live=1&cpn=@@@@@@@@@@&mpd_version=5&ip=199.116.72.167&ipbits=0&expire=1518825649&sparams=ip,ipbits,expire,id,itag,source,cmbypass,ctier,ei,gcr,hightc,playlist_type,ratebypass,live&signature=@@@@@@@@@@@@@@@@@@@@@@@@@.@@@@@@@@@@@@@@@@@@@@@&key=dg_yt0&alr=yes&c=WEB_UNPLUGGED&cver=0.1&sq=1329958
```

and here's a sample response snippet : 

```
RCC{¼Ev{¿ÁÖ# H{Âwåò{ÅfE C#AV{ÈUyb{ËDÁ #E {Î3ïd{Ñ!ÄEÃ#A {Ôy {ÖþÁL#DE{ÙíLï{ÜÜ¿C#AL{ßËË{âº/"?Ã$ð{å¨{è{ë¡{îu{ñdË{ôR{÷A{ú/{ý{
{üÐ{ë{Ù{È{·{¦{hì{{r{`{ O{#>{&-TÎ{){,
T {.ù{1èWE{4×{7ÆÓT{:´{=£  {@{CR{Fo{I^{LM{O;Óu{R*{Upå{X{Z÷òn{]å{`Ôaô{cÂ{f±uò{i {laì{o~{rl [{u[{xJÓÁ{{9{~(Ð]{{, {ó{âEv{Ñ{Àåò{¯{yb{{{ïd{j{¡Yy {¤G{§6Lï{ª${­Ë{°{²ñ{µà{¸Î¡{»½{¾¬Ë{Á{Ä{Çx{ÊgÐ{ÍU{ÐD{Ó3{Ö"{Ù{Ûÿhì{Þî{áÝ{äÌ{ç»{ê©{íTÎ{ð{óuT {öd{ùSWE{üB{ÿ0ÓT{Bð{,{ý{
ì{
Ú{É  {·{¦R{{{s{"aÓu{%P{(?på{+.{.òn{1 {3úaô{6è®B"ð{9×uò{<Æ
R(A)Ã#'{?µaì*{B¤ÙO{E [{HÕ C#YO{KpÓÁ{N_ÓT#U {QNÐ]{T<ILÃ#ST{W+, {ZL #IL{]Ev{_÷ÎEC#L {bæåò{eÕEÄ#NE{hÃyb{k²
pÃ#ED)A)
{n¡	ïdC#'*{q¡Ã#{ty {wmTO{z\Lï{}J Ó#TO{9Ë{(WEC# S{{ET#WE{ô{ãEÎÃ#ET{Ò¡{Á T#EN{°Ë{ÈEC# T{{ { Ð#HE{£jÐ{¦YOTÃ# P{©H{¬7®#OT{¯%{²/B".$ð{µhì{·ò{ºá{½Ï{À¾{Ã¬{Æ{É{ÌyTÎ{Ïh{ÒVT {ÕE{Ø4WE{Û#{ÞÓT{á{ãï  {æÝ{éÌR{ì»{ïª{ò{õÓu{øv{ûepå{þT{Còn{1{ aô{
{ýuò{ìÂBð{Û,{Ê{¸{§{aì{!{$t [{'b{*QÓÁ{-?{0.Ð]{3{6, {8û{;éEv{>Ø{AÇåò{D¶{G¥yb{J{Mïd{Pp{S_y {VN{Y=Lï{\,{_Ë{b	{dø{gç{jÖ¡{mÄ{p³Ë{s¡{v{y{|nÐ{]{K{:{){{hì{õ{ä{Ò{Á{°{TÎ{¢{¥|T {¨k{«ZWE{®I{±8ÓT{´&{·  {º{¼òR{¿á{ÂÐ{Å¿{È­Óu{Ë{Îpå{Ñz{Ôiòn{×W{ÚFaô{Ý4{à#uò{ã{æaì{èð{ëÞ [{îÍ{ñ¼ÓÁ{ô«{÷Ð]{ú{ýw, {e{TEv{C{	2åò{!{yb{þ{íïd{Ü{Ëy {¹{ ¨Lï{#{&Ë{)t
```
The response is also attached as a binary file here : [rawcc.txt](https://github.com/CCExtractor/ccextractor/files/1732337/rawcc.txt) .

Several such responses are received with time and the binary data probably contains the captions, but I haven't been able to make much sense of it.

After discussing with Carlos, I tried stripping the parity bit in each byte and show it in ASCII (applying &0x7f to each of them) , but the result did not make much sense to me - maybe I did something wrong. I'd be happy to provide more such received responses.

I also tried looking how they are handling this response, and they are (probably - not sure) are doing this using : https://s.ytimg.com/yts/jsbin/player_ias-vfliDr87C/en_GB/captions.js

I tried going through it, set few breakpoints, but the JS is not at all documented. All the variable names are letters and I don't really know (and have adequate time to figure out) what's going on there. 

The XML for DVR captions can be also understood from the above attached JS.

Please feel free to add your findings and correct if I assumed something wrong.

**Comment by meetDeveloper** [comment]
I would like to work on this issue, but I currently don't have subscription of YouTube TV. I think I will be able to scrap the subtitles once I am able to look in their workings.

**Comment by cfsmp3** [comment]
From what we're seeing - this is definitely not like scraping a web site.

**Comment by meetDeveloper** [comment]
Yeah, maybe, I would like to try it out, and see the internal working, I
went to the website to get the free trial, but they ask for card and I
don't have one.

**Comment by cfsmp3** [comment]
@meetDeveloper you can collaborate with @saurabhshri for now... work with him for the initial research.

While we will provide a youtube subscription to accepted GSoC students, we cannot do it for anyone else I'm afraid.

**Comment by meetDeveloper** [comment]
@saurabhshri   I wanted to study the source, I think I might able to decode how live shows are captioned, how should I go about it?

**Comment by saurabhshri** [comment]
@meetDeveloper Sure! DM me on Slack. Same username.

**Comment by saurabhshri** [comment]
If someone wants to look at the raw data that is decoded for the captions, I am attaching it all below.

I played the live shows and captured the raw caption data received by the player, along with the captions it displayed during that time period. Decoding the response should yield at least some of the text in transcription.

The first two folders, named `FIRST` & `SECOND` contains multiple files, each file a separate request/response object. It contains everything need to be known about that transaction. The files `TRANSCRIPTION` contain the captions that were displayed and are typed exactly as seen.

The `THIRD` folder contains two files, `RESPONSES` which contains just the binary rawcc data sent. Each response is marked by `RCC` in the beginning. The captions displayed during that time are in `TRANSCRIPTION` file.

The captions is the first two directories is broadcasted with a delay (probably captioned live), while in 3rd they are perfectly in sync.

https://drive.google.com/open?id=1H_npv96SpiJJhAbFtaJ9HMV7V1SfAg5r

**Comment by meetDeveloper** [comment]
I did some research, They are most probably CEA-608, or CEA-708 subtitles, as network YoutubeTV supports sends captions for live tv using these two standards, and google has created a ExoPlayer library for media players, that have functionality to extract subtitles from rawcc file, look at [this](https://google.github.io/ExoPlayer/doc/reference/index.html?com/google/android/exoplayer2/extractor/rawcc/package-summary.html), so most probably what youtube is doing is getting those live caption provided by network, which are in either CEA-608, or CEA-708, decoding them and displaying them.

**Comment by cfsmp3** [comment]
I'd expect them to be CEA-608 and 708 at their source, but I'd say it's
unlikely (but I wouldn't bet either way) that that's what the players
actually get. I guess we'll need to analyze data dumps to find out for sure.

**Comment by meetDeveloper** [comment]
Look at this exoplayer that google is experimenting with https://google.github.io/ExoPlayer/doc/reference/index.html?com/google/android/exoplayer2/extractor/rawcc/package-summary.html, it can extract RawCC.

**Comment by saurabhshri** [comment]
@meetDeveloper This looks just like the right thing. Glancing at the code I can see it looks for `RCC` as header ID, which matches with captured data. So, we know we're definitely going in right direction. 

Did you try to see if you're able to get the matching transcription from the dumps?

**Comment by meetDeveloper** [comment]
@saurabhshri Yeah, I looked in the code, they are looking for rcc in the header, I am currently analyzing it and performing experiments, hopefully we will get a lead from here. I think we are in right direction.

**Comment by meetDeveloper** [comment]
@saurabhshri  See this dump of rawcc that they use, extension was rawcc, this was exactly what we also got, I am now sure they are the same, please tell me what do you think.
[sample.txt](https://github.com/CCExtractor/ccextractor/files/1745196/sample.txt)

**Comment by meetDeveloper** [comment]
@saurabhshri  I would like to do this as my summer project in gSoc, Could you tell me the steps?

**Comment by cfsmp3** [comment]
@meetDeveloper Come find us on slack :-)

**Comment by cfsmp3** [comment]
Closing, since Youtube now support most of the formats we export.
