### ISSUE TITLE
[BUG] SRT from WTV file results in garbled random unreadable text

### ISSUE THREAD

**Issue by sjtsnix** [CCExtractor/ccextractor#938]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : **0.85**

**In raising this issue, I confirm the following (please check boxes, eg [X] - and delete unchecked ones):**

- [X ] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ X] I have checked that the issue I'm posting isn't already reported.
- [ X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [X ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [X] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X] - and delete unchecked ones):**

- [X] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [X] NO | [ ] YES - *please specify the last known working version*
- What platform did you use? [X] Windows - [ ] Linux - [ ] Mac
- What were the used arguments? 
C:\Program Files (x86)\CCExtractor\ccextractorwinfull.exe  --gui_mode_reports  -autoprogram  -out=srt -bom -cf C:\Users\sj\Desktop\CCExtractor_Elementary_Text.txt -latin1 [+input files]

**Video links (replace text below with your links) **

https://1drv.ms/f/s!Aji9dqqvSe1MZ85Mb4a5sjrMwo4

**Additional information**

Originally attempted to use CCExtractor with MCEBuddy per: 
https://discussion.mcebuddy2x.com/t/how-to-enable-dvb-and-image-subtitle-extraction/154
and result was a SRT file with random garbled text.

Upon discovering there was a GUI version of CCExtractor, I downloaded, installed it, and dragged the referenced WTV file into it and resulting SRT file has random Garbled Text.  That file is available at the link above as well.

I use Two HD HomeRun Prime devices to record all my content on a Windows 7x64 pro desktop.

Let me know if you need any further info.

SJ

PS: Make sure you set an alert in GitHub so you get notifications about your ticket. We may need to ask questions and we do everything inside GitHub's system.

**Comment by cfsmp3** [comment]
GSoC qualification: 7 points

**Comment by thetransformerr** [comment]
hi @sjtsnix , I had been working on this issue, and wanted to ask if any more such videos are available with you , where srt generated is garble , or this is the only one you are facing prob??

Also if possible please share a video of small  size.
Thanks

**Comment by thetransformerr** [comment]
hi @cfsmp3 , @sjtsnix , I did some tweak in cc functions for wtv but still was unable to resolve this issue, may be it would have been much more helpful if I had some more videos for testing. With currently given video,I am unable to play it in VLC with subtitles, and even windows media player can't play it.

**Comment by l3ob** [comment]
same issue here
got two video recordings in wtv: https://1drv.ms/f/s!Avg7I-USP1V9bP_RmWhFddC3aI4
see if it can help @thetransformerr

**Comment by thetransformerr** [comment]
hi @l3ob , I will surely start again with new videos and get back to you , thanks for new titles

**Comment by thetransformerr** [comment]
hey @l3ob from the files you provided , you were getting right subtitles , but the problem was , it was randomly sprayed with this  
`B"` 

and I was able to get perfect sub with using flag -wtvmpeg2 with ccextractor

ccextractor -wtvmpeg2 Arrow_WDCW_2018_03_29_21_00_01.wtv 

also I am attaching both files here 

[Arrow_WDCW_2018_03_29_21_00_01.srt.txt](https://github.com/CCExtractor/ccextractor/files/1896178/Arrow_WDCW_2018_03_29_21_00_01.srt.txt)
[de2.srt.txt](https://github.com/CCExtractor/ccextractor/files/1896179/de2.srt.txt)


@cfsmp3

**Comment by cfsmp3** [comment]
If -wtvmpeg2 solves the problem then there's no bug here, just use it. -wtvmpeg2 means "use the CC from the MPEG streams instead of the separate WTV caption data". 

WTV is a closed format, we don't have official specs. 

As long as we have an usable solution (adding a specific parameter definitely is usable) I'm happy here.

Closing this.
