### ISSUE TITLE
[BUG] CC extractor not reading captions on HEVC transport stream 

### ISSUE THREAD

**Issue by DenverJoe** [CCExtractor/ccextractor#942]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : **X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X] - and delete unchecked ones):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [ ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ ] I have checked that the issue I'm posting isn't already reported.
- [ ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [ ] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X] - and delete unchecked ones):**

- [ ] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [x] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [ ] NO | [ ] YES - *please specify the last known working version*
- What platform did you use? [ ] Windows - [ ] Linux - [ ] Mac
- What were the used arguments? `-autoprogram`

**Video links (replace text below with your links) **

Please make the affected input file available for us (no screenshots, those don't help!). Public links to Dropbox, Google Drive, etc, are all fine. If it is not possible to make it available publicly, send us a private invitation (both Dropbox and Google Drive allow that). In this case we will download the file and upload it to the private developer repository.

Do *not* upload your file to any location that will require us to sign up or endure a wait list, slow downloads, etc. If your upload expires make sure you keep it active somehow (replace links if needed). Keep in mind that while we go over all tickets some may take a few days, and it's important we have the file available when we actually need it.

**Additional information**

{issue content here, replace this line with your issue content}

PS: Make sure you set an alert in GitHub so you get notifications about your ticket. We may need to ask questions and we do everything inside GitHub's system.

**Comment by cfsmp3** [comment]
We cannot do anything here - please submit some samples for us to look at.

**Comment by DenverJoe** [comment]
Sure, where do you want some samples uploaded?

**Comment by canihavesomecoffee** [comment]
@DenverJoe Ideally you can upload them on the sample platform (https://sampleplatform.ccextractor.org) so that we can add it to the regression tests once we add support/fix it.

**Comment by cfsmp3** [comment]
Usually dropbox or google drive, but anywhere you want - just send us the
links so we can download them.
Please don't use any place that requires us to create an account, or pay to
download a decent speeds, etc.

**Comment by DenverJoe** [comment]
ftp://sam.ateme.com/JoeJohnson/Encompass/EDM-ANTI/CC%20TEST/ESPNCaribbean.TS

ftp://support@sam.ateme.com/JoeJohnson/Encompass/EDM-ANTI/CC%20TEST/history.ts

ftp://sam.ateme.com/JoeJohnson/Encompass/EDM-ANTI/CC%20TEST/NBCOlympicsClose.ts

**Comment by DenverJoe** [comment]
I added some FTP download locations.  Let me know what you think.

Thanks
Joe

**Comment by cfsmp3** [comment]
Can we make a copy of these files and post them on our website so
developers can use them?

**Comment by DenverJoe** [comment]
Sure but for development only. Not for public consumption.

On Feb 26, 2018, 4:28 PM -0700, Carlos Fernandez Sanz <notifications@github.com>, wrote:
Can we make a copy of these files and post them on our website so
developers can use them?

**Comment by cfsmp3** [comment]
We would post them here:

https://ccextractor.org/public:general:tvsamples

Otherwise you can just leave them in your FTP server so people following
the ticket can download them from there. But if you prefer this please
don't delete them. It can takes us a while to get to this ticket, and it
happens very often than when someone volunteers to look into a ticket the
relevant files are gone.

**Comment by DenverJoe** [comment]
Ok

On Feb 26, 2018, 6:38 PM -0700, Carlos Fernandez Sanz <notifications@github.com>, wrote:
We would post them here:

https://ccextractor.org/public:general:tvsamples

Otherwise you can just leave them in your FTP server so people following
the ticket can download them from there. But if you prefer this please
don't delete them. It can takes us a while to get to this ticket, and it
happens very often than when someone volunteers to look into a ticket the
relevant files are gone.
