### ISSUE TITLE
No result from french channels with dvb subtitles

### ISSUE THREAD

**Issue by tsmarinov** [CCExtractor/ccextractor#949]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : **X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X] - and delete unchecked ones):**

- [X ] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [X] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X] - and delete unchecked ones):**

- [ ] I have never used CCExtractor.
- [X] I have used CCExtractor just a couple of times.
- [X] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [X] NO | [ ] YES - *please specify the last known working version*
- What platform did you use? [ ] Windows - [X] Linux - [ ] Mac
- What were the used arguments? `-autoprogram`
./ccextractor -quant 2 -in=ts -datapid 0x4db -out=srt -stdout -nobom -trim -noteletext -codec dvbsub -dvblang fra -ocrlang fra c8.ts

**Video links (replace text below with your links) **
https://goo.gl/kncQUn

**Additional information**

{issue content here, replace this line with your issue content}

PS: Make sure you set an alert in GitHub so you get notifications about your ticket. We may need to ask questions and we do everything inside GitHub's system.

There are several channels with dvb subtitles but ccextractors outputs nothing however i could get spupng. I see the subtitles in vlc and mpc. I'm using the latest commit a0e7ddd

here is the arguments
./ccextractor -quant 2 -in=ts -datapid 0x4db -out=srt -stdout -nobom -trim -noteletext -codec dvbsub -dvblang fra -ocrlang fra ./merged/c8.ts

and the result is:

```
CCExtractor 0.87, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: ./merged/c8.ts
[Extract: 1] [Stream mode: Transport]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: Auto] [Debug: No] [Buffer input: No]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .srt] [Encoding: UTF-8] [Delay: 0] [Trim lines: Yes]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]

-----------------------------------------------------------------
Opening file: ./merged/c8.ts
Analyzing data in general mode
Sending captions to stdout.
 99%  |  01:55dvbsub_decode: incomplete, broken or empty packet, remaining bytes=570, segment_length=829
Return from dvbsub_decode: -1
100%  |  01:56
Number of NAL_type_7: 0
Number of VCL_HRD: 0
Number of NAL HRD: 0
Number of jump-in-frames: 0
Number of num_unexpected_sei_length: 0

Min PTS:                                09:25:43:140
Max PTS:                                09:27:39:380
Length:                          00:01:56:240
Done, processing time = 7 seconds

No captions were found in input.
Issues? Open a ticket here
https://github.com/CCExtractor/ccextractor/issues
```
Every channel is with similar output. Here is the link https://goo.gl/kncQUn with source ts, outputs, spupng that I've got. Arguments that I've use are in terminal.txt

**Comment by tsmarinov** [comment]
Yes. Sorry. there was some problem while uploading the files. Now it is OK

**Comment by tsmarinov** [comment]
I've included tracesports.ts which has 6 languages and cannot get the the Romanian language but it is there however I can get the pngs. Similar result with Chinese language also in tracesports.ts

**Comment by thealphadollar** [comment]
The issue does happen but something weird I noticed about the subtitles is that they appear with a lot of noise and three instances appear on the screen at the same time. This could mean there might be some issues with the bundled closed captions of these transport streams.

![screenshot from 2018-03-09 13-26-39](https://user-images.githubusercontent.com/32812320/37196932-b7273aa4-239e-11e8-8a27-a4a9e157267d.png)

![screenshot from 2018-03-09 13-26-59](https://user-images.githubusercontent.com/32812320/37196933-b800448e-239e-11e8-9eec-a9ff06fefb86.png)

**Comment by tsmarinov** [comment]
With VLC and Media Player Classic there is no problem (Windows) and in tracesports there is no problem extracting spanish language

![vlcsnap-2018-03-09-11h09m57s217](https://user-images.githubusercontent.com/3245642/37199777-520b6afe-238b-11e8-9237-bd980175987e.jpg)

![vlcsnap-2018-03-09-11h12m14s262](https://user-images.githubusercontent.com/3245642/37199771-4c2b6030-238b-11e8-9dda-20e6208a098c.jpg)

**Comment by cfsmp3** [comment]
@tsmarinov We believe this is fixed in the current master. Let us know if you still have problems (feel free to reopen).
