### ISSUE TITLE
[BUG] Reading mp4 file switch to next idx before finish processing

### ISSUE THREAD

**Issue by AlexandrGraschenkov** [CCExtractor/ccextractor#952]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : **from master**

**In raising this issue, I confirm the following (please check boxes, eg [X] - and delete unchecked ones):**

- [ ] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [ ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ ] I have checked that the issue I'm posting isn't already reported.
- [ ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [X] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X] - and delete unchecked ones):**

- [ ] I have never used CCExtractor.
- [X] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [ ] NO | [ ] YES - *please specify the last known working version*
- What platform did you use? [ ] Windows - [ ] Linux - [X] Mac
- What were the used arguments? `-autoprogram`

**Video links (replace text below with your links) **

https://drive.google.com/open?id=13Jga959y2UjujePkKnqPdoiShi75sboX

**Additional information**

When process mp4 file `ctx->current_file` move to next index before previous file complete processing. So app fall down cause have wrong idx. Here is [code](https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/file_functions.c#L432) witch call increment file idx.

PS: Make sure you set an alert in GitHub so you get notifications about your ticket. We may need to ask questions and we do everything inside GitHub's system.

**Comment by cfsmp3** [comment]
That index is increased only when a file has been processed completely. I cannot reproduce any problem here, small.mp4 was processed correctly.

Please reopen the ticket with the exact parameters you're using (if processing more than one file, then the list of all of them).

**Comment by AlexandrGraschenkov** [comment]
Yes, subtitles is generated, but program fail with error. If you can run program in debug mode, you probably immediately find the problem.
For test you can try comment this [line](https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/file_functions.c#L432), and see the log after execution. The log for me is different(more complete).
