### ISSUE TITLE
Option -unixts isn't working on vtt/smptett/ttxt output 

### ISSUE THREAD

**Issue by boldmss** [CCExtractor/ccextractor#965]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : **X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X] - and delete unchecked ones):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X] - and delete unchecked ones):**

- [ ] I have never used CCExtractor.
- [x] I have used CCExtractor just a couple of times.
- [x] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [X] NO | [ ] YES - *please specify the last known working version*
- What platform did you use? [ ] Windows - [X] Linux - [ ] Mac
- What were the used arguments? `-autoprogram`

**Video links (replace text below with your links) **

Please make the affected input file available for us (no screenshots, those don't help!). Public links to Dropbox, Google Drive, etc, are all fine. If it is not possible to make it available publicly, send us a private invitation (both Dropbox and Google Drive allow that). In this case we will download the file and upload it to the private developer repository.

Do *not* upload your file to any location that will require us to sign up or endure a wait list, slow downloads, etc. If your upload expires make sure you keep it active somehow (replace links if needed). Keep in mind that while we go over all tickets some may take a few days, and it's important we have the file available when we actually need it.

**Additional information**

{issue content here, replace this line with your issue content}

PS: Make sure you set an alert in GitHub so you get notifications about your ticket. We may need to ask questions and we do everything inside GitHub's system.

HI, 
I am trying to get vtt or smptett output with UNIX timestamp related to system time and this options seems to don't work as it should, please check the following line.

**********************************
test@ubuntu:~/ccextractor/linux$ ./ccextractor -unixts 0 -nofc -nots -ocrlang spa -out=ttxt ../../test.ts -o salida.ttxt
CCExtractor 0.87, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: ../../test.ts
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: Auto] [Debug: No] [Buffer input: No]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .txt] [Encoding: UTF-8] [Delay: 0] [Trim lines: No]
[Add font color data: No] [Add font typesetting: No]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]
[Quantisation-mode: CCExtractor's internal function]

-----------------------------------------------------------------
Opening file: ../../test.ts
File seems to be a transport stream, enabling TS mode
Analyzing data in general mode
100%  |  02:46
Number of NAL_type_7: 0
Number of VCL_HRD: 0
Number of NAL HRD: 0
Number of jump-in-frames: 0
Number of num_unexpected_sei_length: 0

Min PTS:				00:00:00:000
Max PTS:				00:02:46:961
Length:				 00:02:46:961
Done, processing time = 6 seconds

No captions were found in input.
Issues? Open a ticket here
https://github.com/CCExtractor/ccextractor/issues

***************************************************

 A cat of 'salida.ttxt' file:

test@ubuntu:~/ccextractor/linux$ cat salida.vtt 
00:00:02,883|00:00:08,390|DVB|con música, entrevistas,
médicos y psiquiatras 
00:00:08,390|00:00:11,039|DVB|discutiendo los peligros
de la adicción. 
00:00:11,039|00:00:15,020|DVB|¿Qué haría él en nuestro
especial para la televisión? 
00:00:15,020|00:00:20,216|DVB|Podría cantar temas
relacionados con las drogas 
00:00:20,216|00:00:23,973|DVB|que los jóvenes escuchen,
al igual que los padres, 
00:00:23,973|00:00:27,424|DVB|para que entiendan mejor
las drogas 
00:00:27,424|00:00:31,657|DVB|y los temas revolucionarios que
infiltraron el rock and roll. 
00:00:31,768|00:00:35,332|DVB|Podría invitar a otros artistas
a unirse a la campaña 
00:00:35,427|00:00:39,189|DVB|y que desarrollen otros
temas para el rock and roll. 
00:00:39,283|00:00:42,778|DVB|Ya veo, para que canten
todos juntos. 
00:00:42,778|00:00:46,357|DVB|Sí, moderno,
pero con temas apropiados. 
00:00:46,357|00:00:49,918|DVB|Algo como "Elévate con la vida". 
00:00:49,918|00:00:53,877|DVB|"Elévate con la vida".
Eso me gusta. 
00:00:56,159|00:00:59,421|DVB|-¿Qué más?
-Eso es todo, señor. 
00:00:59,421|00:01:03,982|DVB|Además de eso,
también quiere una placa. 
00:01:05,523|00:01:06,836|DVB|¿Qué? 
00:01:06,836|00:01:08,990|DVB|Una placa de Agente Federal
General. 
00:01:09,089|00:01:12,879|DVB|Está muy interesado
en esa placa. 
00:01:12,986|00:01:14,923|DVB|Ya veo. 
00:01:15,020|00:01:18,264|DVB|Ya veo. Bien. 
00:01:22,403|00:01:27,090|DVB|Sr. Presidente,
¿concertamos la cita? 
00:01:27,183|00:01:29,300|DVB|-No.
-Pero Sr. Presidente... 
00:01:29,397|00:01:34,733|DVB|No voy a traer a un roquero
a la Oficina Oval, por Dios. 
00:01:34,733|00:01:40,397|DVB|Díganle que lo intente
cuando ganen los Demócratas. 
00:01:40,397|00:01:43,676|DVB|¿Qué está pasando con Ford
en el Congreso? 
00:01:43,676|00:01:48,590|DVB|Leí esa historia anoche
y es de lo más ridícula. 
00:01:48,685|00:01:52,199|DVB|Es alcohólico, ¿cierto? 
00:01:52,389|00:01:54,221|DVB|Maldición, lo teníamos. 
00:01:54,221|00:01:57,278|DVB|Sabía que lo negaría
antes de que entráramos. 
00:01:57,278|00:02:02,049|DVB|Odio eso. Es como si disfrutara
destruir a la gente. 
00:02:02,145|00:02:04,056|DVB|Así es. 
00:02:05,700|00:02:08,406|DVB|-¿Qué hacemos ahora?
-Iremos ante la Corte Suprema. 
00:02:08,504|00:02:09,546|DVB|Muy gracioso. 
00:02:09,644|00:02:13,782|DVB|Sí, déjame dar la mala noticia. 
00:02:27,764|00:02:29,883|DVB|-¿Puedo ponérmelos?
-Sí. 
00:02:29,978|00:02:34,115|DVB|-Son los lentes de Elvis.
-Eres hermosa. 
00:02:34,207|00:02:38,615|DVB|-¿En serio?
-Sí, eres preciosa. 
00:02:42,895|00:02:46,961|DVB|Hola, le estaba mostrando
tus lentes.

*****************************
You can download the test.ts file from:

https://www.dropbox.com/s/xnlstmpb5nqzn2q/test.ts?dl=0

Thanks in advance!!!!

**Comment by boldmss** [comment]
Hi, any news?

**Comment by cfsmp3** [comment]
@boldmss It might be fixed already in current master, can you confirm?

**Comment by boldmss** [comment]
Ok, let me check.

Thanks,

M

Enviado desde mi iPhone

**Comment by pavanjoshi914** [comment]
you are using a version of 0.87 have a try with 0.88 if any issue found feel free to discuss.

**Comment by cfsmp3** [comment]
Closing due to original poster not responding.
