### ISSUE TITLE
[BUG] Cannot extract teletext in Russian from NTV video

### ISSUE THREAD

**Issue by mahalwal** [CCExtractor/ccextractor#967]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : **0.86**

**In raising this issue, I confirm the following (please check boxes, eg [X] - and delete unchecked ones):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [X] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X] - and delete unchecked ones):**
- [X] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [X] NO | [ ] YES - *please specify the last known working version*
- What platform did you use? [ ] Windows - [X] Linux - [ ] Mac
- What were the used arguments? `-autoprogram`

**Video links (replace text below with your links) **

http://vrnewsscape.ucla.edu/dropbox/2017-07-31_1600_RU_%d0%9d%d0%a2%d0%92_%d0%a1%d0%b5%d0%b3%d0%be%d0%b4%d0%bd%d1%8f.mpg

**Additional information**
PS: Make sure you set an alert in GitHub so you get notifications about your ticket. We may need to ask questions and we do everything inside GitHub's system.
```
@ubuntu:~/ccextractor/ccextractor/linux$ ./ccextractor ../../923/2017-07-31_1600_RU_НТВ_Сегодня.mpg
CCExtractor 0.87, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: ../../923/2017-07-31_1600_RU_НТВ_Сегодня.mpg
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: Auto] [Debug: No] [Buffer input: No]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .srt] [Encoding: UTF-8] [Delay: 0] [Trim lines: No]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]
[Quantisation-mode: CCExtractor's internal function]

-----------------------------------------------------------------
Opening file: ../../923/2017-07-31_1600_RU_НТВ_Сегодня.mpg
File seems to be a transport stream, enabling TS mode
Analyzing data in general mode
VBI/teletext stream ID 1044 (0x414) for SID 1040 (0x410)
  0%  |  00:00- Programme Identification Data = FAB-TELETEXT SYSTEM 
- Universal Time Co-ordinated = Mon Jul 31 08:57:29 2017
100%  |  39:51
Teletext decoder: 59789 packets processed 

Number of NAL_type_7: 0
Number of VCL_HRD: 0
Number of NAL HRD: 0
Number of jump-in-frames: 0
Number of num_unexpected_sei_length: 0

Min PTS:				01:07:46:325
Max PTS:				01:47:37:845
Length:				 00:39:51:520
Done, processing time = 17 seconds

No captions were found in input.
Issues? Open a ticket here
https://github.com/CCExtractor/ccextractor/issues
```

PS: Make sure you set an alert in GitHub so you get notifications about your ticket. We may need to ask questions and we do everything inside GitHub's system.

**Comment by Sudoxo** [comment]
When I try to open that link, it says: **"404 Not Found"**.

**Comment by cfsmp3** [comment]
@mahalwal Closing because we can't access the file anymore, but feel free to reopen if you still have the problem and can update the link to the video.
