### ISSUE TITLE
[BUG] It does not work for mp4 and mpv format videoes, It creates an srt file, but file is completely empty.

### ISSUE THREAD

**Issue by vardhanshah** [CCExtractor/ccextractor#969]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : **X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X] - and delete unchecked ones):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [ ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ ] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [ ] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X] - and delete unchecked ones):**

- [ ] I have never used CCExtractor.
- [x] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [ ] NO | [ ] YES - *please specify the last known working version*
- What platform did you use? [ ] Windows - [ ] Linux - [ ] Mac
- What were the used arguments? `-autoprogram`

Videos is in my storage space. Videos of mp4, mpv format are playable in VLC Media Player.Videos are in English language.

Here is the output for one of the file

Ouput for : ./ccexctractor /media/OS/Movies/Sherlock.The.Abominable.Bride/sherlock.the.abominable.bride.mp4

--------------------------Start of ouput-----------------------------------------

CCExtractor 0.85, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: /media/OS/Movies/Sherlock.The.Abominable.Bride/sherlock.the.abominable.bride.mp4
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: Auto] [Debug: No] [Buffer input: No]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .srt] [Encoding: UTF-8] [Delay: 0] [Trim lines: No]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]

-----------------------------------------------------------------
Opening file: /media/OS/Movies/Sherlock.The.Abominable.Bride/sherlock.the.abominable.bride.mp4
Detected MP4 box with name: ftyp
Detected MP4 box with name: moov
File seems to be a MP4
Analyzing data with GPAC (MP4 library)
Creating /media/OS/Movies/Sherlock.The.Abominable.Bride/sherlock.the.abominable.bride.srt
Opening '/media/OS/Movies/Sherlock.The.Abominable.Bride/sherlock.the.abominable.bride.srt': ok
Track 1, type=vide subtype=avc1
Track 2, type=soun subtype=MPEG
MP4: found 2 tracks: 1 avc and 0 cc
Changed fps using NAL to: 25.000000
100%  |  89:18
Closing media: ok
Found 1 AVC track(s). Found no dedicated CC track(s).

Total frames time:	  01:29:17:880  (133947 frames at 25.00fps)

Min PTS:				00:00:00:039
Max PTS:				01:29:18:042
Length:				 01:29:18:003
Done, processing time = 3 seconds

----------------End of ouput-------------

PS: Make sure you set an alert in GitHub so you get notifications about your ticket. We may need to ask questions and we do everything inside GitHub's system.

**Comment by cfsmp3** [comment]
There doesn't seem to be subtitles here. 
In any case wthout access to the file there's nothing we can do.
