### ISSUE TITLE
[QUESTION] How can I compile extractor for iOS usage?

### ISSUE THREAD

**Issue by AlexandrGraschenkov** [CCExtractor/ccextractor#970]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : **X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X] - and delete unchecked ones):**

- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X] - and delete unchecked ones):**

- [x] I absolutely love CCExtractor, but have not contributed previously.

**Necessary information**
- What platform did you use? 
- [x] iOS
- What were the used arguments? `-autoprogram`

**Video links (replace text below with your links) **

Please make the affected input file available for us (no screenshots, those don't help!). Public links to Dropbox, Google Drive, etc, are all fine. If it is not possible to make it available publicly, send us a private invitation (both Dropbox and Google Drive allow that). In this case we will download the file and upload it to the private developer repository.

Do *not* upload your file to any location that will require us to sign up or endure a wait list, slow downloads, etc. If your upload expires make sure you keep it active somehow (replace links if needed). Keep in mind that while we go over all tickets some may take a few days, and it's important we have the file available when we actually need it.

**Additional information**

I'm trying build for start ccx library for iOS. Trying custom toolchain from [here](https://github.com/leetal/ios-cmake). For now with no success. Can you give some suggestion how to do that?

**Comment by cfsmp3** [comment]
It should compile fine using the standard build tools, with make. 
It can fails, paste the compile build sequence.
