### ISSUE TITLE
[BUG] Error: Parameter -o1/o2 not understood.

### ISSUE THREAD

**Issue by unicode45** [CCExtractor/ccextractor#973]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : 0,85b

**In raising this issue, I confirm the following (please check boxes, eg [X] - and delete unchecked ones):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X] - and delete unchecked ones):**

- [ ] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [x] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [x] NO | [ ] YES - *please specify the last known working version*
- What platform did you use? [x] Windows - [x] Linux - [ ] Mac
- What were the used arguments? `-o1 filename1.ext -o2 filename2.ext`

**Additional information**
Parameter -oN seems not working for a long time(I test on 0.7x to 0.85b but all failed).

**Comment by thealphadollar** [comment]
@unicode45, can you please detail the issue a bit more? I'm unable to see what video file was used and what *exactly* were the passed commands. 

That'll help us solve the issue faster :)

**Comment by thealphadollar** [comment]
@unicode45  Getting a little deeper into the issue, we never had an option like that. I've removed the instance of it in the help, I apologize for the misleading :D

**Comment by unicode45** [comment]
Thanks for the explanation. : )

**Comment by cfsmp3** [comment]
Well, o1 and o2 were valid options. Don't remember what we replaced them
with though.

**Comment by unicode45** [comment]
Here's a sample Korean ts file that I used.
https://drive.google.com/file/d/0B8AjqtxcLQDxeW5qT0RGSzQzZm8/view

I tried -o1 and -o2 option becuase *.p1.svc01.srt always containts the right Korean subtitle contents while .srt is empty.

**Comment by thealphadollar** [comment]
@unicode45  Are you sure this is the right file? I'm doubtful since ffprobe shows no subtitle stream and even vlc is not able to detect/play any CC.

![screenshot from 2018-05-12 21-12-19](https://user-images.githubusercontent.com/32812320/39959036-6023c9f8-5629-11e8-8482-64691c191b31.png)

**Comment by unicode45** [comment]
Sorry. this might be a better sample.
https://doc-00-2s-docs.googleusercontent.com/docs/securesc/dhkuk4q9mgunis2fm53qs8dpimqu3un0/49e70t76sald3e3on3027l7sotjdn2va/1526140800000/12314372573940017857/04182627330199378501/1dQGwjRP49mBU1FkrNrJEdIgkTrrQomNG?e=download

I've checked with MediaInfo and EIA-708 stream found.

**Comment by thealphadollar** [comment]
@unicode45 Ahh, maybe a problem at my side but the link is not working.

**Comment by unicode45** [comment]
How about this one?
https://drive.google.com/file/d/1OTLS_8SaKco_ZHXATz3p6Z-2H_WB-8dc/view?usp=drivesdk

**Comment by thealphadollar** [comment]
Hey @unicode45, please have a look at the [issue](https://github.com/CCExtractor/ccextractor/issues/374#issuecomment-222220372) that was created two years back regarding the same.

For eg.
To extract data from channel 2 of the stream, you can give a command like,
```bash
ccextractor [input_file] -2 -o [output_filename]
```
The `-o [output_filename]` can be omitted if you want to stick to default naming.

**Comment by unicode45** [comment]
Thanks for the information. 
As you mentioned, it was duplicated report.

**Comment by rayfoss** [comment]
These docs are really misleading... `-2` seems to be broken badly with multi track MP4's.

```
 -o outputfilename: Use -o parameters to define output filename if you don't
                       like the default ones (same as infile plus _1 or _2 when
                       needed and file extension, e.g. .srt).
                           -o or -o1 -> Name of the first (maybe only) output
                                        file.
                           -o2       -> Name of the second output file, when
                                        it applies.
```

**Comment by cfsmp3** [comment]
Yes. -o1 and -o2 were probably one of the first supported parameters and
they came from the 608-only days, where you could have 2 languages only.

If multilanguage doesn't work in .mp4 it's not really an issue with -o2
(which it's likely to just be implemented in 608).
