### ISSUE TITLE
[QUESTION] - I'm not able to extract CEA-708 CC from a MXF file

### ISSUE THREAD

**Issue by leocsantiago** [CCExtractor/ccextractor#981]
CCExtractor version (using the --version parameter preferably) : 0.85

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [X] I have used the latest available version of CCExtractor to verify this issue exists.

- [ ] I have never used CCExtractor.
- [X] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

- Is this a regression (did it work before)? [X] NO | [ ] YES - *please specify the last known working version*
- What platform did you use? [X] Windows - [ ] Linux - [ ] Mac
- What were the used arguments? `-svc`

https://drive.google.com/open?id=103S0QesAQferRkRBD9x1OADG82jXrQQy

I tried to extract the CEA-708 cc from a MXF file, but I had no success.

I need to extract a raw data and put it into a file again.

How can I do that?

Media info:

General
Complete name                            : C:\ffmpeg\bin\TEST_2ch_CC.MXF
Format                                   : MXF
Commercial name                          : HDV 1080i
Format version                           : 1.3
Format profile                           : OP-1a
Format settings                          : Closed / Complete
File size                                : 34.4 MiB
Duration                                 : 10 s 177 ms
Overall bit rate                         : 28.3 Mb/s
Encoded date                             : 2018-05-02 17:50:09.732
Writing application                      : Grass Valley K.K. EDIUS 8.3.2.1697

Video
ID                                       : 2
Format                                   : MPEG Video
Commercial name                          : HDV 1080i
Format version                           : Version 2
Format profile                           : Main@High 1440
Format settings                          : CustomMatrix / BVOP
Format settings, BVOP                    : Yes
Format settings, Matrix                  : Custom
Format settings, GOP                     : M=3, N=15
Format settings, picture structure       : Frame
Format settings, wrapping mode           : Frame
Codec ID                                 : 0D01030102046001-0401020201050300
Duration                                 : 10 s 177 ms
Bit rate mode                            : Constant
Bit rate                                 : 25.0 Mb/s
Width                                    : 1 440 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 29.970 (30000/1001) FPS
Standard                                 : Component
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Interlaced
Scan order                               : Top Field First
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.536
Time code of first frame                 : 00:00:00:00
Time code source                         : Group of pictures header
GOP, Open/Closed                         : Closed
Stream size                              : 30.3 MiB (88%)
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio #1
ID                                       : 3
Format                                   : PCM
Format settings                          : Little
Format settings, wrapping mode           : Frame (AES)
Codec ID                                 : 0D01030102060300
Duration                                 : 10 s 177 ms
Bit rate mode                            : Constant
Bit rate                                 : 768 kb/s
Channel(s)                               : 1 channel
Sampling rate                            : 48.0 kHz
Frame rate                               : 29.970 FPS (1601.6 SPF)
Bit depth                                : 16 bits
Stream size                              : 954 KiB (3%)
Locked                                   : Yes

Audio #2
ID                                       : 4
Format                                   : PCM
Format settings                          : Little
Format settings, wrapping mode           : Frame (AES)
Codec ID                                 : 0D01030102060300
Duration                                 : 10 s 177 ms
Bit rate mode                            : Constant
Bit rate                                 : 768 kb/s
Channel(s)                               : 1 channel
Sampling rate                            : 48.0 kHz
Frame rate                               : 29.970 FPS (1601.6 SPF)
Bit depth                                : 16 bits
Stream size                              : 954 KiB (3%)
Locked                                   : Yes

Text #1
ID                                       : 5-CC1
Format                                   : EIA-608
Muxing mode                              : Ancillary data / CDP
Duration                                 : 10 s 177 ms
Bit rate mode                            : Constant
Stream size                              : 0.00 Byte (0%)
CaptionServiceName                       : CC1

Text #2
ID                                       : 5-1
Format                                   : EIA-708
Muxing mode                              : Ancillary data / CDP
Duration                                 : 10 s 177 ms
Bit rate mode                            : Constant
Stream size                              : 0.00 Byte (0%)

Other #1
ID                                       : 1-Material
Type                                     : Time code
Format                                   : MXF TC
Time code of first frame                 : 00:00:00:00
Time code settings                       : Material Package
Time code, striped                       : Yes

Other #2
ID                                       : 1-Source
Type                                     : Time code
Format                                   : MXF TC
Time code of first frame                 : 00:00:00:00
Time code settings                       : Source Package
Time code, striped                       : Yes

Other #3
Type                                     : Time code
Format                                   : SMPTE TC
Muxing mode                              : SDTI
Time code of first frame                 : 00:00:00:00

**Comment by cfsmp3** [comment]
@leocsantiago is this still happening in current master?

**Comment by Sudoxo** [comment]
Everything seems to be working (I've tested on linux)

**Comment by cfsmp3** [comment]
Closing. @leocsantiago feel free to reopen if needed

**Comment by legettt** [comment]
Hi, 
I'm using a mac and I'm unable to extract captions from an MXF file.  @cfsmp3, would you be able to look into this issue again?

**Comment by cfsmp3** [comment]
> Hi, I'm using a mac and I'm unable to extract captions from an MXF file. @cfsmp3, would you be able to look into this issue again?

We'd need a sample file to test.

**Comment by legettt** [comment]
> > Hi, I'm using a mac and I'm unable to extract captions from an MXF file. @cfsmp3, would you be able to look into this issue again?
> 
> We'd need a sample file to test.

@cfsmp3 Sure! https://app.shift.io/review/615ccb899b4ce36551d6f8fd
