### ISSUE TITLE
Where is 0.86 (or even 0.87) windows version?  only 0.85 is in the download link

### ISSUE THREAD

**Issue by richcakes** [CCExtractor/ccextractor#982]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : **X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X] - and delete unchecked ones):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).

**My familiarity with the project is as follows (check one, eg [X] - and delete unchecked ones):**

- [X ] I absolutely love CCExtractor, but have not contributed previously.

**Necessary information**
- Is this a regression (did it work before)? [ ] NO | [X ] YES - *please specify the last known working version*  0.85
- What platform did you use? [X] Windows - [ ] Linux - [ ] Mac
- What were the used arguments? `-autoprogram`

**Video links (replace text below with your links) **

Please make the affected input file available for us (no screenshots, those don't help!). Public links to Dropbox, Google Drive, etc, are all fine. If it is not possible to make it available publicly, send us a private invitation (both Dropbox and Google Drive allow that). In this case we will download the file and upload it to the private developer repository.

Do *not* upload your file to any location that will require us to sign up or endure a wait list, slow downloads, etc. If your upload expires make sure you keep it active somehow (replace links if needed). Keep in mind that while we go over all tickets some may take a few days, and it's important we have the file available when we actually need it.

**Additional information**
Where is windows gui version 0.86.   I tried downloading it from your site and only 0.85 is there.  it says 0.86 but when I install it, it shows "CCExtractor GUI 0.85" at the top left on the program.
{issue content here, replace this line with your issue content}

PS: Make sure you set an alert in GitHub so you get notifications about your ticket. We may need to ask questions and we do everything inside GitHub's system.

**Comment by cfsmp3** [comment]
Not a bug. We haven't released it for Windows yet, but we'll do it when there's a new release.
