### ISSUE TITLE
[BUG] Hardsubx extraction from the sample stops at 11%

### ISSUE THREAD

**Issue by thealphadollar** [CCExtractor/ccextractor#983]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : **X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X] - and delete unchecked ones):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [X] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X] - and delete unchecked ones):**

- [X] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [ ] NO | [ ] YES - *please specify the last known working version*
- What platform did you use? [ ] Windows - [X] Linux - [ ] Mac
- What were the used arguments? `-hardsubx`

**https://drive.google.com/drive/u/0/folders/1yHZN4jQw24MIgFGrByUbUZahkUelQHD8**

**Additional information**

The sample present in the above link has hard subtitles embeded in the video and ccextractor is able to extract them till 11% and then it abruptly is killed. I was unable to figure out the reason for the stopping of the program.

![screenshot from 2018-05-15 15-21-48](https://user-images.githubusercontent.com/32812320/40059467-bc4be6da-5871-11e8-853f-f582cf3468a4.png)

System information:
OS: Ubuntu  16.04.4 LTS (Xenial Xerus)
System Memory: 1 GiB

**Comment by saurabhshri** [comment]
It's probably due to memory constraint, did you try it in an environment with more memory (it executes fine on my machine)?

**Comment by thealphadollar** [comment]
I'll try it and report back.

Though that makes me wonder, are there rooms to improve the efficiency
there?

I'm kind of naive at image processing but I think it is strange that one
gigabyte couldn't suffice.

**Comment by thealphadollar** [comment]
@saurabhshri  I'm closing this since  it's resource-related but, nevertheless, it would be amazing to see if we could make this feature less straining :smiley:
