### ISSUE TITLE
CEA-708 timing issue

### ISSUE THREAD

**Issue by thetransformerr** [CCExtractor/ccextractor#992]

**Comment by thetransformerr** [comment]
@cfsmp3 @canihavesomecoffee @Izaron @anshul1912 @alexbrt @MatejMecka 

Please provide your valuable suggestions

**Comment by starlord1311** [comment]
@thetransformerr can i take up this issue?

**Comment by MatejMecka** [comment]
Feel free to send a PR no need to notify us :)

**Comment by thetransformerr** [comment]
Yes , Of course you can , and I would recommend you to discuss it with @Carlos and other related members of group, and you might need to read cea-708 manual before or while working on this issue. Wish you a good luck.

**Comment by cfsmp3** [comment]
Closing, since there's no description at all to the actual issue.
