### ISSUE TITLE
[QUESTION] Support of ISDBT subtitles in ffmpeg

### ISSUE THREAD

**Issue by jakubvojacek** [CCExtractor/ccextractor#998]
CCExtractor version (using the --version parameter preferably) :e9d2a89768f10e6d269dcd0b9245895f3899a72d

**In raising this issue, I confirm the following (please check boxes, eg [X] - and delete unchecked ones):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X] - and delete unchecked ones):**

- [x] I absolutely love CCExtractor, but have not contributed previously.

**Necessary information**
- Is this a regression (did it work before)? [x] NO | [ ] YES 
- What platform did you use? [ ] Windows - [x] Linux - [ ] Mac

Hello, 

we are using ccextractor to extract dvb_teletext, dvb_subtitles and CEA-608 capitions and it works flawlessly. We are now having issues with ISDBT subtitles. They are supported with ccextractor but they seems not be supported in ffmpeg and we loose the subtitles from the stream while transcoding it. I know it is not an issue with ccextractor but I am posting anyway to see whether it would be possible to add support for ISDBT subtitles to ffmpeg (since you are familiar with the isdbt specs). *Please note that we are willing to consider this as a paid consultancy.*

A sample file to test with is available here https://goo.gl/iiKTAQ, I can extract the subtitles using 

```
ccextractor -datapid 0x116 -o test.vtt nsc.mp4
```

and it does extract cues into test.vtt file. But when the file is transcoded, for example using

```
ffmpeg -i nsc.mp4 -map 0 -c copy -f mp4 nsc_transcoded.mp4
```

The subtitles are no longer recognizable in nsc_transcoded.mp4. We cannot be extracting them from the original source because we are extracting them from a live source and we need timestamp of subtitles to be in sync with transcoded live stream, therefore we need to be extracting them from the transcoded live stream, which is not currently working.

If you are willing to help us, please let me know.

Thank you
Jakub

**Comment by cfsmp3** [comment]
Last time we tried to merge something into FFMpeg (specifically, SCTE-35) it was a nightmare due to "political" issues inside FFMpeg, and we only managed to get that partially merged. 

If you don't need this to be merged with the official FFMpeg we can look into it. Just send me an email (address is somewhere on our website) ad we can discuss it.
